/* ============================================================
   codex.js — 文法資料庫（大局觀記憶宮殿）的資料層
   ------------------------------------------------------------
   9 大章 → 節 → 條目，每條有永久座標（n），涵蓋 A1→B2 全境。
   顯示於 map.html 第三分頁「📚文法資料庫」；quiz/gram_trainer
   答題結果區用 codexLocate(topic) 顯示「📍 5-2-2」定位連結。

   ⚠️ 鐵律：座標一經指定永不變動、永不重編——這是 Owen 的記憶
   宮殿地址（他靠「明確位置」記憶）。之後新增條目只能在該節尾端
   取下一個號碼；就算條目作廢也保留號碼標 deprecated，不回收。

   欄位：n=座標 lvl=CEFR等級 name=中文名 fr=法文標籤 brief=一行摘要
   pts=說明條列 ex=[{fr,zh}]例句 exc=[例外] vs=[{n,note}]相似對比
   topics=[quiz topic]（每個topic全庫只出現一次，定位才唯一）
   gram=gram_rules.js 的文法點id（連去練習）
   章/節只有 n/name/fr（+節可掛 topics 當粗定位）。
   ============================================================ */

const CODEX = [

// ═══ 第 1 章 名詞與限定詞 ═══════════════════════════════════
{ n:'1', name:'名詞與限定詞', fr:'Le nom et ses déterminants', sections:[

 { n:'1-1', name:'名詞的性別', fr:'Le genre', items:[
  { n:'1-1-1', lvl:'A1', name:'陰陽性的本質', fr:'masculin / féminin',
    brief:'每個名詞出生就帶性別標籤，是分類籤不是意義',
    ex:[{fr:'Le livre est sur la table.', zh:'書（陽）在桌子（陰）上。'},
        {fr:'Le soleil et la lune.', zh:'太陽（陽）與月亮（陰）——德文剛好相反，可見跟意義無關'}],
    pts:[
      {r:'性別跟東西本身無關——桌子沒有女性特質，純粹是分類籤（拉丁文三性崩塌的遺產）',
       fr:'la table, la voiture', zh:'桌子、汽車（都是陰性，但沒有理由）'},
      {r:'背名詞永遠連冠詞一起背：不背 livre，背 le livre——冠詞就是性別標籤本人',
       fr:'le livre, la maison', zh:'背的時候整組一起唸出聲'},
      {r:'形容詞、冠詞、所有格全部看名詞穿制服——性別是全句性數配合的源頭',
       fr:'une grande maison blanche', zh:'一棟白色大房子（grande、blanche 都跟著 maison 變陰性）'},
    ],
    exc:['少數雙性別雙意義：le tour（一圈）vs la tour（塔）、le livre（書）vs la livre（磅）'],
    vs:[{n:'1-1-2', note:'判性靠字尾機率，不靠意義'}], gram:'articles' },
  { n:'1-1-2', lvl:'A2', name:'字尾判性訣竅', fr:'terminaisons',
    brief:'字尾可以猜性別，準確率八九成',
    ex:[{fr:'la nation, la santé, la culture', zh:'-tion／-té／-ure 結尾 → 猜陰性'},
        {fr:'le fromage, le gouvernement, le tourisme', zh:'-age／-ment／-isme 結尾 → 猜陽性'}],
    pts:[
      {r:'偏陰性字尾：-tion/-sion、-té、-ure、-ette、-ance/-ence、-ie',
       fr:'la station, la baguette, la boulangerie', zh:'車站、法棍、麵包店'},
      {r:'偏陽性字尾：-age、-ment、-eau、-isme、-oir',
       fr:'le voyage, le bureau, le miroir', zh:'旅行、辦公室、鏡子'},
      {r:'-e 結尾「傾向」陰性但例外極多，只能當弱線索，別當規則',
       fr:'le musée, le lycée', zh:'博物館、高中（-ée 卻是陽性）'},
    ],
    exc:['-age 例外：la page、la plage、l\'image（陰）','l\'eau（陰）——最常用的例外'] },
  { n:'1-1-3', lvl:'A1', name:'人與職業的陰陽形', fr:'noms de personnes',
    brief:'指人的名詞跟著人的性別變形',
    ex:[{fr:'Il est étudiant. Elle est étudiante.', zh:'他是學生。她是學生。（+e）'},
        {fr:'un acteur et une actrice', zh:'男演員和女演員（-teur→-trice）'}],
    pts:[
      {r:'基本 +e；-eur→-euse；-teur→-trice；-ien→-ienne',
       fr:'un vendeur / une vendeuse, un musicien / une musicienne', zh:'售貨員、音樂家的陰陽形'},
      {r:'部分職業歷史上只有陽性形，現代法語正在補陰性形',
       fr:'un professeur / une professeure', zh:'老師（新式陰性形已被接受）'},
    ] },
 ]},

 { n:'1-2', name:'名詞的複數', fr:'Le nombre', items:[
  { n:'1-2-1', lvl:'A1', name:'規則複數 +s', fr:'pluriel en -s',
    brief:'加 s 但不發音——複數靠冠詞聽出來',
    ex:[{fr:'le livre → les livres', zh:'一本書 → 一些書（唸起來只差 le→les）'},
        {fr:"J'ai deux chats.", zh:'我有兩隻貓。（chats 的 s 完全不發音）'}],
    pts:[
      {r:'書寫 +s，口語完全聽不到——耳朵靠冠詞 le→les、un→des 判斷複數',
       fr:'la table / les tables', zh:'桌子／桌子們（聽 la vs les）'},
      {r:'所以聽力時注意力放在冠詞上，不要等字尾',
       fr:'Il y a des chiens.', zh:'有一些狗。（des 就是複數訊號）'},
    ] },
  { n:'1-2-2', lvl:'A2', name:'-eau/-eu→+x、-al→-aux', fr:'pluriels en -x',
    brief:'兩個古法語拼寫家族',
    ex:[{fr:'un gâteau → des gâteaux', zh:'一個蛋糕 → 一些蛋糕（+x）'},
        {fr:'le journal → les journaux', zh:'報紙 → 報紙們（-al→-aux，發音也變）'}],
    pts:[
      {r:'-eau/-eu 結尾加 x（不是 s）',
       fr:'les cheveux, les bureaux', zh:'頭髮、辦公室們'},
      {r:'-al 變 -aux——這組連發音都變，聽得出複數',
       fr:'un animal / des animaux', zh:'一隻動物／一些動物'},
    ],
    exc:['-s/-x/-z 結尾不變：le fils→les fils','l\'œil→les yeux（完全換字）'] },
 ]},

 { n:'1-3', name:'冠詞', fr:'Les articles', topics:['articles'], items:[
  { n:'1-3-1', lvl:'A1', name:'定冠詞', fr:'le / la / l\' / les',
    brief:'特定的、雙方都知道的、或泛指整類',
    ex:[{fr:"J'aime la musique et le sport.", zh:'我喜歡音樂和運動。（泛指整類→定冠詞）'},
        {fr:'Ferme la porte !', zh:'關門！（你知我知的那扇門）'}],
    pts:[
      {r:'le 用於陽性單數、la 用於陰性單數、l\' 用於母音或啞音 h 開頭（不分陰陽）、les 用於全部複數（不分陰陽）',
       fr:"le café, la gare, l'école, l'hôtel, les amis", zh:'咖啡、車站、學校、旅館、朋友們'},
      {r:'發音注意：les 的 s 遇母音要連音唸 [z]',
       fr:'les amis [le-za-mi]', zh:'朋友們（les‿amis 連音）'},
    ],
    grid:{head:['', '陽性單數', '陰性單數', '母音/啞音h前', '複數'],
          rows:[['定冠詞', 'le livre', 'la table', "l'école / l'hôtel", 'les livres']]},
    usage:[
      {r:'特指：雙方都知道講的是哪一個', fr:'Ferme la porte.', zh:'關（那扇）門。'},
      {r:'泛指一整類（⚠️ 中文英文都不加，這是中文使用者最大的坑）', fr:"J'aime le café.", zh:'我喜歡（喝）咖啡——不是特定某杯'},
      {r:'喜好動詞後面固定用定冠詞：aimer / adorer / préférer / détester', fr:'Elle déteste les épinards.', zh:'她討厭菠菜。'},
      {r:'身體部位（法文不用所有格）', fr:"J'ai mal à la tête.", zh:'我頭痛。（不說 ma tête）'},
      {r:'星期＋le＝每週固定', fr:'Le lundi, je travaille.', zh:'每週一我上班。（不加le就是「這個星期一」）'},
    ],
    mnem:'把定冠詞想成「大家都認識的那位」——第二次提到、指著講、或講整個種類，都算大家認識。',
    more:[
      {fr:'Le soleil se lève.', zh:'太陽升起。（獨一無二的東西）'},
      {fr:'La France est belle.', zh:'法國很美。（國名要冠詞）'},
      {fr:'Où est la gare ?', zh:'車站在哪？（城裡就那座）'},
      {fr:"Les Français aiment le fromage.", zh:'法國人愛乳酪。（兩個泛指）'},
    ],
    see:['1-3-4','1-1-1'], gram:'articles' },
  { n:'1-3-2', lvl:'A1', name:'不定冠詞', fr:'un / une / des',
    brief:'第一次提到、隨便哪一個',
    ex:[{fr:'Il y a un chien et des chats.', zh:'有一隻狗和一些貓。'},
        {fr:"J'habite dans un appartement.", zh:'我住在一間公寓。（第一次提到）'}],
    pts:[
      {r:'un 用於陽性單數、une 用於陰性單數、des 用於全部複數——英文有 a/an，但沒有 des 這個「複數的a」，所以中文使用者常漏掉 des',
       fr:'un livre, une table, des livres', zh:'一本書、一張桌、一些書'},
      {r:'un/une 同時就是數字「一」——「一個」跟「某個」法文不區分',
       fr:"J'ai une sœur.", zh:'我有一個姊妹。'},
    ],
    grid:{head:['', '陽性單數', '陰性單數', '複數'],
          rows:[['不定冠詞', 'un chien', 'une amie', 'des chats']]},
    usage:[
      {r:'第一次提到、對方還不知道是哪一個', fr:"J'ai vu un film hier.", zh:'我昨天看了一部電影。'},
      {r:'數量「一個」', fr:'Je voudrais une baguette.', zh:'我要一條法棍。'},
      {r:'第二次再提到同一個東西就換定冠詞', fr:'Un chien arrive. Le chien est noir.', zh:'一隻狗走來。那隻狗是黑的。（un→le 的接力）'},
    ],
    more:[
      {fr:'Elle a des enfants ?', zh:'她有小孩嗎？'},
      {fr:'Il y a un problème.', zh:'有一個問題。'},
      {fr:"C'est une bonne idée !", zh:'這是個好主意！'},
    ],
    see:['1-3-5','7-2-3'] },
  { n:'1-3-3', lvl:'A2', name:'部分冠詞', fr:'du / de la / de l\'',
    brief:'不可數的「一些」——吃喝的預設冠詞',
    ex:[{fr:"Je bois de l'eau et du café.", zh:'我喝水和咖啡。（喝的是「一些」不是全部）'},
        {fr:'Elle mange de la viande.', zh:'她吃肉。（陰性→de la）'}],
    pts:[
      {r:'du 用於陽性（de+le的縮合形）、de la 用於陰性、de l\' 用於母音前——結構就是「de＋定冠詞」＝「那東西的一部分」',
       fr:'du pain, de la soupe, de l\'eau', zh:'一些麵包、一些湯、一些水'},
      {r:'複數的「一些」直接用 des（跟不定冠詞複數同形）',
       fr:'des pâtes, des légumes', zh:'一些麵、一些蔬菜'},
    ],
    grid:{head:['', '陽性', '陰性', '母音前', '複數'],
          rows:[['部分冠詞', 'du pain', 'de la viande', "de l'eau", 'des pâtes']]},
    usage:[
      {r:'吃、喝——永遠談的是一部分不是整類', fr:'On mange du poisson ce soir.', zh:'今晚吃魚。'},
      {r:'抽象名詞的「有一些」', fr:'Il a du courage et de la patience.', zh:'他有勇氣和耐心。'},
      {r:'做運動、玩樂器', fr:'Je fais du sport. Elle joue du piano.', zh:'我做運動。她彈鋼琴。'},
      {r:'天氣現象', fr:'Il y a du vent et du soleil.', zh:'有風有太陽。'},
    ],
    mnem:'吃喝玩樂有天氣，開口先想部分冠詞。整類才用 le/la（J\'aime le café vs Je bois du café）。',
    exc:['喜好動詞（aimer/préférer…）後面永遠用定冠詞不用部分冠詞：J\'aime le café（❌ J\'aime du café）'],
    vs:[{n:'1-3-4', note:'同一個 du，兩個身分：Je bois du café（部分冠詞「一些」）vs Je parle du café（de+le縮合「談論那家咖啡店」）——看動詞要不要接 de',
         grid:{head:['句子','du 的身分','意思'],
               rows:[['Je bois du café.','部分冠詞','我喝（一些）咖啡'],
                     ['Je parle du café.','de+le 縮合','我在講那家咖啡店（parler de）']]}},
        {n:'1-3-5', note:'否定之後 du/de la 全部塌縮成 de'}],
    more:[
      {fr:'Tu veux de la glace ?', zh:'你要冰淇淋嗎？'},
      {fr:'Il faut acheter du lait.', zh:'得買牛奶。'},
      {fr:"Elle écoute de la musique.", zh:'她在聽音樂。'},
    ],
    see:['9-2-1'] },
  { n:'1-3-4', lvl:'A1', name:'縮合冠詞', fr:'du / au / des / aux',
    brief:'de+le、à+le 黏成一個音的化石',
    ex:[{fr:'Je vais au marché.', zh:'我去市場。（à+le→au）'},
        {fr:'Il parle du prof.', zh:'他在講老師（的事）。（de+le→du）'}],
    pts:[
      {r:'只有 le 和 les 會被吃掉：de+le→du、de+les→des、à+le→au、à+les→aux。這不是選擇，是強制——寫 de le 直接算錯',
       fr:'au cinéma, aux États-Unis', zh:'去電影院、在美國'},
      {r:'la 和 l\' 完全不縮合，照原樣寫',
       fr:"à la gare, de l'école", zh:'在車站、從學校'},
    ],
    grid:{head:['', '+le', '+la', "+l'", '+les'],
          rows:[['de', 'du', 'de la', "de l'", 'des'],
                ['à',  'au', 'à la',  "à l'",  'aux']]},
    usage:[
      {r:'去哪裡／在哪裡（à+場所）', fr:'On va au restaurant.', zh:'我們去餐廳。'},
      {r:'從哪來／誰的／談論什麼（de+名詞）', fr:'Il revient du bureau.', zh:'他從辦公室回來。'},
      {r:'固定搭配裡也照縮：jouer au foot、faire du vélo', fr:'Ils jouent aux cartes.', zh:'他們玩牌。（à+les→aux）'},
    ],
    mnem:'口訣「了樂必縮」：遇到 le/les 必縮合；la 和 l\' 是釘子戶，拆不動。',
    more:[
      {fr:'Le bus arrive au centre-ville.', zh:'公車到市中心。'},
      {fr:"C'est le vélo du voisin.", zh:'這是鄰居的腳踏車。'},
      {fr:'Je pense aux vacances.', zh:'我在想假期的事。'},
    ],
    see:['8-1-2','1-3-3'] },
  { n:'1-3-5', lvl:'A2', name:'變 de 的場合', fr:'la règle du « de »',
    brief:'否定與量詞之後，冠詞塌縮成 de',
    ex:[{fr:'Je ne mange pas de viande.', zh:'我不吃肉。（否定後 de la→de）'},
        {fr:'Il mange beaucoup de pâtes.', zh:'他吃很多麵。（量詞後→de）'}],
    pts:[
      {r:'觸發點一：否定之後。un/une/du/de la/des 全部變 de——數量歸零，冠詞也歸零',
       fr:"J'ai un chien. → Je n'ai pas de chien.", zh:'我有狗 → 我沒有狗'},
      {r:'觸發點二：量詞之後。beaucoup de、un peu de、trop de、assez de、un kilo de——量詞已經標了量，冠詞退場',
       fr:'beaucoup de travail, trop de sel', zh:'很多工作、太多鹽'},
      {r:'觸發點三：形容詞放到複數名詞前面時，des 變 de',
       fr:'des objets → de beaux objets', zh:'一些物品 → 一些漂亮的物品'},
      {r:'母音前縮寫成 d\'',
       fr:"pas d'amis, beaucoup d'eau", zh:'沒有朋友、很多水'},
    ],
    usage:[
      {r:'這條是「改寫規則」不是新冠詞——先寫出原句，再看有沒有踩到三個觸發點', fr:'Il y a du vent. → Il n\'y a pas de vent.', zh:'有風 → 沒有風'},
    ],
    exc:['être 的否定不變：Ce n\'est pas du café（「這不是咖啡」是身分判斷，不是數量歸零）',
         '定冠詞 le/la/les 永遠不變：Je n\'aime pas le café（喜好談整類，跟數量無關）'],
    vs:[{n:'7-2-3', note:'否定句冠詞規則的完整版在否定章'}],
    more:[
      {fr:'Elle ne boit jamais de vin.', zh:'她從不喝酒。（jamais 也觸發）'},
      {fr:"Il n'y a plus de place.", zh:'沒位子了。（plus 也觸發）'},
      {fr:'Une douzaine d\'œufs, s\'il vous plaît.', zh:'請給我一打蛋。'},
    ],
    see:['1-6-1'] },
  { n:'1-3-6', lvl:'A2', name:'不加冠詞的場合', fr:'l\'absence d\'article',
    brief:'少數位置冠詞消失',
    ex:[{fr:'Elle est médecin.', zh:'她是醫生。（職業當屬性→裸用）'},
        {fr:'Je viens de Taïwan.', zh:'我來自台灣。（國名搭 de 不加冠詞）'}],
    pts:[
      {r:'職業、身分放在 être 後面當屬性時裸用；但 c\'est 開頭就要冠詞',
       fr:"Il est professeur. / C'est un professeur.", zh:'他是老師。／這是一位老師。'},
      {r:'城市名本身不帶冠詞；月份、星期單獨用也裸',
       fr:'à Taipei, en janvier, lundi', zh:'在台北、在一月、星期一'},
    ],
    usage:[
      {r:'自我介紹職業國籍', fr:'Je suis taïwanais et je suis dentiste.', zh:'我是台灣人，我是牙醫。'},
      {r:'venir de + 陰性國家或城市（la 被拿掉）', fr:'Elle vient de France.', zh:'她來自法國。（不說 de la France）'},
      {r:'清單、招牌、標題常整批裸用', fr:'Entrée, plat, dessert : 15 euros.', zh:'前菜、主菜、甜點：15歐。'},
    ],
    exc:['職業加了形容詞就要冠詞：C\'est un bon professeur / Il est un excellent médecin（後者較書面）',
         '陽性國家 venir 要縮合：Il vient du Canada（不是裸 de）'],
    vs:[{n:'7-3-1', note:'c\'est + 冠詞 vs il est + 裸職業，同一條分界'}],
    more:[
      {fr:'Elle est étudiante en droit.', zh:'她是法律系學生。'},
      {fr:'Nous sommes mardi.', zh:'今天星期二。'},
    ],
    see:['8-1-1'] },
 ]},

 { n:'1-4', name:'指示詞', fr:'Les démonstratifs', items:[
  { n:'1-4-1', lvl:'A1', name:'指示形容詞', fr:'ce / cet / cette / ces',
    brief:'「這個/那個」，法文不分遠近',
    ex:[{fr:'Cette valise est lourde.', zh:'這個行李箱很重。（陰性→cette）'},
        {fr:'Cet hôtel est cher.', zh:'這間旅館很貴。（陽性+母音→cet）'}],
    pts:[
      {r:'四張臉：ce（陽）cet（陽+母音）cette（陰）ces（複數）',
       fr:'ce livre, ces téléphones', zh:'這本書、這些手機'},
      {r:'cet＝母音相撞禁忌的墊音形（跟 mon amie 同一條規則）',
       fr:'cet ordinateur, cet ami', zh:'這台電腦、這位朋友'},
      {r:'法文預設不分遠近；要強調才加 -ci/-là',
       fr:'ce livre-ci / ce livre-là', zh:'這本／那本'},
    ],
    topics:['demonstrative-adj'], gram:'determinants' },
  { n:'1-4-2', lvl:'B1', name:'指示代名詞', fr:'celui / celle / ceux / celles',
    brief:'「那個～的」——把名詞收掉再指一次',
    ex:[{fr:'Quel livre ? Celui de Paul.', zh:'哪本書？保羅的那本。'},
        {fr:'Je préfère celle qui est bleue.', zh:'我比較喜歡藍色的那個（陰性）。'}],
    pts:[
      {r:'celui（陽）celle（陰）ceux（陽複）celles（陰複），跟被代替的名詞配合',
       fr:'ceux de la classe', zh:'班上的那些人'},
      {r:'不能單獨站，後面必接 de、-ci/-là 或關係子句',
       fr:'celui-là, celle que je veux', zh:'那一個、我要的那個'},
    ] },
 ]},

 { n:'1-5', name:'所有格', fr:'Les possessifs', items:[
  { n:'1-5-1', lvl:'A1', name:'所有格形容詞', fr:'mon / ma / mes …',
    brief:'跟「被擁有的名詞」配合，不跟主人',
    ex:[{fr:'Sa femme est fleuriste.', zh:'他的太太是花店老闆。（看femme陰性→sa，不看主人）'},
        {fr:'Nos enfants sont grands.', zh:'我們的孩子們長大了。（複數→nos）'}],
    pts:[
      {r:'全表：mon/ma/mes、ton/ta/tes、son/sa/ses、notre/nos、votre/vos、leur/leurs',
       fr:'ma mère, tes amis, leurs filles', zh:'我媽、你的朋友們、他們的女兒們'},
      {r:'⚠️ 中文使用者最大坑：son/sa 看名詞性別不看主人——「她的爸爸」也是 son père',
       fr:'Marie aime son père.', zh:'瑪麗愛她爸爸。（père陽性→son）'},
    ],
    topics:['family-possessives'], gram:'determinants' },
  { n:'1-5-2', lvl:'A1', name:'母音前借陽性形', fr:'mon amie',
    brief:'ma amie 母音相撞，借 mon 來墊',
    ex:[{fr:"C'est mon amie Sophia.", zh:'這是我朋友（女）蘇菲亞。'},
        {fr:'Son école est loin.', zh:'他/她的學校很遠。（école陰性但母音開頭→son）'}],
    pts:[
      {r:'陰性名詞母音開頭 → ma/ta/sa 借用 mon/ton/son',
       fr:'ton amie, son histoire', zh:'你的朋友（女）、他的故事'},
      {r:'純發音規則，名詞還是陰性——後面形容詞照配陰性',
       fr:'Mon amie est belle.', zh:'我朋友（女）很漂亮。（belle陰性）'},
    ],
    topics:['possessives'], gram:'determinants',
    vs:[{n:'2-2-4', note:'bel/nouvel/vieil 同一條母音禁忌'}] },
  { n:'1-5-3', lvl:'B1', name:'所有格代名詞', fr:'le mien / la tienne …',
    brief:'「我的那個」——名詞收掉的所有格',
    ex:[{fr:"Ce livre ? C'est le mien.", zh:'這本書？是我的。'},
        {fr:'Ta voiture est plus grande que la mienne.', zh:'你的車比我的大。'}],
    pts:[
      {r:'le mien/la mienne、le tien、le sien、le nôtre、le vôtre、le leur',
       fr:"C'est la sienne.", zh:'是他/她的（那個陰性東西）。'},
      {r:'冠詞+性數都配合被代替的名詞',
       fr:'mes clés → les miennes', zh:'我的鑰匙們 → 我的（陰複）'},
    ] },
 ]},

 { n:'1-6', name:'數與量', fr:'Les nombres et quantités', items:[
  { n:'1-6-1', lvl:'A2', name:'量詞', fr:'expressions de quantité',
    brief:'量詞後面一律 de + 裸名詞',
    ex:[{fr:'Je mange beaucoup de pâtes.', zh:'我吃很多麵。'},
        {fr:'un kilo de tomates, une bouteille de vin', zh:'一公斤番茄、一瓶酒'}],
    pts:[
      {r:'程度量詞：beaucoup de、un peu de、assez de、trop de',
       fr:'trop de sel', zh:'太多鹽'},
      {r:'單位量詞：un kilo de、une bouteille de、une douzaine de——中間永遠是裸 de',
       fr:"une douzaine d'œufs", zh:'一打蛋'},
    ],
    vs:[{n:'1-3-5', note:'就是「變de」規則的量詞分支'}] },
  { n:'1-6-2', lvl:'A1', name:'數字系統', fr:'les nombres',
    brief:'70/80/90 是古代二十進位的化石',
    ex:[{fr:'quatre-vingt-quinze', zh:'95 ＝ 4×20＋15'},
        {fr:'soixante-dix-huit', zh:'78 ＝ 60＋18'}],
    pts:[
      {r:'70=60+10、80=4×20、90=4×20+10——二十進位的殘骸；比利時瑞士直接說 septante/nonante',
       fr:'soixante-dix, quatre-vingts, quatre-vingt-dix', zh:'70、80、90'},
      {r:'21/31/41…加 et：vingt et un',
       fr:'trente et un', zh:'31'},
    ],
    exc:['quatre-vingts 有 s，但 quatre-vingt-un 後面接數字就沒 s'] },
  { n:'1-6-3', lvl:'A2', name:'序數', fr:'les ordinaux',
    brief:'字尾 -ième，只有「第一」特殊',
    ex:[{fr:'le premier étage', zh:'二樓（法國的一樓是台灣的二樓！）'},
        {fr:'la deuxième rue à gauche', zh:'左邊第二條街'}],
    pts:[
      {r:'數字+ième：deuxième、troisième；只有 premier/première 完全不規則',
       fr:'le troisième jour', zh:'第三天'},
      {r:'日期只有1號用序數，其他用基數',
       fr:'le premier mai / le 4 juin', zh:'5月1日／6月4日'},
    ] },
 ]},
]},

// ═══ 第 2 章 形容詞 ═════════════════════════════════════════
{ n:'2', name:'形容詞', fr:'L\'adjectif', sections:[

 { n:'2-1', name:'性數配合', fr:'L\'accord', topics:['adjective-agreement'], items:[
  { n:'2-1-1', lvl:'A1', name:'基本配合 +e / +s', fr:'accord de base',
    brief:'衛星穿主星的制服：陰+e、複+s',
    ex:[{fr:'Il a une voiture noire.', zh:'他有一輛黑色的車。（noire陰性+e）'},
        {fr:'Ce sont des livres intéressants.', zh:'這些是有趣的書。（複數+s）'}],
    pts:[
      {r:'形容詞跟被修飾的名詞做性數配合：陽性單數不變、陰性單數+e、陽性複數+s、陰性複數+es',
       fr:'grand → grande → grands → grandes', zh:'高大：陽單／陰單／陽複／陰複四種寫法'},
      {r:'陽性形已經以啞音 e 結尾時，陰性不再多加一個 e',
       fr:'un homme jeune, une femme jeune', zh:'年輕的男人、年輕的女人（jeune 不變）'},
      {r:'+e 常讓原本不發音的尾子音重新發聲，配合有時是「聽得到」的，不只是拼字問題',
       fr:'un sac lourd, une valise lourde', zh:'重的包（d不發音）、重的行李箱（d發音）'},
    ],
    grid:{head:['','陽性單數','陰性單數','陽性複數','陰性複數'],
          rows:[['grand（高大）','grand','grande','grands','grandes'],
                ['jeune（年輕，已-e不再加）','jeune','jeune','jeunes','jeunes']]},
    usage:[
      {r:'描述人或物的外觀、性質，先確定名詞性數再配合形容詞', fr:'Elle porte une robe bleue.', zh:'她穿一件藍色洋裝。'},
      {r:'一個名詞前後掛多個形容詞，每個都各自配合同一個名詞', fr:'un petit chien noir', zh:'一隻黑色小狗（petit、noir 都配 chien）'},
      {r:'être 後面的表語形容詞配合主詞，不是配合離它最近的字', fr:'Ils sont fatigués.', zh:'他們累了。（fatigués 配 ils）'},
    ],
    exc:['已經以啞音 -e 結尾的陽性形容詞不再加 e：範圍包含 jeune、rouge、facile、rapide 等一整批常見形容詞'],
    more:[
      {fr:'Ils ne sont pas contents.', zh:'他們不高興。'},
      {fr:'Est-ce que ces valises sont lourdes ?', zh:'這些行李箱重嗎？'},
      {fr:'Ma sœur est plus grande que moi.', zh:'我姊姊比我高。'},
      {fr:"C'est une histoire vraie.", zh:'這是真實的故事。'},
    ],
    see:['2-1-2','2-2-1'], gram:'adjectifs-accord' },
  { n:'2-1-2', lvl:'A2', name:'變形家族', fr:'terminaisons spéciales',
    brief:'六大字尾家族各有變法',
    ex:[{fr:'Elle est courageuse et sportive.', zh:'她勇敢又愛運動。'},
        {fr:'Ce plat est délicieux mais un peu cher.', zh:'這道菜很好吃但有點貴。'}],
    pts:[
      {r:'-eux → -euse：courageux/courageuse、heureux/heureuse',
       fr:'un homme heureux, une femme heureuse', zh:'幸福的男人、幸福的女人'},
      {r:'-if → -ive：sportif/sportive、actif/active',
       fr:'un enfant actif, une équipe active', zh:'活潑的孩子、活躍的隊伍'},
      {r:'-er → -ère：cher/chère、premier/première',
       fr:'un livre cher, une place chère', zh:'貴的書、貴的位子'},
      {r:'-on/-en → -onne/-enne：bon/bonne、coréen/coréenne',
       fr:'un bon repas, une bonne idée', zh:'一頓好餐、一個好主意'},
      {r:'-c → -che 或 -que：blanc/blanche、public/publique',
       fr:'un mur blanc, une robe blanche', zh:'白牆、白洋裝'},
      {r:'完全不規則、要單獨背：beau/belle、nouveau/nouvelle、vieux/vieille、long/longue、fou/folle',
       fr:'un vieux quartier, une vieille ville', zh:'老城區、老城市'},
    ],
    grid:{head:['陽性','陰性','例字'],
          rows:[['-eux','-euse','heureux/heureuse'],
                ['-if','-ive','sportif/sportive'],
                ['-er','-ère','cher/chère'],
                ['-on/-en','-onne/-enne','bon/bonne'],
                ['-c','-che/-que','blanc/blanche'],
                ['不規則','—','beau/belle, vieux/vieille']]},
    usage:[
      {r:'描述個性、狀態時先確認字尾家族再變陰性', fr:'Elle est très active.', zh:'她非常活躍。'},
      {r:'國籍形容詞常屬 -en/-on 家族', fr:'une amie coréenne', zh:'一位韓國朋友（陰性）'},
    ],
    exc:['少數形容詞看起來像某家族但其實不規則：doux/douce、frais/fraîche——遇到不熟的字查字典比套規則保險'],
    more:[
      {fr:"C'est une histoire longue et compliquée.", zh:'這是一段又長又複雜的故事。'},
      {fr:'Il est fou de musique.', zh:'他為音樂瘋狂。'},
      {fr:'Nous cherchons un appartement neuf.', zh:'我們在找一間新公寓。'},
      {fr:'Cette rue est publique.', zh:'這條街是公共的。'},
    ],
    see:['2-1-1','2-1-3'] },
  { n:'2-1-3', lvl:'A2', name:'不變的形容詞', fr:'adjectifs invariables',
    brief:'借來的顏色字不配合',
    ex:[{fr:'des chaussures marron', zh:'棕色的鞋（marron不加s）'},
        {fr:'une veste orange', zh:'橘色外套（orange本是名詞，不變陰性）'}],
    pts:[
      {r:'orange、marron 本身是名詞（橘子／栗子），借來當顏色形容詞用時不隨名詞變化性數',
       fr:'des yeux marron, des jupes orange', zh:'棕色眼睛、橘色裙子（都不加s）'},
      {r:'兩個字組成的複合顏色也整組不變：bleu clair、vert foncé、bleu marine',
       fr:'des yeux bleu clair', zh:'淺藍色的眼睛（bleu和clair都不加s）'},
    ],
    usage:[
      {r:'描述衣物、眼睛、頭髮的顏色時，先判斷這個顏色字是不是借用名詞', fr:'Elle porte un pull marron.', zh:'她穿一件棕色毛衣。'},
      {r:'買東西、形容商品顏色的口語場合很常用到', fr:'Vous avez ce sac en orange ?', zh:'這款包包有橘色的嗎？'},
    ],
    exc:['範圍限於「名詞借來當顏色」這一批：orange、marron、cerise、turquoise 等；純粹的顏色形容詞（rouge、bleu、vert、noir 單獨用）仍正常配合陰陽複數'],
    more:[
      {fr:'Il a les cheveux marron.', zh:'他頭髮是棕色的。'},
      {fr:'Ces murs sont bleu ciel.', zh:'這些牆是天藍色的。'},
      {fr:"J'aime les tomates orange et rouges.", zh:'我喜歡橘色和紅色的番茄。（rouges單字顏色照常配合，orange不變）'},
    ],
    see:['2-1-1'] },
 ]},

 { n:'2-2', name:'位置', fr:'La place', topics:['adjective-position'], items:[
  { n:'2-2-1', lvl:'A1', name:'預設放名詞後', fr:'adjectif postposé',
    brief:'客觀分類的形容詞在後面',
    ex:[{fr:'une ville française', zh:'一座法國城市'},
        {fr:'Il conduit une voiture rouge.', zh:'他開一輛紅色的車。'}],
    pts:[
      {r:'顏色、國籍、形狀、宗教、材質等「客觀分類」形容詞，法文預設放在名詞後面——這是大多數形容詞的預設位置',
       fr:'une voiture rouge, un film français, une table ronde', zh:'紅色的車、法國電影、圓桌'},
      {r:'分詞當形容詞用時也後置：une porte fermée、un enfant fatigué',
       fr:'un magasin ouvert', zh:'一家開著的店'},
    ],
    usage:[
      {r:'描述國籍、地區來源', fr:'un fromage italien', zh:'義大利乳酪'},
      {r:'描述形狀、材質等客觀屬性', fr:'une table en bois', zh:'木頭桌子'},
      {r:'寫作／口說預設先用這條，除非要用到 2-2-2 的高頻評價字才考慮前置', fr:"C'est une région montagneuse.", zh:'這是一個多山的地區。'},
    ],
    more:[
      {fr:'Elle porte une jupe noire.', zh:'她穿一條黑裙子。'},
      {fr:'Nous avons visité un château médiéval.', zh:'我們參觀了一座中世紀城堡。'},
      {fr:"C'est un restaurant japonais.", zh:'這是一家日本餐廳。'},
    ],
    see:['2-2-2','2-1-1'], gram:'adjectifs-accord' },
  { n:'2-2-2', lvl:'A2', name:'BAGS 前置組', fr:'adjectifs antéposés',
    brief:'美醜好壞大小新舊老少——高頻評價字搶前位',
    ex:[{fr:'un beau garçon, une petite maison', zh:'帥男孩、小房子'},
        {fr:'Elle a acheté de beaux objets.', zh:'她買了一些漂亮的東西。（前置+複數→de）'}],
    pts:[
      {r:'BAGS：Beauté美醜、Âge新舊老少、Goodness好壞、Size大小——這一小批高頻評價形容詞放在名詞前面',
       fr:'beau, joli, bon, mauvais, grand, petit, nouveau, vieux, jeune', zh:'美、漂亮、好、壞、大、小、新、老、年輕'},
      {r:'前置形容詞＋複數名詞時，不定冠詞/部分冠詞的 des 要變成 de（見 1-3-5）',
       fr:'des objets → de beaux objets', zh:'一些物品 → 一些漂亮的物品'},
    ],
    grid:{head:['類別','常見字'],
          rows:[['Beauté 美醜','beau/belle, joli(e)'],
                ['Âge 新舊老少','nouveau/nouvelle, vieux/vieille, jeune'],
                ['Goodness 好壞','bon(ne), mauvais(e)'],
                ['Size 大小','grand(e), petit(e), gros(se)']]},
    usage:[
      {r:'口語形容人事物的第一印象、主觀評價', fr:"C'est une bonne idée.", zh:'這是個好主意。'},
      {r:'BAGS字前置時常跟後置的客觀形容詞疊用：BAGS在前、其他在後', fr:'un beau film français', zh:'一部漂亮的法國電影（beau前、français後）'},
    ],
    exc:['BAGS字特別加強調重音或對比語氣時偶爾也能後置改變語感，但這是進階書面用法，A2階段先照BAGS前置的預設走'],
    more:[
      {fr:"C'est un vieux quartier.", zh:'這是一個老城區。'},
      {fr:'Nous avons une grande cuisine.', zh:'我們有一個大廚房。'},
      {fr:"Il porte un mauvais pull aujourd'hui.", zh:'他今天穿了一件難看的毛衣。'},
      {fr:'Ce sont de jeunes étudiants.', zh:'這些是年輕學生。（de不是des）'},
    ],
    see:['2-2-1','1-3-5'] },
  { n:'2-2-3', lvl:'B1', name:'前後變義', fr:'place et sens',
    brief:'同一個字，位置一換意思就換',
    ex:[{fr:'un grand homme ≠ un homme grand', zh:'偉人 ≠ 高個子'},
        {fr:'mon ancien prof ≠ une maison ancienne', zh:'我的前任老師 ≠ 一棟古老的房子'}],
    pts:[
      {r:'grand 前置＝抽象的「偉大」，後置＝身高的「高」',
       fr:'un grand homme / un homme grand', zh:'偉人／身材高的男人'},
      {r:'ancien 前置＝「前任、以前的」，後置＝「古老、年代久遠」',
       fr:'mon ancien prof / une maison ancienne', zh:'我的前任老師／一棟古老的房子'},
      {r:'propre 前置＝「自己的」（所有格式），後置＝「乾淨的」',
       fr:'ma propre chambre / une chambre propre', zh:'我自己的房間／一間乾淨的房間'},
    ],
    grid:{head:['形容詞','前置意思','後置意思'],
          rows:[['grand','偉大的（抽象）','高的（身高）'],
                ['ancien','前任的、以前的','古老的'],
                ['propre','自己的','乾淨的'],
                ['pauvre','可憐的','貧窮的（同類邏輯，補充字）'],
                ['cher','親愛的','昂貴的（同類邏輯，補充字）']]},
    usage:[
      {r:'書面／閱讀測驗常故意用這批字考位置決定的意思', fr:'Napoléon était un grand homme.', zh:'拿破崙是位偉人。（不是說他很高）'},
      {r:'口語稱呼用前置 cher，形容價格用後置 cher', fr:'Cher ami, ce livre est cher.', zh:'親愛的朋友，這本書很貴。（同一個字兩種位置兩種意思）'},
    ],
    more:[
      {fr:'Ma propre voiture est en panne, alors je conduis une voiture propre mais empruntée.', zh:'我自己的車壞了，所以我開一輛乾淨但借來的車。'},
      {fr:"C'est un pauvre étudiant.", zh:'這是個可憐的學生。（前置＝可憐）'},
      {fr:'Cet homme est pauvre.', zh:'這個人很窮。（後置＝貧窮）'},
    ],
    see:['2-2-2','2-2-1'] },
  { n:'2-2-4', lvl:'A2', name:'母音前特殊形', fr:'bel / nouvel / vieil',
    brief:'beau/nouveau/vieux 遇母音的墊音形',
    ex:[{fr:'un bel appartement', zh:'一間漂亮的公寓'},
        {fr:'Un vieil ami me téléphone.', zh:'一位老朋友打電話給我。'}],
    pts:[
      {r:'beau、nouveau、vieux 三個 BAGS 前置字，遇到「陽性單數＋母音或啞音h開頭」的名詞時，改用墊音形 bel、nouvel、vieil',
       fr:'un bel homme, un nouvel ordinateur, un vieil ami', zh:'一位帥男人、一台新電腦、一位老朋友'},
      {r:'這只是發音上避免母音相撞的墊音形，陰性、複數不受影響，發音其實跟陰性形一樣',
       fr:'une belle femme, de beaux hommes', zh:'漂亮的女人（陰性正常）、一些帥男人（複數正常）'},
    ],
    grid:{head:['基本陽性','陰性','母音前墊音形'],
          rows:[['beau','belle','bel'],
                ['nouveau','nouvelle','nouvel'],
                ['vieux','vieille','vieil']]},
    usage:[
      {r:'名詞是陽性單數且以母音或啞音h開頭時才用墊音形', fr:'un nouvel élève', zh:'一位新學生'},
      {r:'子音開頭的陽性單數名詞維持原本的 beau/nouveau/vieux', fr:'un beau jardin', zh:'一座漂亮的花園'},
    ],
    exc:['只在「陽性單數＋母音/啞音h」這個狹窄範圍出現，陰性（belle/nouvelle/vieille）跟複數（beaux/nouveaux/vieux…）都不受影響'],
    more:[
      {fr:'Ils habitent dans un vieil immeuble.', zh:'他們住在一棟老公寓大樓裡。'},
      {fr:'Voici mon nouvel appartement.', zh:'這是我的新公寓。'},
      {fr:'Quel bel oiseau !', zh:'多漂亮的鳥！'},
    ],
    see:['1-5-2','2-2-2'],
    vs:[{n:'1-5-2', note:'mon amie 同一條母音相撞禁忌'}] },
 ]},

 { n:'2-3', name:'比較與最高級', fr:'La comparaison', topics:['comparaison'], items:[
  { n:'2-3-1', lvl:'A2', name:'比較級三式', fr:'plus / aussi / moins … que',
    brief:'三個副詞當萬用零件',
    ex:[{fr:'Elle est plus grande que moi.', zh:'她比我高。'},
        {fr:"Ce train est aussi rapide que l'avion.", zh:'這班火車跟飛機一樣快。'}],
    pts:[
      {r:'plus…que＝更（多）、aussi…que＝一樣、moins…que＝較不——三個副詞夾住形容詞或副詞，que後面接比較對象',
       fr:'plus cher que, aussi cher que, moins cher que', zh:'比較貴、一樣貴、比較不貴'},
      {r:'比較對象如果是人且用代名詞，要用重讀代名詞（見 3-2-1），不能用主詞代名詞',
       fr:'plus grande que moi, plus jeune que lui', zh:'比我高、比他年輕（不是 que je、que il）'},
    ],
    grid:{head:['結構','意思','例句'],
          rows:[['plus + adj + que','更…','plus grand que'],
                ['aussi + adj + que','一樣…','aussi grand que'],
                ['moins + adj + que','較不…','moins grand que']]},
    usage:[
      {r:'比較兩個人或物的屬性', fr:'Paris est plus grand que Lyon.', zh:'巴黎比里昂大。'},
      {r:'比較動作的方式，用副詞代替形容詞，位置一樣', fr:'Il court plus vite que moi.', zh:'他跑得比我快。'},
      {r:'否定句一樣把 ne…pas 包住整個比較結構', fr:"Ce n'est pas plus cher que l'autre.", zh:'這不比另一個貴。'},
    ],
    exc:['bon 和 mauvais 走不規則比較級（見 2-3-2），不能說 plus bon'],
    more:[
      {fr:'Elle parle français aussi bien que sa mère.', zh:'她法文說得跟她媽媽一樣好。'},
      {fr:'Ce quartier est moins cher que le centre-ville.', zh:'這一區比市中心便宜。'},
      {fr:'Tu es plus patient que moi.', zh:'你比我有耐心。'},
    ],
    see:['2-3-2','2-3-3'], gram:'comparaison' },
  { n:'2-3-2', lvl:'A2', name:'meilleur 與 pire', fr:'comparatifs irréguliers',
    brief:'拉丁文比較級活化石，不走 plus',
    ex:[{fr:'Le thé est meilleur que le café.', zh:'茶比咖啡好。'},
        {fr:'Cette solution est pire que le problème.', zh:'這個解法比問題本身更糟。'}],
    pts:[
      {r:'bon 的比較級是 meilleur（陰性 meilleure、複數 meilleurs/meilleures），絕對不說 plus bon',
       fr:'un meilleur film, une meilleure idée', zh:'更好的電影、更好的主意'},
      {r:'mauvais 的比較級可以是 pire（書面/強調）或 plus mauvais（口語也接受），兩者都存在但 pire 更正式常見',
       fr:'C\'est pire que je pensais.', zh:'比我想的更糟。'},
      {r:'副詞版是另一條線：bien → mieux（不是 meilleur），meilleur 只配名詞不配動詞（見 9-5-2）',
       fr:"Il joue mieux qu'avant.", zh:'他打得比以前好。（mieux不是meilleur）'},
    ],
    grid:{head:['原級','比較級（配名詞/形容詞）','副詞版（配動詞）'],
          rows:[['bon（好）','meilleur','bien → mieux'],
                ['mauvais（壞）','pire / plus mauvais','mal → plus mal / pis（罕用）']]},
    usage:[
      {r:'評論食物、產品、選項哪個更好', fr:"Ce restaurant est meilleur que l'autre.", zh:'這家餐廳比另一家好。'},
      {r:'表達情況變得更糟', fr:'La situation devient pire.', zh:'情況變得更糟了。'},
    ],
    exc:['「更好地做某事」用 mieux 不用 meilleur——meilleur 是形容詞只能修飾名詞，這是A2到B1最常錯的一格（詳見 9-5-2）'],
    vs:[{n:'9-5-2', note:'meilleur 配名詞（形容詞）、mieux 配動詞（副詞）',
         grid:{head:['句子','用字','原因'],
               rows:[['Ce café est meilleur.','meilleur','café是名詞'],
                     ['Il chante mieux.','mieux','chante是動詞']]}}],
    more:[
      {fr:'Tu as fait de ton mieux, mais le résultat est pire que prévu.', zh:'你已經盡力了，但結果比預期更糟。'},
      {fr:'Cette année, les résultats sont meilleurs.', zh:'今年的成績更好。（複數meilleurs）'},
      {fr:"Rien n'est pire que l'attente.", zh:'沒有什麼比等待更糟。'},
    ],
    see:['2-3-1','9-5-2'] },
  { n:'2-3-3', lvl:'B1', name:'最高級', fr:'le superlatif',
    brief:'比較級前面加定冠詞',
    ex:[{fr:"C'est la plus belle plage de France.", zh:'這是法國最美的海灘。'},
        {fr:'Il est le plus jeune de la famille.', zh:'他是家裡最年輕的。'}],
    pts:[
      {r:'在 plus/moins + 形容詞前面加上定冠詞（le/la/les），冠詞跟名詞配合性數',
       fr:'le plus grand, la plus grande, les plus grands', zh:'最大的（陽單／陰單／複數）'},
      {r:'形容詞如果本來就後置，定冠詞要出現兩次：一次在名詞前、一次在形容詞前',
       fr:'la ville la plus grande de France', zh:'法國最大的城市（la…la 各配一次）'},
      {r:'形容詞本來就前置（BAGS）時，冠詞只出現一次，直接放最高級整組前面',
       fr:'le plus beau jour', zh:'最美好的一天'},
      {r:'比較的範圍用 de 引出，不是 dans',
       fr:'le meilleur élève de la classe', zh:'班上最好的學生'},
    ],
    grid:{head:['形容詞位置','結構','例句'],
          rows:[['後置（預設）','冠詞+名詞+冠詞+plus+adj','la ville la plus grande'],
                ['前置（BAGS）','冠詞+plus+adj+名詞','le plus beau jour']]},
    usage:[
      {r:'介紹景點、排名第一的事物', fr:"C'est le plus haut sommet d'Europe.", zh:'這是歐洲最高峰。'},
      {r:'不規則最高級沿用 meilleur/pire 的不規則形', fr:"C'est le meilleur restaurant du quartier.", zh:'這是這一區最好的餐廳。'},
    ],
    exc:['最高級的不規則形跟比較級一致：le meilleur（不是le plus bon）、le pire（不是le plus mauvais，但plus mauvais也可接受）'],
    more:[
      {fr:'Quelle est la ville la plus visitée du pays ?', zh:'這個國家最多人參觀的城市是哪一個？'},
      {fr:"C'est le moins cher de tous les hôtels.", zh:'這是所有旅館裡最便宜的。'},
      {fr:'Ce sont les meilleurs souvenirs de mon voyage.', zh:'這些是我旅行中最好的回憶。'},
    ],
    see:['2-3-1','2-3-2'] },
  { n:'2-3-4', lvl:'B1', name:'名詞與動詞的比較', fr:'plus de … que / verbe + plus que',
    brief:'比數量用 plus de，比動作用動詞+plus',
    ex:[{fr:"J'ai plus de livres que toi.", zh:'我書比你多。（數量）'},
        {fr:'Il travaille plus que moi.', zh:'他工作得比我多。（動作）'}],
    pts:[
      {r:'比較「數量多少」時用 plus de/moins de/autant de ＋ 名詞 ＋ que，中間的 de 是量詞de的邏輯（見 1-6-1）',
       fr:"J'ai plus de temps que lui.", zh:'我比他有更多時間。'},
      {r:'比較「動作程度」時，plus/moins/autant 直接放動詞後面，不加 de',
       fr:'Elle dort moins que moi.', zh:'她睡得比我少。'},
      {r:'autant de 是「一樣多」的名詞版，跟形容詞版 aussi 對應',
       fr:"Elle a autant de patience que lui.", zh:'她跟他一樣有耐心。'},
    ],
    grid:{head:['比較對象','結構','例句'],
          rows:[['數量（名詞）','plus/moins/autant de + 名詞 + que','plus de livres que'],
                ['動作（動詞）','動詞 + plus/moins/autant + que','travaille plus que']]},
    usage:[
      {r:'比較兩人擁有的東西數量', fr:"Il a moins d'argent que sa sœur.", zh:'他錢比他姊姊少。'},
      {r:'比較兩人做某件事的頻率或程度', fr:'Elle voyage plus que nous.', zh:'她比我們常旅行。'},
    ],
    exc:['名詞版一定要加 de：不能說 plus livres que，必須是 plus de livres que'],
    more:[
      {fr:'Tu manges plus de légumes que moi.', zh:'你吃的蔬菜比我多。'},
      {fr:"Ils sortent moins que l'année dernière.", zh:'他們比去年少出門。'},
      {fr:"J'ai autant de travail que toi cette semaine.", zh:'這星期我跟你工作量一樣多。'},
    ],
    see:['2-3-1','1-6-1'] },
 ]},
]},

// ═══ 第 3 章 代名詞 ═════════════════════════════════════════
{ n:'3', name:'代名詞', fr:'Les pronoms', sections:[

 { n:'3-1', name:'主詞代名詞', fr:'Pronoms sujets', items:[
  { n:'3-1-1', lvl:'A1', name:'六人稱與 tu/vous', fr:'je, tu, il …',
    brief:'主詞代名詞是黏在動詞上的輕音節',
    ex:[{fr:'Vous êtes professeur ?', zh:'您是老師嗎？（敬稱）'},
        {fr:'Ils habitent à Lyon depuis dix ans.', zh:'他們在里昂住十年了。'}],
    pts:[
      {r:'六個主詞代名詞：je（我）、tu（你，熟）、il/elle（他/她）、nous（我們）、vous（您/你們）、ils/elles（他們/她們）——動詞永遠要黏著其中一個變位',
       fr:'je parle, nous parlons', zh:'我說、我們說（動詞跟著代名詞換形）'},
      {r:'tu 用於熟人、同輩、小孩；vous 用於陌生人、長輩、正式場合，也是「你們」的唯一形式——選錯不是文法錯是社交地雷',
       fr:'Tu viens ? / Vous venez ?', zh:'你要來嗎？（熟）／您（你們）要來嗎？（敬稱或複數）'},
      {r:'ils 只要群體裡混了一位陽性成員就整體用 ils，即使99位是女性——語法上的陽性優先',
       fr:'Marie, Julie et Paul — ils arrivent.', zh:'瑪麗、茱莉和保羅——他們到了。（一個男生就用ils）'},
    ],
    grid:{head:['單數','複數'],
          rows:[['je（我）','nous（我們）'],
                ['tu（你，熟）','vous（您/你們）'],
                ['il（他）/elle（她）','ils（他們）/elles（她們）']]},
    usage:[
      {r:'第一次見面、對長輩或客戶，一律用 vous', fr:'Bonjour, vous allez bien ?', zh:'您好，您好嗎？'},
      {r:'朋友、同學、家人用 tu，對方主動提議才互相用tu', fr:'On se tutoie ?', zh:'我們可以互相用tu嗎？'},
      {r:'口語裡 on 常取代 nous（見 3-1-2）', fr:'On y va !', zh:'我們走吧！'},
    ],
    more:[
      {fr:"Je ne comprends pas.", zh:'我不懂。'},
      {fr:'Elle travaille à Paris.', zh:'她在巴黎工作。'},
      {fr:'Vous parlez très bien français.', zh:'您法語說得很好。'},
      {fr:'Elles sont toutes étudiantes.', zh:'她們都是學生。'},
    ],
    see:['3-1-2','3-2-1'] },
  { n:'3-1-2', lvl:'A1', name:'on', fr:'on = nous 口語版',
    brief:'「人」磨成的萬用主詞，動詞跟 il 同形',
    ex:[{fr:'On a un appartement.', zh:'我們有一間公寓。'},
        {fr:'En France, on mange souvent du pain avec le fromage.', zh:'在法國，人們常常麵包配乳酪一起吃。'}],
    pts:[
      {r:'口語裡 on 幾乎完全取代 nous 當「我們」，比 nous 自然得多',
       fr:'On va au cinéma ce soir.', zh:'我們今晚去看電影。'},
      {r:'也可以泛指「人們、大家」，不特指某群人',
       fr:'On dit que ce restaurant est excellent.', zh:'聽說（大家都說）這家餐廳很棒。'},
      {r:'不管指「我們」還是「大家」，動詞永遠用第三人稱單數變位——這是 on 最容易忘的地方',
       fr:'On mange bien ici.', zh:'這裡吃得不錯。（mange不是mangeons）'},
    ],
    grid:{head:['意思','例句'],
          rows:[['我們（口語）','On part demain.'],
                ['大家/人們（泛指）','On ne sait jamais.'],
                ['被動替代（見6-4-1）',"On m'a volé mon vélo."]]},
    usage:[
      {r:'跟朋友家人講「我們要做什麼」，口語一律用on不用nous', fr:'On se voit demain ?', zh:'明天見？'},
      {r:'講當地習慣、通則時用on當「人們」', fr:'Ici, on ferme à midi.', zh:'這裡中午關門。'},
    ],
    exc:['書面正式文件、演講稿仍用 nous，on 是口語與非正式書面的預設'],
    more:[
      {fr:'On est en retard !', zh:'我們遲到了！'},
      {fr:"Est-ce qu'on peut commencer ?", zh:'我們可以開始了嗎？'},
      {fr:'On ne sait jamais ce qui va se passer.', zh:'誰也不知道會發生什麼事。'},
    ],
    topics:['on-vs-nous'], gram:'pronouns', see:['3-1-1','6-4-1'],
    vs:[{n:'6-4-1', note:'on 也是法文迴避被動語態的主力'}] },
 ]},

 { n:'3-2', name:'重讀代名詞', fr:'Pronoms toniques', items:[
  { n:'3-2-1', lvl:'A2', name:'moi / toi / lui / eux', fr:'pronoms toniques',
    brief:'有重音的加強版，扛主詞代名詞站不住的場合',
    ex:[{fr:'Chez eux, on mange bien.', zh:'在他們家吃得好。'},{fr:'Et toi ?', zh:'那你呢？'}],
    pts:[
      {r:'重讀代名詞：moi、toi、lui、elle、nous、vous、eux、elles——跟主詞代名詞長得像但功能不同，帶重音可以獨立站',
       fr:'Moi, je pense que oui.', zh:'我啊，我覺得是。（moi加強je）'},
      {r:'四個使用場合：介詞後面、單獨強調、單獨回答問題、比較句的que後面',
       fr:'chez lui, plus grand que toi, Qui ? Moi.', zh:'在他家、比你高、誰？我。'},
      {r:'⚠️ il→lui、ils→eux 是最常錯的兩格，因為長得完全不像主詞代名詞',
       fr:'Je pense à eux.', zh:'我想著他們。（不是à ils）'},
    ],
    grid:{head:['主詞代名詞','重讀代名詞'],
          rows:[['je','moi'],['tu','toi'],['il','lui'],['elle','elle'],
                ['nous','nous'],['vous','vous'],['ils','eux'],['elles','elles']]},
    usage:[
      {r:'介詞（chez、avec、pour、sans…）後面一律用重讀形', fr:'Tu viens avec moi ?', zh:'你跟我一起來嗎？'},
      {r:'句首強調主詞時疊用：重讀代名詞＋逗號＋主詞代名詞', fr:'Lui, il ne dit jamais rien.', zh:'他呀，他從來什麼都不說。'},
      {r:'單獨回答問題，不需要完整句子', fr:'Qui a fait ça ? — Elle.', zh:'誰做的？——她。'},
    ],
    exc:['命令式肯定句掛在動詞後面時也用重讀形：Aide-moi !（見6-1-1），否定句才變回me/te'],
    more:[
      {fr:'Sans toi, je ne peux pas y arriver.', zh:'沒有你，我做不到。'},
      {fr:'Nous, on est fatigués.', zh:'我們啊，我們累了。'},
      {fr:'Eux, ils habitent à côté.', zh:'他們啊，他們住隔壁。'},
      {fr:"C'est pour vous.", zh:'這是給您的。'},
    ],
    topics:['pronoms-toniques'], gram:'pronouns', see:['3-1-1','3-3-1'] },
 ]},

 { n:'3-3', name:'受詞代名詞', fr:'Pronoms compléments', items:[
  { n:'3-3-1', lvl:'A2', name:'COD 直接受詞', fr:'me, te, le, la, nous, vous, les',
    brief:'不經介詞的受詞，放動詞前面',
    ex:[{fr:"Tu m'aides ?", zh:'你幫我嗎？'},{fr:'Il les aime.', zh:'他愛他們。'}],
    pts:[
      {r:'COD直接受詞代名詞：me/te/le/la/nous/vous/les——代替動詞「直接吃到」的對象，放在變位動詞前面',
       fr:'Je le connais.', zh:'我認識他。（le直接代替connais的對象）'},
      {r:'母音或啞音h前，me/te/le/la 要縮寫成 m\'/t\'/l\'',
       fr:"Tu m'aides ? Il l'aime.", zh:'你幫我嗎？他愛他/她。'},
      {r:'否定時 ne 和 pas 把「代名詞+動詞」整組包住',
       fr:"Je ne la connais pas.", zh:'我不認識她。'},
    ],
    grid:{head:['人稱','COD代名詞'],
          rows:[['me/te','我/你'],["le/la/l'",'他/她/它（陽/陰）'],
                ['nous/vous','我們/您'],['les','他們/她們/它們']]},
    usage:[
      {r:'先問自己「動詞後面直接接的是誰/什麼」，沒有介詞在中間才是COD', fr:'Je regarde la télé. → Je la regarde.', zh:'我看電視。→ 我看它。'},
      {r:'複合過去式裡COD放在助動詞前面，過去分詞還要跟它配合（見5-2-5）', fr:"Je l'ai vu hier.", zh:'我昨天看到他了。'},
    ],
    exc:['regarder、écouter、chercher、attendre 這幾個動詞中文會說「看『著』、聽『著』」，但法文直接及物、後面直接接COD不需要介詞'],
    more:[
      {fr:'Tu le prends ou pas ?', zh:'你要拿它還是不要？'},
      {fr:'Elle nous invite ce soir.', zh:'她今晚邀請我們。'},
      {fr:"Je ne t'entends pas bien.", zh:'我聽不太清楚你（說話）。'},
    ],
    topics:['cod-pronouns'], gram:'pronouns', see:['3-3-2','3-3-3'],
    vs:[{n:'3-3-2', note:'COD吃「誰/什麼」；COI吃「à+人」→lui/leur'}] },
  { n:'3-3-2', lvl:'B1', name:'COI 間接受詞', fr:'lui / leur',
    brief:'動詞經過 à 才碰到的人 → lui/leur',
    ex:[{fr:'Je lui donne le livre.', zh:'我把書給他/她。'},
        {fr:'Elle leur téléphone tous les dimanches.', zh:'她每個星期天打電話給他們。'}],
    pts:[
      {r:'COI間接受詞代名詞 lui（單數，不分男女）、leur（複數）——代替動詞經過介詞à才碰到的「人」',
       fr:'Je lui parle. Je leur écris.', zh:'我跟他/她說話。我寫信給他們。'},
      {r:'觸發詞是接à的動詞群：parler à、téléphoner à、donner à、écrire à、demander à…',
       fr:'Il téléphone à sa mère. → Il lui téléphone.', zh:'他打給他媽媽。→ 他打給她。'},
      {r:'me/te/nous/vous 一二人稱身兼COD跟COI兩職，只有第三人稱才分家成le/la（COD）vs lui（COI）',
       fr:'Tu me comprends. Tu me parles.', zh:'你懂我。你跟我說話。（同一個me兩種身分）'},
    ],
    grid:{head:['受詞類型','第三人稱單數','第三人稱複數'],
          rows:[['COD（直接吃到）','le/la','les'],['COI（經過à的人）','lui','leur']]},
    usage:[
      {r:'先確認動詞後面是不是要接à才碰到人，接的話才用lui/leur', fr:'Je réponds à mes parents. → Je leur réponds.', zh:'我回覆我父母。→ 我回覆他們。'},
      {r:'打電話、寫信、給東西這類「傳遞給某人」的動作幾乎都走這條', fr:'Elle lui envoie un message.', zh:'她傳訊息給他/她。'},
    ],
    exc:['aimer、regarder、écouter、attendre 不接à，受詞是COD不是COI：Je l\'aime（不是Je lui aime）'],
    more:[
      {fr:'Il ne leur répond jamais.', zh:'他從不回覆他們。'},
      {fr:"Est-ce que tu lui as expliqué la situation ?", zh:'你跟他/她解釋情況了嗎？'},
      {fr:'Je vais leur écrire ce soir.', zh:'我今晚要寫信給他們。'},
    ],
    see:['3-3-1','3-3-3'],
    vs:[{n:'3-3-1', note:'le/la（直接）vs lui（經過à）——測驗最愛考的分界'}] },
  { n:'3-3-3', lvl:'B2', name:'雙代名詞順序', fr:'ordre des doubles pronoms',
    brief:'兩顆代名詞疊放的固定軌道',
    ex:[{fr:'Je le lui donne.', zh:'我把它給他。'},
        {fr:'Elle nous les envoie demain.', zh:'她明天會把它們寄給我們。'}],
    pts:[
      {r:'兩顆代名詞疊放時順序固定：me/te/se/nous/vous → le/la/les → lui/leur → y → en',
       fr:'Il me le donne.', zh:'他把它給我。（me在前、le在後）'},
      {r:'兩個都是第三人稱時，COD（le/la/les）先於COI（lui/leur）——跟一二人稱的規則相反順序',
       fr:'Je le lui donne.', zh:'我把它給他。（le先、lui後）'},
      {r:'y和en永遠排最後，而且en習慣上緊貼在動詞前',
       fr:'Il y en a beaucoup.', zh:'那裡有很多。（y在en前）'},
    ],
    grid:{head:['1','2','3','4','5'],
          rows:[['me/te/se/nous/vous','le/la/les','lui/leur','y','en']]},
    usage:[
      {r:'口語點餐、借還東西時常用雙代名詞省話', fr:'Tu peux me le passer ?', zh:'你可以把它遞給我嗎？'},
      {r:'複合過去式裡雙代名詞整組放在助動詞前面', fr:'Je le lui ai donné hier.', zh:'我昨天把它給他了。'},
    ],
    more:[
      {fr:"Elle me l'a promis.", zh:'她跟我保證過（這件事）。'},
      {fr:'Ne le leur dis pas !', zh:'別跟他們說（這件事）！'},
      {fr:'On va vous les envoyer.', zh:'我們會把它們寄給您。'},
    ],
    see:['3-3-1','3-3-2'] },
 ]},

 { n:'3-4', name:'y 與 en', fr:'Les pronoms y et en', items:[
  { n:'3-4-1', lvl:'A2', name:'y ＝ 那裡', fr:'y de lieu',
    brief:'地點收進一個字母',
    ex:[{fr:"J'y vais demain.", zh:'我明天去那裡。'},
        {fr:"Tu habites toujours à Marseille ? — Oui, j'y habite depuis dix ans.", zh:'你還住馬賽嗎？——對，我住那裡十年了。'}],
    pts:[
      {r:'y 代替「à/en/chez/dans+地點」，把整個地點壓縮成一個字母，放在變位動詞前面',
       fr:'Tu vas à Paris ? — J\'y vais.', zh:'你要去巴黎嗎？——我要去（那裡）。'},
      {r:'固定口語句：On y va !（走吧）、Ça y est !（好了/搞定了）——已經變成慣用語不用拆開分析',
       fr:'Ça y est, on a fini !', zh:'搞定了，我們做完了！'},
    ],
    usage:[
      {r:'回答「你去不去/住不住某地」這類問題時，用y避免重複地名', fr:'Il est à la banque ? — Oui, il y est.', zh:'他在銀行嗎？——對，他在那裡。'},
      {r:'常跟命令式連用：Vas-y !（加油/去吧）', fr:'Vas-y, tu peux le faire !', zh:'加油，你可以做到的！'},
    ],
    exc:['y 只代替地點，à+人要用重讀代名詞不能用y（見3-4-2的對照）'],
    more:[
      {fr:'On y mange très bien.', zh:'在那裡吃得很好。'},
      {fr:"Je n'y vais pas ce week-end.", zh:'這週末我不去那裡。'},
      {fr:'Vous y êtes déjà allé ?', zh:'您已經去過那裡了嗎？'},
    ],
    topics:['pronom-y'], gram:'pronouns', see:['3-4-2','8-1-1'] },
  { n:'3-4-2', lvl:'B1', name:'y ＝ à + 事物', fr:'y remplaçant à + chose',
    brief:'penser à、réfléchir à 的事物版代名詞',
    ex:[{fr:"J'y réfléchis.", zh:'我在考慮這件事。'},
        {fr:"Tu penses souvent à ton avenir ? — Oui, j'y pense souvent.", zh:'你常想到你的未來嗎？——對，我常想到（這件事）。'}],
    pts:[
      {r:'y 也代替「à+事物」，用在 penser à、réfléchir à、s\'intéresser à 這類接à的動詞後面',
       fr:'Tu penses à ton examen ? — J\'y pense.', zh:'你在想你的考試嗎？——我在想（這件事）。'},
      {r:'⚠️ à後面如果是人，不能用y，要換成重讀代名詞：penser à quelqu\'un → penser à lui',
       fr:'Je pense à lui, pas à ce projet.', zh:'我在想他，不是這個計畫。'},
    ],
    usage:[
      {r:'講對某件事的想法、興趣、注意力時很常用y代替那件事', fr:"Tu t'intéresses à la politique ? — Un peu, j'y pense parfois.", zh:'你對政治有興趣嗎？——有一點，我偶爾會想到。'},
      {r:'回答「你有沒有注意到/考慮到某件事」時用y簡答', fr:"Tu as pensé à réserver ? — Oui, j'y ai pensé.", zh:'你有想到要訂位嗎？——有，我想到了。'},
    ],
    exc:['à+人一律不用y——判斷標準是「後面是人還是事物/地點」，這是跟3-4-1地點用法之間最容易搞混的分岔'],
    more:[
      {fr:"Fais attention à la marche ! — J'y fais attention.", zh:'小心台階！——我會注意的。'},
      {fr:"Il n'y pense jamais.", zh:'他從來不想這件事。'},
      {fr:'On y réfléchira ensemble.', zh:'我們會一起考慮這件事。'},
    ],
    see:['3-4-1','3-4-4'] },
  { n:'3-4-3', lvl:'B1', name:'en ＝ 部分量', fr:'en de quantité',
    brief:'du/de la/des/數量 的名詞收進 en',
    ex:[{fr:"J'en ai deux.", zh:'我有兩個。'},
        {fr:"Tu veux du café ? — Oui, j'en veux bien.", zh:'你要咖啡嗎？——好，我要一些。'}],
    pts:[
      {r:'en 代替「du/de la/des/數量+名詞」，把「一部分的東西」壓縮成一個字',
       fr:"Tu veux du café ? — J'en veux bien.", zh:'你要咖啡嗎？——我要（一些）。'},
      {r:'原句帶數字或明確數量時，答句要保留數字/量詞，只有名詞被en取代',
       fr:'Tu as des enfants ? — J\'en ai deux.', zh:'你有小孩嗎？——我有兩個。（deux留著）'},
      {r:'否定句裡 en 一樣放在動詞前，ne…pas包住整組',
       fr:"Je n'en ai pas.", zh:'我沒有（這個東西）。'},
    ],
    usage:[
      {r:'回答「有沒有/要不要某個東西（不特指哪一個）」時用en', fr:'Il y a du pain ? — Oui, il y en a.', zh:'有麵包嗎？——有（一些）。'},
      {r:'量詞句（beaucoup de、un peu de…）後面接名詞也常收進en', fr:"J'en ai beaucoup.", zh:'我有很多（這個）。'},
    ],
    exc:['en 代替的是「部分/數量」，不是「特定那一個」——特定的東西要用COD代名詞le/la/les，不是en'],
    more:[
      {fr:"Combien de frères as-tu ? — J'en ai un.", zh:'你有幾個兄弟？——我有一個。'},
      {fr:'Elle en boit tous les matins.', zh:'她每天早上都喝（一些）。'},
      {fr:'Vous en avez assez ?', zh:'您這樣夠了嗎？'},
    ],
    see:['3-4-4','1-3-3'],
    vs:[{n:'8-2-1', note:'en 也是介係詞（en France, en bus）——同形不同身分'}] },
  { n:'3-4-4', lvl:'B1', name:'en ＝ de + 事物', fr:'en remplaçant de + chose',
    brief:'parler de、avoir besoin de 的事物版',
    ex:[{fr:"J'en ai besoin.", zh:'我需要它。'},
        {fr:"Tu parles souvent de ton travail ? — Oui, j'en parle souvent.", zh:'你常聊你的工作嗎？——對，我常聊（這件事）。'}],
    pts:[
      {r:'en 也代替「de+事物」，用在 parler de、avoir besoin de、avoir envie de、être content de 這類接de的動詞/形容詞後面',
       fr:'Tu as besoin de ce livre ? — J\'en ai besoin.', zh:'你需要這本書嗎？——我需要它。'},
      {r:'⚠️ de後面如果是人，不能用en，要換成重讀代名詞：parler de quelqu\'un → parler de lui',
       fr:'Je parle de lui, pas de ce film.', zh:'我在講他，不是這部電影。'},
    ],
    usage:[
      {r:'講對某件事的需求、渴望、談論內容時很常用en代替那件事', fr:"J'ai envie de partir. → J'en ai envie.", zh:'我想離開。→ 我想要（這件事）。'},
      {r:'回答「你滿不滿意/自不自豪某件事」時用en簡答', fr:"Tu es content de ton travail ? — Oui, j'en suis content.", zh:'你對自己的工作滿意嗎？——對，我很滿意。'},
    ],
    exc:['de+人一律不用en——判斷標準是「de後面是人還是事物」，跟3-4-3數量用法是另一組容易混的分岔'],
    more:[
      {fr:'Il en est très fier.', zh:'他對這件事非常自豪。'},
      {fr:'On en discutera demain.', zh:'我們明天會討論這件事。'},
      {fr:"Je ne m'en souviens plus.", zh:'我不記得這件事了。'},
    ],
    see:['3-4-3','3-4-2'] },
 ]},

 { n:'3-5', name:'關係代名詞', fr:'Pronoms relatifs', topics:['qui-que'], items:[
  { n:'3-5-1', lvl:'B1', name:'qui（主格）', fr:'qui sujet',
    brief:'子句缺主詞用 qui——後面直接接動詞',
    ex:[{fr:"L'homme qui parle est mon prof.", zh:'正在說話的人是我老師。'},
        {fr:'Je cherche un livre qui parle de la Révolution française.', zh:'我在找一本講法國大革命的書。'}],
    pts:[
      {r:'子句裡缺主詞時用 qui 銜接，qui 後面直接接動詞（不需要再放主詞）',
       fr:'la France est un pays qui change', zh:'法國是一個在變化的國家'},
      {r:'qui 前面一定是先行詞（被修飾的名詞），qui 本身代替那個先行詞當新子句的主詞',
       fr:"C'est une amie qui habite à Lyon.", zh:'這是一位住在里昂的朋友。'},
      {r:'qui 永不縮寫，即使後面是母音開頭：qui il 維持原樣，不會變成qu\'il（那是que的縮寫）',
       fr:'Voici la personne qui a téléphoné.', zh:'這是打過電話的人。'},
    ],
    usage:[
      {r:'描述人、動物、事物「做了/在做什麼動作」時用qui補充說明', fr:"J'ai un ami qui parle cinq langues.", zh:'我有一個朋友會說五種語言。'},
      {r:'定義類句子（那個…的人/東西）常用qui開頭子句', fr:'Cherchez un plombier qui travaille le week-end.', zh:'找一個週末也工作的水電工。'},
    ],
    exc:['qui當關係代名詞時只代替第三人稱先行詞，不會出現「Je qui parle」這種用法'],
    more:[
      {fr:'Les enfants qui jouent dehors sont mes neveux.', zh:'在外面玩的小孩是我姪子姪女。'},
      {fr:'Ce sont des produits qui viennent de France.', zh:'這些是來自法國的產品。'},
      {fr:'Je ne connais personne qui pense comme ça.', zh:'我不認識任何這樣想的人。'},
    ],
    gram:'relatifs', see:['3-5-2','3-5-3'],
    vs:[{n:'3-5-2', note:'挖掉的洞是主詞→qui；是受詞→que'}] },
  { n:'3-5-2', lvl:'B1', name:'que（受格）', fr:'que objet',
    brief:'子句缺受詞用 que——後面先出現新主詞',
    ex:[{fr:"C'est un métier que j'adore.", zh:'這是我熱愛的職業。'},
        {fr:'Le film que nous avons vu hier était excellent.', zh:'我們昨天看的電影很棒。'}],
    pts:[
      {r:'子句裡缺受詞時用 que 銜接，que 後面會先出現一個新主詞',
       fr:"c'est un métier que j'adore", zh:'這是一個我熱愛的職業'},
      {r:'que 代替先行詞當新子句的直接受詞（COD），跟qui當主詞的邏輯對稱',
       fr:'Voici le livre que je cherche.', zh:'這是我在找的書。'},
      {r:'母音或啞音h前縮寫成 qu\'',
       fr:"le livre qu'il lit", zh:'他在讀的那本書'},
    ],
    usage:[
      {r:'描述「某人對某物做了什麼」時，被做的那個東西當先行詞、用que補充', fr:"J'aime la robe que tu portes.", zh:'我喜歡你穿的那件洋裝。'},
      {r:'複合過去式裡，que所指的先行詞在前，過去分詞要配合它性數（見5-2-5）', fr:"La lettre que j'ai écrite est longue.", zh:'我寫的那封信很長。'},
    ],
    exc:['分辨qui/que的方法：子句裡先出現動詞就用qui（缺主詞），先出現主詞才用que（缺受詞）——看子句結構不是看意思'],
    more:[
      {fr:'Le pays que je préfère, c\'est le Japon.', zh:'我最喜歡的國家是日本。'},
      {fr:"Ce n'est pas le sac que j'ai acheté.", zh:'這不是我買的那個包。'},
      {fr:"Les amis que tu m'as présentés sont sympas.", zh:'你介紹給我的朋友們人很好。'},
    ],
    gram:'relatifs', see:['3-5-1','5-2-5'] },
  { n:'3-5-3', lvl:'B1', name:'où（時地格）', fr:'où',
    brief:'地點與時間的關係詞',
    ex:[{fr:"C'est la ville où je suis né.", zh:'這是我出生的城市。'},
        {fr:'Je me souviens du jour où nous nous sommes rencontrés.', zh:'我記得我們相遇的那天。'}],
    pts:[
      {r:'où 代替「地點」的先行詞，取代原本要用的介詞+地點結構',
       fr:"la ville où j'habite", zh:'我住的那座城市'},
      {r:'où 也代替「時間」的先行詞，中文常說「…的那天/那時」，法文不能用quand（quand不是關係代名詞）',
       fr:'le jour où je suis arrivé', zh:'我到達的那天'},
    ],
    usage:[
      {r:'描述某個地方發生的事，用où接上補充子句', fr:"Voici le café où on s'est rencontrés.", zh:'這是我們相遇的咖啡廳。'},
      {r:'描述某個時間點發生的事，一樣用où不是quand', fr:"Je me souviens de l'année où j'ai commencé le français.", zh:'我記得我開始學法文的那一年。'},
    ],
    exc:['quand不能當關係代名詞使用，只能當疑問詞或連接詞：接在名詞後面補充說明時間永遠用où'],
    more:[
      {fr:'Le restaurant où nous avons dîné était excellent.', zh:'我們吃晚餐的那家餐廳很棒。'},
      {fr:"C'est le quartier où j'ai grandi.", zh:'這是我長大的社區。'},
      {fr:"Je n'oublierai jamais le moment où j'ai reçu la nouvelle.", zh:'我永遠不會忘記我收到消息的那一刻。'},
    ],
    see:['3-5-1','3-5-2'] },
  { n:'3-5-4', lvl:'B2', name:'dont（de格）', fr:'dont',
    brief:'動詞帶 de 的關係詞：de+先行詞',
    ex:[{fr:'le livre dont tu parles', zh:'你說的那本書'},
        {fr:"C'est un outil dont j'ai vraiment besoin.", zh:'這是一個我真的需要的工具。'}],
    pts:[
      {r:'動詞或形容詞固定接de的（parler de、avoir besoin de、être content de…），子句裡缺的那個de+名詞就用dont代替',
       fr:'parler de → le film dont je parle', zh:'我在講的那部電影'},
      {r:'dont 也能代替「de+名詞」表示所有關係（…的），把兩句黏成帶「的」的子句',
       fr:'la fille dont le père est médecin', zh:'那個爸爸是醫生的女孩'},
      {r:'dont 前面一定接名詞先行詞，不需要再另外加de——dont本身已經包含了de',
       fr:'le sujet dont on discute', zh:'我們在討論的那個主題'},
    ],
    usage:[
      {r:'先確認動詞是不是接de（avoir besoin de、parler de、rêver de…），是的話才用dont', fr:'Voici le projet dont je rêve.', zh:'這是我夢想的那個計畫。'},
      {r:'描述某人的所屬物（父母、職業、特徵）時常用dont表達「…的」', fr:"C'est un homme dont je connais la famille.", zh:'這是一個我認識他家人的人。'},
    ],
    exc:['dont不能跟其他介詞疊用：avoir besoin de已經被dont吸收，不能再寫成de dont'],
    more:[
      {fr:"C'est un sujet dont on parle beaucoup en ce moment.", zh:'這是最近很多人在討論的話題。'},
      {fr:'La voiture dont il est fier est une vieille Renault.', zh:'他引以為傲的那輛車是一輛老雷諾。'},
      {fr:'Voici les documents dont vous avez besoin.', zh:'這是您需要的文件。'},
    ],
    see:['3-5-2','3-5-5'] },
  { n:'3-5-5', lvl:'B2', name:'lequel 家族', fr:'lequel / auquel / duquel',
    brief:'介詞後的關係詞，性數配合',
    ex:[{fr:'la raison pour laquelle je pars', zh:'我離開的原因'},
        {fr:"Le stylo avec lequel j'écris est cassé.", zh:'我用來寫字的那支筆壞了。'}],
    pts:[
      {r:'介詞（sur、avec、pour、dans…）後面接事物的關係代名詞用lequel家族，跟著先行詞的性數配合',
       fr:'la table sur laquelle je travaille', zh:'我在上面工作的那張桌子'},
      {r:'跟à、de縮合會產生特殊形：à+lequel→auquel、de+lequel→duquel（陰性複數也各有對應形）',
       fr:'le projet auquel je pense', zh:'我在想的那個計畫'},
      {r:'先行詞是人時，介詞後也可以簡化用qui代替lequel（更口語自然）',
       fr:"l'ami avec qui je voyage", zh:'跟我一起旅行的朋友'},
    ],
    grid:{head:['','陽性單數','陰性單數','陽性複數','陰性複數'],
          rows:[['基本形','lequel','laquelle','lesquels','lesquelles'],
                ['à+','auquel','à laquelle','auxquels','auxquelles'],
                ['de+','duquel','de laquelle','desquels','desquelles']]},
    usage:[
      {r:'描述「在…上/裡面/用…」發生的事，且先行詞是物品時用lequel家族', fr:"L'ordinateur sur lequel je travaille est lent.", zh:'我在上面工作的那台電腦很慢。'},
      {r:'書面、正式場合比qui更常見；口語人物先行詞常直接簡化用qui', fr:"Les collègues avec qui je travaille sont sympas.", zh:'跟我一起工作的同事人很好。'},
    ],
    exc:['先行詞是人且介詞不是de/à時，用qui比lequel更自然（avec qui優於avec lequel），但語法上lequel家族仍然正確'],
    more:[
      {fr:'C\'est le dossier sur lequel nous travaillons.', zh:'這是我們正在處理的檔案。'},
      {fr:'Voici les critères auxquels il faut penser.', zh:'這是必須考慮的幾個標準。'},
      {fr:"L'entreprise pour laquelle elle travaille est internationale.", zh:'她工作的那家公司是跨國企業。'},
    ],
    see:['3-5-4','3-5-1'] },
 ]},

 { n:'3-6', name:'不定代名詞', fr:'Pronoms indéfinis', items:[
  { n:'3-6-1', lvl:'A2', name:'quelqu\'un / quelque chose / tout', fr:'indéfinis courants',
    brief:'某人/某事/全部 的代名詞組',
    ex:[{fr:'Tout le monde est là.', zh:'大家都在。（est 不是 sont）'},
        {fr:"Il y a quelqu'un à la porte.", zh:'門口有人。'}],
    pts:[
      {r:'quelqu\'un（某人）、quelque chose（某事/某物）——不定代名詞，不指定確切是誰/什麼',
       fr:"J'ai vu quelqu'un dans le jardin.", zh:'我在花園裡看到有人。'},
      {r:'tout le monde（大家）指全體人，但文法上是單數集合詞，動詞要用第三人稱單數',
       fr:'Tout le monde comprend.', zh:'大家都懂。（comprend不是comprennent）'},
      {r:'否定鏡像：quelqu\'un↔personne、quelque chose↔rien（見7-2-2），一問一答常成對出現',
       fr:'Tu cherches quelque chose ? — Non, rien.', zh:'你在找什麼嗎？——沒，什麼都不找。'},
    ],
    usage:[
      {r:'不確定或不想指名道姓時，用quelqu\'un/quelque chose帶過', fr:"Quelqu'un a appelé pour toi.", zh:'有人打電話找你。'},
      {r:'描述「所有人」的共同狀態、看法時用tout le monde', fr:'Tout le monde aime ce restaurant.', zh:'大家都喜歡這家餐廳。'},
    ],
    exc:['tout le monde、personne、rien 這幾個看起來像複數概念的詞，動詞一律用單數配合——這是中文使用者常見的錯誤來源'],
    more:[
      {fr:"Est-ce que quelqu'un peut m'aider ?", zh:'有人可以幫我嗎？'},
      {fr:"Je n'ai rien à ajouter.", zh:'我沒有什麼要補充的。'},
      {fr:'Tout le monde était content du résultat.', zh:'大家都對結果很滿意。'},
    ],
    see:['7-2-2'] },
 ]},
]},

// ═══ 第 4 章 動詞變位系統（現在式） ══════════════════════════
{ n:'4', name:'動詞變位系統', fr:'La conjugaison au présent', sections:[

 { n:'4-1', name:'第一組 -ER', fr:'Verbes en -ER', items:[
  { n:'4-1-1', lvl:'A1', name:'標準 -ER 變位', fr:'parler 型',
    brief:'90%動詞的家：字尾多半不發音，變位其實是拼字',
    pts:['-e/-es/-e/-ons/-ez/-ent','parle=parles=parlent 同音——耳朵只要顧 nous -ons、vous -ez','新動詞一律入此組：googler、liker'],
    ex:[{fr:'Je parle, nous parlons.', zh:'我說、我們說。'}],
    topics:['er-verbs'], gram:'er-verbs' },
  { n:'4-1-2', lvl:'A2', name:'拼寫微調五家族', fr:'particularités orthographiques',
    brief:'為保住發音做的拼字手術',
    pts:['manger→nous mangeons（保軟g）；commencer→nous commençons（ç保s音）','acheter→j\'achète（啞音節前開音變è）；appeler→j\'appelle（疊字版同功能）','payer→je paie/paye（兩可）'],
    ex:[{fr:'nous mangeons, j\'achète', zh:'我們吃、我買'}] },
  { n:'4-1-3', lvl:'A1', name:'aller（獨行俠）', fr:'aller',
    brief:'唯一不規則的 -er 動詞——因為它是拼裝車',
    pts:['vais/vas/va/allons/allez/vont（來自三個不同拉丁動詞的零件）','是 futur proche 的引擎（見 5-5-1）'],
    ex:[{fr:'Je vais au marché.', zh:'我去市場。'}] },
 ]},

 { n:'4-2', name:'第二組 -IR', fr:'Verbes en -IR (finir)', items:[
  { n:'4-2-1', lvl:'A2', name:'finir 型（-iss-）', fr:'finir, choisir, réfléchir',
    brief:'複數帶 -iss- 的規則家族',
    pts:['-is/-is/-it/-issons/-issez/-issent','-iss- 是拉丁文「逐漸變成」的化石：grandir（長大）、rougir（變紅）多半是變化類動詞','regular 判別法：能不能說 nous -issons'],
    ex:[{fr:'Nous choisissons le menu.', zh:'我們選套餐。'}],
    topics:['ir-re-verbs'], gram:'ir-re' },
 ]},

 { n:'4-3', name:'第三組（不規則）', fr:'Le 3e groupe', items:[
  { n:'4-3-1', lvl:'A1', name:'être 與 avoir', fr:'être / avoir',
    brief:'最高頻→磨損最兇→最不規則',
    pts:['être：suis/es/est/sommes/êtes/sont；avoir：ai/as/a/avons/avez/ont','年齡感受用 avoir：J\'ai 25 ans、j\'ai faim/froid/chaud','兩者都是複合時態的助動詞（見 5-2）'],
    ex:[{fr:"J'ai faim.", zh:'我餓了。（擁有飢餓）'}],
    topics:['etre-avoir'], gram:'etre-avoir' },
  { n:'4-3-2', lvl:'A2', name:'faire 與 dire', fr:'faire / dire',
    brief:'vous faites、vous dites——僅有的非 -ez 組',
    pts:['faire：fais/fais/fait/faisons/faites/font','dire：dis/dis/dit/disons/dites/disent','faire 是萬用動詞：faire du sport/les courses/la cuisine、il fait beau'],
    ex:[{fr:'Vous faites la cuisine ?', zh:'你們煮飯嗎？（faites！）'}],
    topics:['irregular-verbs-3rd-group'], gram:'ir-re' },
  { n:'4-3-3', lvl:'A2', name:'prendre 與 mettre', fr:'prendre / mettre',
    brief:'單數規矩、複數變臉',
    pts:['prendre：prends/prend/prenons/prennent（複數丟d，ils疊n）','mettre：mets/met/mettons（雙t只在複數）','家族：apprendre、comprendre；promettre、permettre 同模式'],
    ex:[{fr:'Ils prennent le bus.', zh:'他們搭公車。'}] },
  { n:'4-3-4', lvl:'A2', name:'venir 與 tenir', fr:'venir / tenir',
    brief:'viens/viennent 的鼻音家族',
    pts:['viens/viens/vient/venons/venez/viennent','venir de + inf＝剛剛做完（見 5-6-1）','家族：revenir、devenir、se souvenir；tenir 同模式'],
    ex:[{fr:'Je viens de Taïwan.', zh:'我來自台灣。'}] },
  { n:'4-3-5', lvl:'A2', name:'partir / sortir / dormir 型', fr:'verbes en -tir/-mir',
    brief:'單數砍尾音的口語家族',
    pts:['pars/pars/part/partons（單數丟t音）','sortir、dormir、sentir、servir 同模式'],
    ex:[{fr:'Je pars demain.', zh:'我明天出發。'}] },
  { n:'4-3-6', lvl:'A2', name:'vendre 型 -RE', fr:'verbes en -dre',
    brief:'il 形零字尾的規則 -RE 家族',
    pts:['vends/vends/vend/vendons/vendez/vendent','répondre、attendre、entendre、perdre 同模式'],
    ex:[{fr:'Ils vendent le pain.', zh:'他們賣麵包。'}] },
  { n:'4-3-7', lvl:'A2', name:'情態三王 pouvoir/vouloir/devoir', fr:'verbes modaux',
    brief:'自己變位、後面永遠原形',
    pts:['peux/peut/pouvons/peuvent；veux/veut/voulons/veulent；dois/doit/devons/doivent','⚠️ elle veut 不是 veux——x是je/tu專用','je voudrais＝想要的禮貌版（條件式，見 6-2-1）'],
    ex:[{fr:'Elle veut partir.', zh:'她想離開。'}],
    topics:['pouvoir-vouloir'], gram:'ir-re' },
  { n:'4-3-8', lvl:'B1', name:'savoir / connaître / voir / boire', fr:'autres irréguliers',
    brief:'高頻不規則的第二梯隊',
    pts:['sais/sait/savons；connais/connaît/connaissons；vois/voit/voyons/voient；bois/boit/buvons/boivent','savoir＝會（技能/資訊）、connaître＝認識（人/地方）——只能接名詞'],
    ex:[{fr:'Je sais nager mais je ne connais pas cette piscine.', zh:'我會游泳但不認識這間泳池。'}] },
 ]},

 { n:'4-4', name:'反身動詞', fr:'Verbes pronominaux', items:[
  { n:'4-4-1', lvl:'A2', name:'反身代詞系統', fr:'se laver 型',
    brief:'動作回到自己，代詞跟人稱走',
    pts:['me/te/se/nous/vous/se + 動詞：je me lave','母音前縮寫：je m\'appelle、tu t\'habilles','日常起居全家桶：se lever、se doucher、s\'habiller、se coucher'],
    ex:[{fr:'Je me réveille à 7h.', zh:'我七點醒來。'}],
    topics:['reflexive-verbs'], gram:'reflechis' },
  { n:'4-4-2', lvl:'A2', name:'反身動詞的否定', fr:'négation des pronominaux',
    brief:'ne 站在反身代詞前面',
    pts:['Je ne me réveille pas à 7h（ne+me+動詞+pas）','原形時代詞先行：ne pas se lever'],
    ex:[{fr:'Il ne se rase pas.', zh:'他不刮鬍子。'}] },
  { n:'4-4-3', lvl:'B1', name:'相互動詞', fr:'sens réciproque',
    brief:'複數的 se ＝「互相」',
    pts:['Ils se téléphonent（他們互打電話）','On se voit demain ?（明天見？）'],
    ex:[{fr:'Nous nous aimons.', zh:'我們相愛。'}] },
 ]},

 { n:'4-5', name:'無人稱動詞', fr:'Verbes impersonnels', items:[
  { n:'4-5-1', lvl:'A1', name:'il y a / il faut / il fait', fr:'expressions impersonnelles',
    brief:'il 是假主詞，沒有人在那裡',
    pts:['il y a＝有（存在）：Il y a un chien','il faut + inf＝必須（見 6-7-1）','天氣全家桶：il fait beau/froid、il pleut、il neige'],
    ex:[{fr:'Il y a du vent et il pleut.', zh:'有風而且下雨。'}],
    vs:[{n:'9-4-1', note:'il y a + 時間＝「…之前」是另一個身分'}] },
 ]},
]},
];

const CODEX_PART2 = [

// ═══ 第 5 章 時態（直陳式時間軸） ════════════════════════════
{ n:'5', name:'時態', fr:'Les temps de l\'indicatif', sections:[

 { n:'5-1', name:'現在式的地盤', fr:'Le présent', items:[
  { n:'5-1-1', lvl:'A1', name:'présent 的三種工作', fr:'valeurs du présent',
    brief:'現在、習慣、以及「還在繼續」——比中文英文管得寬',
    pts:['當下：Je mange（我正在吃——法文沒有進行式，présent兼任）','習慣：Je travaille le lundi','depuis 句的「持續到現在」也用présent（見 9-4-1）'],
    ex:[{fr:'Je travaille depuis 8h.', zh:'我從八點工作到現在。（用現在式！）'}] },
 ]},

 { n:'5-2', name:'複合過去式', fr:'Le passé composé', topics:['passe-compose'], items:[
  { n:'5-2-1', lvl:'A2', name:'avoir + 過去分詞', fr:'PC avec avoir',
    brief:'「擁有＋完成品」表達過去——大多數動詞的過去式',
    pts:["J'ai mangé、Ils ont acheté、Vous avez trouvé",'否定包住助動詞：On n\'a pas trouvé de lit','疑問倒裝也只動助動詞：As-tu fini ?'],
    ex:[{fr:'Vous avez trouvé des meubles ?', zh:'你們找到家具了嗎？'}], gram:'passe' },
  { n:'5-2-2', lvl:'A2', name:'être 家族＋配合', fr:'PC avec être',
    brief:'移動/狀態轉變動詞：分詞像形容詞，跟主詞配合',
    pts:['14常客：aller, venir, partir, arriver, entrer, sortir, monter, descendre, rester, tomber, naître, mourir, retourner, passer','Elle est sortie（+e）、Ils sont partis（+s）——跟 elle est grande 同一個配合邏輯','記法：這些動詞講的是「主詞自己變成什麼/移到哪」'],
    ex:[{fr:'Elle est arrivée hier.', zh:'她昨天到了。'}],
    exc:['monter/descendre/sortir/passer 帶直接受詞時改用avoir：J\'ai sorti le chien（我遛了狗）'],
    vs:[{n:'5-2-3', note:'反身動詞一律搭 être'}], gram:'passe' },
  { n:'5-2-3', lvl:'B1', name:'反身動詞的 PC', fr:'PC des pronominaux',
    brief:'一律 être；配合看代詞是不是直接受詞',
    pts:['Elle s\'est levée（+e）','⚠️ 代詞是間接受詞時不配合：Elle s\'est lavé les mains（真正受詞是les mains在後面）'],
    ex:[{fr:'Ils se sont couchés tard.', zh:'他們很晚睡。'}] },
  { n:'5-2-4', lvl:'A2', name:'過去分詞的形', fr:'participes passés',
    brief:'-é / -i / -u 三條生產線＋高頻例外',
    pts:['-er→é（mangé）、-ir→i（fini）、-re→u（vendu）','高頻例外：être→été、avoir→eu、faire→fait、prendre→pris、mettre→mis、dire→dit、écrire→écrit、voir→vu、boire→bu、pouvoir→pu、vouloir→voulu、devoir→dû、venir→venu、naître→né、mourir→mort'],
    ex:[{fr:"J'ai pris le métro.", zh:'我搭了地鐵。（prendre→pris）'}] },
  { n:'5-2-5', lvl:'B2', name:'COD 前置的配合', fr:'accord avec COD antéposé',
    brief:'受詞跑到前面時，avoir 的分詞也要配合它',
    pts:['la robe que j\'ai achetée（que=la robe 在前→+e）','Je les ai vus（les在前→+s）','寫作扣分重災區，口語多半聽不出來'],
    ex:[{fr:'Ces photos ? Je les ai prises hier.', zh:'這些照片？我昨天拍的。（prises+es）'}] },
 ]},

 { n:'5-3', name:'未完成過去式', fr:'L\'imparfait', topics:['imparfait'], items:[
  { n:'5-3-1', lvl:'A2', name:'imparfait 的用途', fr:'valeurs de l\'imparfait',
    brief:'廣角鏡：過去的背景、狀態、習慣',
    pts:['描述當時場景：Il faisait beau, il y avait du monde','過去的習慣：Quand j\'étais petit, je jouais au foot','A2階段先掌握無人稱三兄弟：il faisait / il y avait / c\'était'],
    ex:[{fr:"C'était super !", zh:'（那時）超棒的！'}], gram:'imparfait',
    vs:[{n:'5-3-3', note:'vs passé composé——法文時態最重要的一組對比'}] },
  { n:'5-3-2', lvl:'B1', name:'imparfait 的變位', fr:'formation',
    brief:'nous 現在式砍 -ons ＋ ais/ais/ait/ions/iez/aient',
    pts:['nous faisons → je faisais；nous buvons → je buvais','唯一例外：être → j\'étais（因為 nous sommes 砍不出字根）'],
    ex:[{fr:'Nous mangions ensemble.', zh:'我們那時常一起吃飯。'}] },
  { n:'5-3-3', lvl:'B1', name:'PC vs imparfait（鏡頭論）', fr:'PC vs imparfait',
    brief:'特寫拍事件、廣角拍背景——同一段故事兩顆鏡頭',
    pts:['Il pleuvait（背景）quand je suis sorti（事件）','問自己：這句是「然後發生了什麼」（PC）還是「當時是什麼樣子」（imparfait）','敘事考題的靈魂，TEF/TCF寫作口說必考'],
    ex:[{fr:'Je dormais quand tu as téléphoné.', zh:'你來電時我正在睡。'}],
    vs:[{n:'5-2-2', note:'事件線用PC'}] },
 ]},

 { n:'5-4', name:'愈過去式', fr:'Le plus-que-parfait', items:[
  { n:'5-4-1', lvl:'B1', name:'過去的過去', fr:'PQP',
    brief:'助動詞改 imparfait ＋ 分詞：比過去更早一層',
    pts:["J'avais déjà mangé quand il est arrivé（他到之前我就吃完了）",'結構＝PC的助動詞退一格時態','間接引語的時態退位也用它（見 7-6-1）'],
    ex:[{fr:'Elle était déjà partie.', zh:'她（那時）已經走了。'}] },
 ]},

 { n:'5-5', name:'未來', fr:'Le futur', items:[
  { n:'5-5-1', lvl:'A2', name:'futur proche', fr:'aller + infinitif',
    brief:'口語主力：aller 變位＋原形',
    pts:['Je vais finir la robe（即將/打算）','只有 aller 動、後面永遠原形','否定包 aller：Je ne vais pas partir'],
    ex:[{fr:'On va être en retard !', zh:'我們要遲到了！'}],
    topics:['futur-proche'], gram:'futur-proche',
    vs:[{n:'5-5-2', note:'口語近程用proche、書面/遠程/承諾用simple'}] },
  { n:'5-5-2', lvl:'B1', name:'futur simple', fr:'le futur simple',
    brief:'原形＋avoir字尾：書面與承諾的未來',
    pts:['parler+ai/as/a/ons/ez/ont：je parlerai','高頻不規則字根：être→ser-、avoir→aur-、aller→ir-、faire→fer-、venir→viendr-、pouvoir→pourr-、voir→verr-','quand+futur（法文邏輯）：Quand j\'aurai le temps, je viendrai'],
    ex:[{fr:'Demain, il fera beau.', zh:'明天天氣會好。（氣象預報體）'}] },
 ]},

 { n:'5-6', name:'剛剛過去', fr:'Le passé récent', items:[
  { n:'5-6-1', lvl:'A2', name:'venir de + 原形', fr:'passé récent',
    brief:'「從做完某事走過來」＝剛剛做完',
    pts:['Je viens de finir（我剛結束）','aller+inf 的鏡像結構，同樣只動 venir'],
    ex:[{fr:'Il vient de partir.', zh:'他剛走。'}],
    topics:['passe-recent'], gram:'passe' },
 ]},

 { n:'5-7', name:'簡單過去式（識讀）', fr:'Le passé simple', items:[
  { n:'5-7-1', lvl:'B2', name:'文學過去式', fr:'passé simple',
    brief:'只出現在書面敘事，會認就好不用會寫',
    pts:['il parla、elle fut、ils vinrent——小說/歷史文的PC替身','閱讀測驗看到別慌：把它當PC理解即可'],
    ex:[{fr:'Il ouvrit la porte et sortit.', zh:'他開門出去了。（小說體）'}] },
 ]},

 { n:'5-8', name:'時態呼應', fr:'La concordance des temps', items:[
  { n:'5-8-1', lvl:'B2', name:'主句過去，從句退位', fr:'concordance',
    brief:'主句一變過去，從句時態整排後退一格',
    pts:['présent→imparfait：Il dit qu\'il vient → Il a dit qu\'il venait','futur→conditionnel：…qu\'il viendrait','PC→PQP：…qu\'il était venu'],
    ex:[{fr:'Elle pensait que tu viendrais.', zh:'她以為你會來。'}],
    vs:[{n:'7-6-1', note:'間接引語就是它的主戰場'}] },
 ]},
]},

// ═══ 第 6 章 語氣 ═══════════════════════════════════════════
{ n:'6', name:'語氣', fr:'Les modes', sections:[

 { n:'6-1', name:'命令式', fr:'L\'impératif', items:[
  { n:'6-1-1', lvl:'A2', name:'命令式', fr:'impératif',
    brief:'砍掉主詞直接說；-er 動詞 tu 形去 s',
    pts:['只有 tu/nous/vous 三格：Mange ! / Allons-y ! / Montez !','-ER 的 tu 去 s（Mange !），其他組保留（Finis !）','否定照包：N\'achetez pas de tickets !','代名詞後掛且 me→moi：Aide-moi !（否定回前：Ne m\'aide pas）'],
    ex:[{fr:'Montez dans le bus !', zh:'上公車！'}],
    topics:['imperative-mood'], gram:'imperatif' },
 ]},

 { n:'6-2', name:'條件式', fr:'Le conditionnel', items:[
  { n:'6-2-1', lvl:'A2', name:'禮貌條件式', fr:'je voudrais …',
    brief:'把要求包上「假設」的軟墊',
    pts:['je voudrais（我想要）、j\'aimerais、tu pourrais…?、on devrait','點餐/請求的標準開場：Je voudrais une baguette'],
    ex:[{fr:'Je voudrais un café, s\'il vous plaît.', zh:'我想要一杯咖啡，謝謝。'}] },
  { n:'6-2-2', lvl:'B1', name:'條件式現在＋si句', fr:'conditionnel présent',
    brief:'futur字根＋imparfait字尾：假設世界的動詞',
    pts:['形：je parlerais、il ferait（跟futur只差字尾）','Si + imparfait, conditionnel：Si j\'avais le temps, je voyagerais','也用於委婉斷言：Ce serait une bonne idée'],
    ex:[{fr:'Si j\'étais riche, j\'achèterais une maison.', zh:'如果我有錢就買房。'}],
    vs:[{n:'6-6-1', note:'si 條件句三式的第二式'}] },
  { n:'6-2-3', lvl:'B2', name:'條件式過去（悔恨式）', fr:'conditionnel passé',
    brief:'aurais/serais＋分詞：早知道就…',
    pts:["J'aurais dû partir plus tôt（我早該早點走）",'Si + PQP, cond. passé：Si j\'avais su, je n\'aurais pas accepté'],
    ex:[{fr:'Tu aurais pu me dire !', zh:'你大可以跟我說啊！'}] },
 ]},

 { n:'6-3', name:'虛擬式', fr:'Le subjonctif', items:[
  { n:'6-3-1', lvl:'B1', name:'什麼時候觸發', fr:'emplois du subjonctif',
    brief:'主句表達意志/情緒/懷疑時，que 後面切到主觀時空',
    pts:['意志：il faut que、je veux que','情緒：je suis content que','懷疑：je ne pense pas que','連詞：bien que、pour que、avant que','⚠️ 確信類不觸發：je pense que + 直陳式'],
    ex:[{fr:'Il faut que tu viennes.', zh:'你必須來。'}],
    vs:[{n:'6-3-3', note:'pense que vs ne pense pas que——同動詞兩個時空'}] },
  { n:'6-3-2', lvl:'B1', name:'虛擬式的形', fr:'formation',
    brief:'ils 現在式砍 -ent ＋ e/es/e/ions/iez/ent',
    pts:['ils finissent → que je finisse','高頻不規則：être→sois、avoir→aie、aller→aille、faire→fasse、pouvoir→puisse、savoir→sache'],
    ex:[{fr:'…que tu fasses tes devoirs.', zh:'…你把作業做完。'}] },
  { n:'6-3-3', lvl:'B2', name:'虛擬 vs 直陳', fr:'subjonctif ou indicatif ?',
    brief:'斷言用直陳、態度用虛擬——考分界線',
    pts:['Je pense qu\'il vient（斷言）/ Je ne pense pas qu\'il vienne（懷疑）','espérer 特例走直陳：J\'espère qu\'il viendra'],
    ex:[{fr:'Je doute qu\'il soit là.', zh:'我懷疑他在不在。'}] },
 ]},

 { n:'6-4', name:'被動與替代', fr:'La voix passive', items:[
  { n:'6-4-1', lvl:'B2', name:'被動語態與 on 替代', fr:'passif / on',
    brief:'être＋分詞（配合主詞）；口語多半用 on 繞開',
    pts:['La lettre a été écrite par Marie（分詞配合主詞）','口語替代：On m\'a volé mon vélo（比 mon vélo a été volé 自然）','se faire + inf：Il s\'est fait renvoyer（被開除）'],
    ex:[{fr:'Le gâteau a été mangé.', zh:'蛋糕被吃掉了。'}],
    vs:[{n:'3-1-2', note:'on 的第三個身分：被動殺手'}] },
 ]},

 { n:'6-5', name:'副動詞', fr:'Le gérondif', items:[
  { n:'6-5-1', lvl:'B2', name:'en + -ant', fr:'gérondif',
    brief:'「一邊…一邊」與「藉由…」',
    pts:['Il écoute de la musique en travaillant（同時）','On apprend en faisant（方式/手段）','形：nous 現在式砍-ons＋ant（faisant、buvant）'],
    ex:[{fr:'Je me suis blessé en tombant.', zh:'我跌倒受了傷。'}] },
 ]},

 { n:'6-6', name:'si 條件句', fr:'Les hypothèses avec si', items:[
  { n:'6-6-1', lvl:'B1', name:'三式總表', fr:'si + trois temps',
    brief:'現實→présent+futur；假設→imparfait+cond.；悔恨→PQP+cond.passé',
    pts:['①Si tu viens, on mangera ensemble（真可能）','②Si tu venais, on mangerait（現在的假設）','③Si tu étais venu, on aurait mangé（過去的悔恨）','⚠️ si 後面永遠不放 futur/conditionnel'],
    ex:[{fr:"S'il pleut demain, je resterai chez moi.", zh:'明天下雨我就待在家。'}] },
 ]},

 { n:'6-7', name:'義務與建議', fr:'Obligation et conseil', items:[
  { n:'6-7-1', lvl:'A2', name:'il faut vs devoir', fr:'il faut / devoir',
    brief:'一般義務（假主詞）vs 個人義務（欠）',
    pts:['il faut + inf：不指定誰的必須','devoir：dois/doit/devons——你「欠」這個動作','il faut que + 虛擬式＝指定對象版（B1，見 6-3-1）'],
    ex:[{fr:'Il faut boire de l\'eau. / Je dois partir.', zh:'該喝水。／我得走了。'}],
    topics:['ilfaut-devoir'], gram:'conseils' },
  { n:'6-7-2', lvl:'A2', name:'給建議句組', fr:'donner des conseils',
    brief:'conseiller de / tu peux / tu devrais 三段軟硬度',
    pts:['Je te conseille de + inf','Tu peux + inf（軟）→ Tu devrais + inf（中）→ Il faut + inf（硬）'],
    ex:[{fr:'Je te conseille de faire du sport.', zh:'我建議你運動。'}],
    topics:['giving-advice'], gram:'conseils' },
  { n:'6-7-3', lvl:'A2', name:'公告體：禁止與請求', fr:'Défense de / Merci de',
    brief:'名詞開頭的告示語氣',
    pts:['Défense de + inf（禁止…）、Interdit de + inf','Merci de + inf（請…，禮貌指令）'],
    ex:[{fr:'Défense de fumer.', zh:'禁止吸菸。'}],
    topics:['interdiction-demande'], gram:'conseils' },
 ]},
]},

// ═══ 第 7 章 句型 ═══════════════════════════════════════════
{ n:'7', name:'句型', fr:'Les structures de phrase', sections:[

 { n:'7-1', name:'問句', fr:'L\'interrogation', items:[
  { n:'7-1-1', lvl:'A1', name:'問句三式', fr:'trois registres',
    brief:'語調（口語）/ est-ce que（萬用）/ 倒裝（書面）',
    pts:['Tu viens ? / Est-ce que tu viens ? / Viens-tu ?','est-ce que＝問句支架，後面語序完全不動','倒裝母音相撞加t：Va-t-il ?'],
    ex:[{fr:'Est-ce que vous parlez français ?', zh:'您說法語嗎？'}], gram:'questions' },
  { n:'7-1-2', lvl:'A1', name:'疑問詞', fr:'mots interrogatifs',
    brief:'qui/que/où/quand/comment/combien/pourquoi',
    pts:['口語常後置：Tu habites où ?','pourquoi 回答用 parce que'],
    ex:[{fr:'Tu pars quand ?', zh:'你何時走？'}],
    topics:['question-words'], gram:'questions' },
  { n:'7-1-3', lvl:'A1', name:'quel 的配合', fr:'quel / quelle / quels / quelles',
    brief:'quel 是形容詞，跟著名詞穿制服',
    pts:['quel âge、quelle ville、quels artistes、quelles langues','搭 être：Quelle est la date ?'],
    ex:[{fr:'Quelles langues tu parles ?', zh:'你說哪些語言？'}], gram:'questions' },
  { n:'7-1-4', lvl:'B1', name:'qu\'est-ce qui / que', fr:'sujet ou objet ?',
    brief:'「什麼」當主詞還是受詞的分岔',
    pts:['Qu\'est-ce qui se passe ?（什麼＝主詞）','Qu\'est-ce que tu fais ?（什麼＝受詞）','尾字 qui/que 跟關係代名詞同一套主受格邏輯（見 3-5）'],
    ex:[{fr:"Qu'est-ce qui ne va pas ?", zh:'哪裡不對勁？'}] },
 ]},

 { n:'7-2', name:'否定', fr:'La négation', topics:['negation'], items:[
  { n:'7-2-1', lvl:'A1', name:'ne … pas', fr:'négation de base',
    brief:'兩片麵包夾住變位動詞',
    pts:['Je ne comprends pas','母音前 n\'：Je n\'aime pas','複合時態夾助動詞：Je n\'ai pas fini'],
    ex:[{fr:'Elle ne travaille pas le lundi.', zh:'她週一不上班。'}], gram:'negation' },
  { n:'7-2-2', lvl:'A2', name:'換尾巴家族', fr:'jamais / plus / rien / personne',
    brief:'尾巴原本都是名詞（一步/一人/一物），搶走了否定意義',
    pts:['ne…jamais（從不）、ne…plus（不再）、ne…rien（沒東西）、ne…personne（沒人）','rien/personne 可當主詞：Personne ne sait','⚠️ plus 否定時 s 不發音（發音就變「更多」）'],
    ex:[{fr:'Je ne connais personne à Paris.', zh:'我在巴黎誰都不認識。'}], gram:'negation' },
  { n:'7-2-3', lvl:'A2', name:'否定後冠詞變 de', fr:'pas de',
    brief:'數量歸零 → de',
    pts:['du pain → pas de pain、des amis → pas d\'amis','定冠詞不變：Je n\'aime pas le café（喜好談的是整類）'],
    ex:[{fr:'Il n\'y a plus de dessert.', zh:'甜點沒了。'}],
    vs:[{n:'1-3-5', note:'跟量詞變de是同一條'}] },
  { n:'7-2-4', lvl:'B1', name:'ne … que（只有）', fr:'restriction',
    brief:'不是否定，是限縮——「除了…之外都不」',
    pts:['Je n\'ai que dix euros（我只有十歐）','que 站在被限縮的東西前面','＝seulement 的文法版'],
    ex:[{fr:'Elle ne boit que de l\'eau.', zh:'她只喝水。'}] },
  { n:'7-2-5', lvl:'B1', name:'口語掉 ne', fr:'chute du ne',
    brief:'日常口語 ne 常消失——聽力要能認出來',
    pts:['Je sais pas（=Je ne sais pas）、C\'est pas grave','聽力放寬、寫作絕不省'],
    ex:[{fr:"J'ai pas le temps.", zh:'我沒時間。（口語）'}] },
 ]},

 { n:'7-3', name:'c\'est 與 il est', fr:'c\'est / il est', items:[
  { n:'7-3-1', lvl:'A2', name:'分界線', fr:'c\'est + nom / il est + adj',
    brief:'c\'est 端出一個東西；il est 描述屬性',
    pts:['c\'est + 冠詞 + 名詞：C\'est une ville française','il est + 形容詞/裸職業：Il est grenoblois、Elle est médecin','評論整件事用 c\'est：C\'est important'],
    ex:[{fr:"C'est un bon prof. / Il est prof.", zh:'他是位好老師。／他是老師。'}],
    topics:['cest-il-est'], gram:'etre-avoir' },
 ]},

 { n:'7-4', name:'強調句', fr:'La mise en relief', items:[
  { n:'7-4-1', lvl:'B1', name:'c\'est … qui / que', fr:'phrase clivée',
    brief:'把聚光燈打在句子某一塊',
    pts:["C'est moi qui ai payé（是我付的——動詞跟真主詞配合）","C'est demain que je pars（強調時間）"],
    ex:[{fr:"C'est lui qui a raison.", zh:'是他對。'}] },
 ]},

 { n:'7-5', name:'感嘆句', fr:'L\'exclamation', items:[
  { n:'7-5-1', lvl:'B1', name:'Quel … ! / Comme … !', fr:'exclamatives',
    brief:'quel 感嘆配合名詞；comme/qu\'est-ce que 感嘆整句',
    pts:['Quelle bonne idée !（不加冠詞）','Comme c\'est beau ! / Qu\'est-ce que c\'est bon !'],
    ex:[{fr:'Quel beau temps !', zh:'天氣真好！'}] },
 ]},

 { n:'7-6', name:'間接引語', fr:'Le discours indirect', items:[
  { n:'7-6-1', lvl:'B2', name:'轉述的變形', fr:'discours rapporté',
    brief:'que 接進來：代名詞換、時態退位、問句改 si/ce que',
    pts:['Il dit : « Je viens » → Il dit qu\'il vient','主句過去→時態退位（見 5-8-1）','是否問句→si：Il demande si tu viens','qu\'est-ce que→ce que：Il demande ce que tu fais'],
    ex:[{fr:"Elle m'a demandé si j'étais libre.", zh:'她問我有沒有空。'}] },
 ]},
]},

// ═══ 第 8 章 介係詞與連接詞 ══════════════════════════════════
{ n:'8', name:'介係詞與連接詞', fr:'Prépositions et connecteurs', sections:[

 { n:'8-1', name:'地點介係詞', fr:'Prépositions de lieu', items:[
  { n:'8-1-1', lvl:'A1', name:'國家與城市', fr:'en / au / aux / à',
    brief:'同一次縮合的不同下場：en陰、au陽、aux複、à城市',
    pts:['en France（陰）、au Canada（陽）、aux États-Unis（複）、à Taipei（城市/島）','來自：de France、du Canada、des États-Unis、de Taïwan','字尾 -e 多陰性'],
    ex:[{fr:'Je vais en France, il vit au Japon.', zh:'我去法國，他住日本。'}],
    exc:['le Mexique 陽性（-e卻陽）→ au Mexique'],
    topics:['preposition-country'], gram:'prepositions' },
  { n:'8-1-2', lvl:'A1', name:'場所與 chez', fr:'à la / au / chez',
    brief:'地方用 à+縮合；「人的地盤」用 chez',
    pts:['à la boucherie、au marché、aux caisses','chez + 人/職業：chez le poissonnier、chez moi、chez le médecin'],
    ex:[{fr:'Je vais chez le coiffeur puis au supermarché.', zh:'我先去理髮店再去超市。'}],
    topics:['preposition-place-transport'], gram:'prepositions' },
  { n:'8-1-3', lvl:'A2', name:'方位詞組', fr:'localisation',
    brief:'de 家族的方位套件',
    pts:['à droite de / à gauche de / à côté de / en face de / près de / loin de','de+le 照縮：en face du canapé','entre A et B（之間）、sur/sous/dans/devant/derrière'],
    ex:[{fr:'La gare est loin de chez moi.', zh:'車站離我家很遠。'}],
    topics:['prepositions-lieu2'], gram:'prepositions' },
 ]},

 { n:'8-2', name:'交通介係詞', fr:'Transports', items:[
  { n:'8-2-1', lvl:'A1', name:'en / à + 交通工具', fr:'en bus / à pied',
    brief:'進得去的用 en，跨上去或步行用 à',
    pts:['en bus/métro/train/voiture/avion','à pied、à vélo、à moto'],
    ex:[{fr:"Je vais à l'école en bus.", zh:'我搭公車上學。'}],
    vs:[{n:'3-4-3', note:'en 另有代名詞身分——同形不同職'}] },
 ]},

 { n:'8-3', name:'de 與 à 的多重身分', fr:'de / à polyvalents', items:[
  { n:'8-3-1', lvl:'B1', name:'de 的身分清單', fr:'les emplois de « de »',
    brief:'所屬/來源/量詞後/否定後/形容詞前——五張臉',
    pts:['所屬：le livre de Paul','來源：venir de France','量詞後與否定後（見 1-3-5）','de+inf 接補語：content de te voir'],
    ex:[{fr:'le vélo de mon frère', zh:'我哥的腳踏車'}] },
  { n:'8-3-2', lvl:'B1', name:'à 的身分清單', fr:'les emplois de « à »',
    brief:'方向/位置/對象/用途/特徵',
    pts:['方向與位置：aller à Paris、être à la maison','間接受詞的橋：parler à、donner à（→lui/leur，見 3-3-2）','用途：une machine à laver；特徵：la fille aux yeux bleus'],
    ex:[{fr:'un verre à vin', zh:'酒杯（裝酒用的杯）'}] },
  { n:'8-3-3', lvl:'B2', name:'動詞的介係詞搭配', fr:'verbe + à / de + inf',
    brief:'動詞接原形要不要橋、用哪座橋——只能整組記',
    pts:['直通：vouloir/pouvoir/aimer + inf','à橋：commencer à、réussir à、apprendre à','de橋：essayer de、décider de、finir de、oublier de'],
    ex:[{fr:"J'apprends à conduire. / J'essaie de comprendre.", zh:'我在學開車。／我試著理解。'}] },
 ]},

 { n:'8-4', name:'連接詞', fr:'Les connecteurs', items:[
  { n:'8-4-1', lvl:'A1', name:'基礎連接詞', fr:'et / mais / ou / donc / car',
    brief:'並列句的五個基本零件',
    pts:['et（和）mais（但）ou（或）donc（所以）car（因為，書面）'],
    ex:[{fr:'Il est tard, donc je pars.', zh:'很晚了，所以我走了。'}] },
  { n:'8-4-2', lvl:'A2', name:'因果：parce que / pour', fr:'cause et but',
    brief:'parce que+子句講原因；pour+原形講目的',
    pts:['Je reste parce que je suis fatigué（原因）','Je pars pour travailler（目的）','pour ou contre + 名詞：表態句型（télétravail 課）'],
    ex:[{fr:'Pourquoi ? — Parce que !', zh:'為什麼？——就是這樣！'}],
    topics:['connectors-pour-parceque'], gram:'opinions' },
  { n:'8-4-3', lvl:'B1', name:'論述連接詞', fr:'connecteurs du discours',
    brief:'寫作口說的骨架詞：先後/對比/讓步/結論',
    pts:['順序：d\'abord → ensuite/puis → enfin','對比：cependant、pourtant、par contre','讓步：bien que（+虛擬）、malgré + 名詞','結論：par conséquent、en effet（佐證）'],
    ex:[{fr:"D'abord je lis, ensuite je réponds.", zh:'我先讀再回答。'}] },
 ]},
]},

// ═══ 第 9 章 副詞與時間表達 ══════════════════════════════════
{ n:'9', name:'副詞與時間', fr:'Adverbes et expressions de temps', sections:[

 { n:'9-1', name:'頻率', fr:'La fréquence', items:[
  { n:'9-1-1', lvl:'A1', name:'頻率光譜', fr:'toujours → jamais',
    brief:'從總是到從不的一條刻度尺',
    pts:['toujours > souvent > parfois/quelquefois > rarement > jamais','搭配週期：tous les jours、le lundi（每週一）、une fois par semaine','位置：變位動詞後（Je vais souvent au parc）'],
    ex:[{fr:'Il y va toujours.', zh:'他總是去。'}],
    topics:['frequency-adverbs'], gram:'negation' },
 ]},

 { n:'9-2', name:'強度與程度', fr:'L\'intensité', items:[
  { n:'9-2-1', lvl:'A2', name:'強度光譜', fr:'un peu → trop',
    brief:'un peu < assez < très/beaucoup < trop（過頭）',
    pts:['très + 形容詞/副詞：très grand','beaucoup + 動詞後：Je mange beaucoup','trop 自帶負評：Il travaille trop','量化名詞全部 +de：trop de sel'],
    ex:[{fr:'C\'est assez bien mais trop cher.', zh:'還不錯但太貴。'}],
    topics:['intensite'], gram:'negation' },
 ]},

 { n:'9-3', name:'副詞構詞', fr:'Formation des adverbes', items:[
  { n:'9-3-1', lvl:'B1', name:'-ment 副詞', fr:'adverbes en -ment',
    brief:'陰性形容詞＋ment（≈英文-ly）',
    pts:['lente→lentement、heureuse→heureusement','-ant/-ent 結尾變 -amment/-emment：récent→récemment','⚠️ bien/mal/vite 是獨立副詞不加 -ment'],
    ex:[{fr:'Parlez lentement, s\'il vous plaît.', zh:'請說慢一點。'}] },
 ]},

 { n:'9-4', name:'時間定位', fr:'Situer dans le temps', items:[
  { n:'9-4-1', lvl:'A2', name:'durée 四天王', fr:'pendant / depuis / il y a / à',
    brief:'問自己：括號閉合了沒',
    pts:['pendant＝閉合括號：J\'ai travaillé pendant trois ans','depuis＝開口括號連著現在（配présent！）：J\'habite ici depuis deux ans','il y a＝往回量到一個點：il y a dix jours','longtemps/toujours 當副詞直接放動詞後'],
    ex:[{fr:'Ils ont déménagé il y a dix jours.', zh:'他們十天前搬家。'}],
    topics:['duree'], gram:'duree-temps',
    vs:[{n:'4-5-1', note:'il y a 的另一個身分是「有」'}] },
  { n:'9-4-2', lvl:'A2', name:'à + 年紀 / 時刻', fr:'à 2 ans / à 8h',
    brief:'à 釘住一個時間點',
    pts:['à deux ans（兩歲時）、à 8 heures（八點）','de…à…：de 9h à 17h'],
    ex:[{fr:'Je suis arrivée en France à deux ans.', zh:'我兩歲時到法國。'}] },
  { n:'9-4-3', lvl:'A1', name:'日期與時刻', fr:'la date et l\'heure',
    brief:'le+數字+月份；heure 是陰性',
    pts:['le 4 juin（1號用 premier）','Il est une heure et demie（heure陰性→une、demie+e）','en janvier / au printemps（春天例外用au）、en été/automne/hiver'],
    ex:[{fr:"Mon anniversaire, c'est le 4 juin.", zh:'我生日是6月4日。'}],
    topics:['numbers-dates-heure'] },
  { n:'9-4-4', lvl:'A2', name:'相對時間詞', fr:'hier / demain / prochain / dernier',
    brief:'以「今天」為原點的座標詞',
    pts:['hier / aujourd\'hui / demain；avant-hier / après-demain','la semaine prochaine / dernière（跟名詞配合）','ce matin、ce soir、ce week-end'],
    ex:[{fr:'La semaine prochaine, nous partons.', zh:'下週我們出發。'}] },
 ]},

 { n:'9-5', name:'副詞位置與 bien/mieux', fr:'Place et cas particuliers', items:[
  { n:'9-5-1', lvl:'B1', name:'副詞的位置', fr:'place de l\'adverbe',
    brief:'短副詞貼動詞；複合時態夾中間',
    pts:['現在式：動詞後（Je mange souvent ici）','複合時態短副詞夾中間：J\'ai bien dormi、Il a trop mangé'],
    ex:[{fr:"J'ai déjà fini.", zh:'我已經做完了。'}] },
  { n:'9-5-2', lvl:'B1', name:'bien / mieux vs bon / meilleur', fr:'bien ou bon ?',
    brief:'副詞線（bien→mieux）與形容詞線（bon→meilleur）不互通',
    pts:['bon/meilleur 修飾名詞：un meilleur café','bien/mieux 修飾動詞：Il chante mieux que moi','C\'est bon（好吃/好了）vs C\'est bien（做得好/不錯）'],
    ex:[{fr:'Ça va mieux.', zh:'（狀況）好多了。'}],
    vs:[{n:'2-3-2', note:'meilleur 那條是形容詞線'}] },
 ]},
]},
];

// 合併兩段
CODEX_PART2.forEach(ch => CODEX.push(ch));

/* ── 術語白話字典（點擊小標籤彈出，全庫共用）────────────────── */
const CODEX_TERMS = {
  '部分冠詞': '「一些」的冠詞——不可數的東西取一部分：du pain＝一些麵包（不是整條）',
  '定冠詞': 'le/la/les——特定的、或泛指一整類（J\'aime le café＝咖啡這種東西）',
  '不定冠詞': 'un/une/des——第一次提到、隨便哪一個（un chien＝某一隻狗）',
  '縮合': '兩個字被講快黏成一個：de+le→du、à+le→au',
  '變位': '動詞跟著主詞換衣服：je parle / nous parlons——同一個動詞六種樣子',
  '原形': '動詞的字典形（沒穿衣服）：parler、finir——兩個動詞連用時第二個永遠原形',
  '助動詞': '幫忙組時態的 avoir/être：J\'ai mangé 的 ai 只是幫手，真正的動作是 mangé',
  '過去分詞': '動詞的「完成品」形：mangé、fini、vendu——複合過去式的第二塊零件',
  '反身動詞': '動作回到自己身上的動詞：se laver 洗自己＝洗澡（多了 me/te/se）',
  'COD': '動詞「直接吃到」的對象：「我看到他」的「他」——變代名詞放動詞前（Je le vois）',
  'COI': '動詞經過 à 才碰到的人：「我打電話給他」→ Je lui téléphone（不分男女）',
  '重讀代名詞': '有重音的加強版代名詞 moi/toi/lui/eux——介詞後、強調、單獨回答時用',
  '關係代名詞': '把兩句黏成一句的鉤子：l\'homme qui parle＝「正在說話的」那個人',
  '性數配合': '形容詞/分詞跟名詞穿同套制服：陰性+e、複數+s（grande, grands）',
  '直陳式': '預設模式——陳述事實用的動詞形（你目前學的幾乎都是它）',
  '虛擬式': '主觀模式——表達想要/情緒/懷疑時，que 後面動詞換的形（B1 才學）',
  '條件式': '假設與禮貌模式：je voudrais＝「我想要」的軟化版',
  '命令式': '砍掉主詞直接命令：Mange !＝吃！',
  '無人稱': 'il 是假主詞、沒有人在那裡：il pleut（下雨）、il faut（必須）',
  '介係詞': '名詞前的小方向詞：à/de/en/chez——法文的膠水',
  '先行詞': '關係子句修飾的那個名詞：le livre que je lis 裡的 le livre',
};

/* ── 索引與定位 helpers ───────────────────────────────────── */

// 攤平索引：座標→節點、topic→座標
const CODEX_BY_N = {};
const CODEX_TOPIC_MAP = {};
CODEX.forEach(ch => {
  CODEX_BY_N[ch.n] = ch;
  (ch.sections || []).forEach(sec => {
    CODEX_BY_N[sec.n] = sec;
    (sec.topics || []).forEach(t => { CODEX_TOPIC_MAP[t] = sec.n; });
    (sec.items || []).forEach(it => {
      CODEX_BY_N[it.n] = it;
      (it.topics || []).forEach(t => { CODEX_TOPIC_MAP[t] = it.n; });
    });
  });
});

// quiz topic → {num, name}；詞彙類 topic 沒有座標回傳 null
function codexLocate(topic) {
  const n = CODEX_TOPIC_MAP[topic];
  if (!n) return null;
  const node = CODEX_BY_N[n];
  return { num: n, name: node.name };
}

