// 常用句庫（中翻法造句練習用）— sentence_drill.html 專用
// 跟 chunks.js 不同：這裡只放「完整、真的常用、值得先背」的句子，用意在練造句反射，
// 不是自動抽取全部筆記內容。每次 Owen 給新課筆記/逐字稿時，人工從中挑選補進來。
// 格式跟 chunks.js 對齊：{ id, lesson, fr, zh, note }
const SENTENCES = [
  // 第1課
  { id: 'S_L1_1', lesson: 1, fr: 'Ça va ?', zh: '你好嗎？', note: '' },
  { id: 'S_L1_2', lesson: 1, fr: 'Oui, ça va, merci. Et toi ?', zh: '好，謝謝，你呢？', note: '' },
  { id: 'S_L1_3', lesson: 1, fr: 'Vous pouvez répéter, s\'il vous plaît ?', zh: '可以再說一次嗎？（正式）', note: '' },
  { id: 'S_L1_4', lesson: 1, fr: 'Excusez-moi, je suis en retard.', zh: '對不起，我遲到了。', note: '' },
  { id: 'S_L1_5', lesson: 1, fr: 'Je suis taïwanais.', zh: '我是台灣人。（男生；女生說 taïwanaise）', note: '' },
  { id: 'S_L1_6', lesson: 1, fr: 'Mon anniversaire, c\'est le 4 juin.', zh: '我的生日是6月4日。', note: '' },

  // 第2課
  { id: 'S_L2_1', lesson: 2, fr: 'Tu habites dans quelle ville ?', zh: '你住在哪個城市？', note: '' },
  { id: 'S_L2_2', lesson: 2, fr: 'Tu parles quelle langue ?', zh: '你說什麼語言？', note: '' },
  { id: 'S_L2_3', lesson: 2, fr: 'Pourquoi tu aimes le sport ?', zh: '你為什麼喜歡運動？', note: '' },
  { id: 'S_L2_4', lesson: 2, fr: 'Parce que c\'est sympa !', zh: '因為很好玩！', note: '' },
  { id: 'S_L2_5', lesson: 2, fr: 'Combien de langues tu parles ?', zh: '你說幾種語言？', note: '' },
  { id: 'S_L2_6', lesson: 2, fr: 'Je parle chinois, taïwanais et anglais.', zh: '我說中文、台語和英文。', note: '' },
  { id: 'S_L2_7', lesson: 2, fr: 'Je m\'appelle Emma, je suis brésilienne et j\'aime le cinéma.', zh: '我叫 Emma，我是巴西人，我喜歡電影。', note: '自我介紹萬用模板' },

  // 第3課
  { id: 'S_L3_1', lesson: 3, fr: 'Je n\'aime pas la danse.', zh: '我不喜歡跳舞。', note: '' },
  { id: 'S_L3_2', lesson: 3, fr: 'Je ne suis pas fort en natation.', zh: '我游泳不太行。', note: '' },
  { id: 'S_L3_3', lesson: 3, fr: 'J\'ai un oncle. Il a 48 ans.', zh: '我有一個叔叔，他48歲。', note: '' },
  { id: 'S_L3_4', lesson: 3, fr: 'Notre fille déteste le sport.', zh: '我們的女兒討厭運動。', note: '' },
  { id: 'S_L3_5', lesson: 3, fr: 'Je prépare la liste des invités pour notre mariage.', zh: '我在準備我們婚禮的賓客名單。', note: '' },
  { id: 'S_L3_6', lesson: 3, fr: 'Son petit-fils a deux mois.', zh: '他的孫子兩個月大。', note: '' },

  // 第4課
  { id: 'S_L4_1', lesson: 4, fr: 'Je voudrais une baguette, s\'il vous plaît.', zh: '我想要一條法棍，謝謝。', note: 'voudrais 比 je veux 有禮貌' },
  { id: 'S_L4_2', lesson: 4, fr: 'Combien coûte une baguette ?', zh: '一條法棍多少錢？', note: '' },
  { id: 'S_L4_3', lesson: 4, fr: 'Elle coûte 1 euro.', zh: '它賣一歐元。', note: '' },

  // 第5課
  { id: 'S_L5_1', lesson: 5, fr: 'Je mange du pain avec du beurre.', zh: '我吃麵包配奶油。', note: '' },
  { id: 'S_L5_2', lesson: 5, fr: 'Je ne mange pas de viande.', zh: '我不吃肉。', note: '' },
  { id: 'S_L5_3', lesson: 5, fr: 'Il n\'y a pas de dessert aujourd\'hui.', zh: '今天沒有甜點。', note: '' },
  { id: 'S_L5_4', lesson: 5, fr: 'Quel est le plat du jour ?', zh: '今日主菜是什麼？', note: '' },
  { id: 'S_L5_5', lesson: 5, fr: 'Pour moi, la blanquette de veau.', zh: '我要白汁小牛肉。（口語點餐）', note: '' },
  { id: 'S_L5_6', lesson: 5, fr: 'Une carafe d\'eau, s\'il vous plaît.', zh: '請給我一壺水。（免費）', note: '' },
  { id: 'S_L5_7', lesson: 5, fr: 'Qu\'est-ce que tu fais ?', zh: '你在做什麼？', note: '' },

  // 第6課
  { id: 'S_L6_1', lesson: 6, fr: 'Il n\'est pas loin.', zh: '不遠。', note: '' },
  { id: 'S_L6_2', lesson: 6, fr: 'Prenez le métro !', zh: '搭地鐵！（命令式）', note: '' },
  { id: 'S_L6_3', lesson: 6, fr: 'Montez dans le bus.', zh: '上公車。', note: '' },
  { id: 'S_L6_4', lesson: 6, fr: 'Descendez à l\'arrêt République.', zh: '在共和站下車。', note: '' },
  { id: 'S_L6_5', lesson: 6, fr: 'N\'achetez pas de tickets.', zh: '不要買票。', note: '' },
  { id: 'S_L6_6', lesson: 6, fr: 'Ayez confiance !', zh: '要有信心！', note: '' },

  // 第7課
  { id: 'S_L7_1', lesson: 7, fr: 'Pour aller au travail, je prends ma voiture.', zh: '去上班我開車。', note: '' },
  { id: 'S_L7_2', lesson: 7, fr: 'Ma famille n\'utilise que les transports en commun.', zh: '我家只用大眾交通。', note: '' },
  { id: 'S_L7_3', lesson: 7, fr: 'Ne prends pas la voiture.', zh: '不要開車。（否定命令）', note: '' },
  { id: 'S_L7_4', lesson: 7, fr: 'La semaine, j\'utilise les transports en commun.', zh: '工作日我搭大眾交通。', note: '' },
  { id: 'S_L7_5', lesson: 7, fr: 'Le week-end, je prends ma voiture.', zh: '週末我開車。', note: '' },
  { id: 'S_L7_6', lesson: 7, fr: 'Tu fais quelle taille ?', zh: '你穿幾號？', note: '' },
  { id: 'S_L7_7', lesson: 7, fr: 'Il me plaît.', zh: '我喜歡它。（plaire，主詞是物）', note: '' },

  // 第8課
  { id: 'S_L8_1', lesson: 8, fr: 'Il fait beau.', zh: '天氣好。', note: '' },
  { id: 'S_L8_2', lesson: 8, fr: 'Il fait mauvais.', zh: '天氣不好。', note: '' },
  { id: 'S_L8_3', lesson: 8, fr: 'Il pleut.', zh: '下雨。', note: '' },
  { id: 'S_L8_4', lesson: 8, fr: 'Il fait 30 degrés.', zh: '氣溫30度。', note: '' },
  { id: 'S_L8_5', lesson: 8, fr: 'Demain soir, je vais finir la robe.', zh: '明晚我要把洋裝做完。', note: '' },
  { id: 'S_L8_6', lesson: 8, fr: 'La semaine prochaine, nous allons tricoter un pull.', zh: '下星期我們要織一件毛衣。', note: '' },
  { id: 'S_L8_7', lesson: 8, fr: 'Mes filles vont être contentes.', zh: '我女兒們會很開心。', note: '' },
  { id: 'S_L8_8', lesson: 8, fr: 'Ça sert à écouter de la musique.', zh: '這是用來聽音樂的。', note: '' },

  // 第9課
  { id: 'S_L9_1', lesson: 9, fr: 'On ne sait pas comment il s\'appelle.', zh: '沒人知道他叫什麼名字。', note: 'on = 泛指' },
  { id: 'S_L9_2', lesson: 9, fr: 'On va au cinéma ce soir ?', zh: '我們今晚要去看電影嗎？', note: '' },
  { id: 'S_L9_3', lesson: 9, fr: 'Je ne veux pas.', zh: '我不想。', note: '' },
  { id: 'S_L9_4', lesson: 9, fr: 'Je n\'ai pas envie.', zh: '我不想做。', note: '' },

  // 第10課
  { id: 'S_L10_1', lesson: 10, fr: 'Qu\'est-ce que tu viens de dire ?', zh: '你剛說什麼？', note: '' },
  { id: 'S_L10_2', lesson: 10, fr: 'Elle vient de commencer, donc elle est encore là.', zh: '她剛開始，所以她還在。', note: '' },

  // 第11課
  { id: 'S_L11_1', lesson: 11, fr: 'Vous avez trouvé des meubles ?', zh: '你們找到家具了嗎？', note: '' },
  { id: 'S_L11_2', lesson: 11, fr: 'On n\'a pas trouvé de lit, mais on a trouvé deux fauteuils.', zh: '我們沒找到床，但找到兩張扶手椅。', note: '' },
  { id: 'S_L11_3', lesson: 11, fr: 'Ils ont déménagé il y a dix jours.', zh: '他們十天前搬家了。', note: '' },
  { id: 'S_L11_4', lesson: 11, fr: 'Tu connais Marc et Lydia ?', zh: '你認識 Marc 和 Lydia 嗎？', note: '' },
  { id: 'S_L11_5', lesson: 11, fr: 'J\'adore ce quartier, je le trouve très agréable.', zh: '我很愛這個街區，我覺得它很宜人。', note: '' },
  { id: 'S_L11_6', lesson: 11, fr: 'Tu as vu Sophie ?', zh: '你有看到 Sophie 嗎？', note: '' },

  // 第12課
  { id: 'S_L12_1', lesson: 12, fr: 'Qu\'est-ce qui vous arrive ?', zh: '你怎麼了？', note: '' },
  { id: 'S_L12_2', lesson: 12, fr: 'Vous vous sentez comment ?', zh: '你感覺怎麼樣？', note: '' },
  { id: 'S_L12_3', lesson: 12, fr: 'J\'ai mal à la tête.', zh: '我頭痛。', note: '' },
  { id: 'S_L12_4', lesson: 12, fr: 'Je suis malade.', zh: '我生病了。', note: '' },
  { id: 'S_L12_5', lesson: 12, fr: 'Je suis fatigué.', zh: '我很累。', note: '' },
  { id: 'S_L12_6', lesson: 12, fr: 'Je suis en pleine forme.', zh: '我精力充沛。', note: '' },
  { id: 'S_L12_7', lesson: 12, fr: 'Je suis allé chez le médecin.', zh: '我去看醫生了。', note: '' },
  { id: 'S_L12_8', lesson: 12, fr: 'Je vais prendre rendez-vous chez un spécialiste.', zh: '我要跟專科醫生預約。', note: '' },

  // 第13課
  { id: 'S_L13_1', lesson: 13, fr: 'Il faut apporter sa serviette de bain.', zh: '要帶浴巾。', note: '' },
  { id: 'S_L13_2', lesson: 13, fr: 'Il ne faut pas utiliser son téléphone portable.', zh: '不可以用手機。', note: '' },
  { id: 'S_L13_3', lesson: 13, fr: 'Il faut nettoyer les appareils après l\'utilisation.', zh: '用完要清潔器材。', note: '' },
  { id: 'S_L13_4', lesson: 13, fr: 'Bougez plus !', zh: '多動！', note: '' },
  { id: 'S_L13_5', lesson: 13, fr: 'Pour votre santé, bougez plus !', zh: '為了您的健康，多動！', note: '' },
  { id: 'S_L13_6', lesson: 13, fr: 'Il faut boire 2L d\'eau.', zh: '要喝2公升的水。', note: '' },
  { id: 'S_L13_7', lesson: 13, fr: 'Vous aimez les aliments salés ?', zh: '你喜歡鹹的食物嗎？', note: '' },
  { id: 'S_L13_8', lesson: 13, fr: 'On a oublié le parasol !', zh: '我們忘了帶陽傘！', note: '' },

  // 第14課
  { id: 'S_L14_1', lesson: 14, fr: 'Est-ce que le petit déjeuner est compris ?', zh: '早餐有含嗎？', note: '' },
  { id: 'S_L14_2', lesson: 14, fr: 'Est-ce que les animaux sont acceptés ?', zh: '可以帶寵物嗎？', note: '' },
  { id: 'S_L14_3', lesson: 14, fr: 'Est-ce qu\'il y a un parking pour les voitures ?', zh: '有停車場嗎？', note: '' },
  { id: 'S_L14_4', lesson: 14, fr: 'J\'arrive le 25 et je pars le 28.', zh: '我25號到、28號走。', note: '' },
  { id: 'S_L14_5', lesson: 14, fr: 'J\'aime le café, mais le thé est meilleur.', zh: '我喜歡咖啡，但茶更好。', note: '' },
  { id: 'S_L14_6', lesson: 14, fr: 'Je ne connais que Monet.', zh: '我只認識莫內。', note: 'ne...que = 只' },
  { id: 'S_L14_7', lesson: 14, fr: 'C\'est à côté de l\'Espagne.', zh: '在西班牙旁邊。', note: '' },
  { id: 'S_L14_8', lesson: 14, fr: 'Je viens de Taïwan.', zh: '我來自台灣。', note: '' },
  { id: 'S_L14_9', lesson: 14, fr: 'Il est rentré de Taïwan.', zh: '他從台灣回來了。', note: '' },
  { id: 'S_L14_10', lesson: 14, fr: 'Elle est arrivée à la plage.', zh: '她到海灘了。', note: '' },

  // 第15課
  { id: 'S_L15_1', lesson: 15, fr: 'Il faisait beau.', zh: '那時天氣好。', note: 'imparfait 描述過去狀態' },
  { id: 'S_L15_2', lesson: 15, fr: 'Il y avait des nuages.', zh: '那時有雲。', note: '' },
  { id: 'S_L15_3', lesson: 15, fr: 'C\'était très intéressant.', zh: '那時很有趣。', note: '' },
  { id: 'S_L15_4', lesson: 15, fr: 'Je suis en vacances chez des amis.', zh: '我在朋友家度假。', note: '' },
  { id: 'S_L15_5', lesson: 15, fr: 'À bientôt !', zh: '再會！', note: '明信片結尾用語' },
  { id: 'S_L15_6', lesson: 15, fr: 'Le droit m\'intéresse.', zh: '法律讓我感興趣。', note: 'COD代名詞 m\'' },
  { id: 'S_L15_7', lesson: 15, fr: 'Je te comprends.', zh: '我懂你。', note: '' },
  { id: 'S_L15_8', lesson: 15, fr: 'Tu m\'aides à faire cet exercice ?', zh: '你可以幫我做這個練習嗎？', note: '' },
  { id: 'S_L15_9', lesson: 15, fr: 'J\'étudie le droit.', zh: '我讀法律系。', note: '' },
  { id: 'S_L15_10', lesson: 15, fr: 'Les cours sont excellents.', zh: '課程很棒。', note: '' },

  // 第16課
  { id: 'S_L16_1', lesson: 16, fr: 'Nous avons toujours le statut étudiant.', zh: '我們現在還保有學生身份。', note: 'toujours + 現在式' },
  { id: 'S_L16_2', lesson: 16, fr: 'Pierre a étudié le droit pendant deux ans, mais maintenant il étudie le commerce.', zh: '皮耶讀了兩年法律，但現在他在讀商業。', note: 'pendant + 明確期間' },
  { id: 'S_L16_3', lesson: 16, fr: 'Je suis dentiste depuis douze ans.', zh: '我當牙醫師已經12年了。', note: 'depuis + 持續到現在' },
  { id: 'S_L16_4', lesson: 16, fr: "C'est un métier que j'adore.", zh: '這是我熱愛的職業。', note: 'que 取代受詞' },
  { id: 'S_L16_5', lesson: 16, fr: 'La France est un pays qui change.', zh: '法國是個一直在變的國家。', note: 'qui 取代主詞' },
  { id: 'S_L16_6', lesson: 16, fr: "J'ai un travail qui est intéressant.", zh: '我的工作很有趣。', note: '' },
  { id: 'S_L16_7', lesson: 16, fr: "J'ai des collègues que j'aime beaucoup.", zh: '我有很喜歡的同事。', note: '' },
  { id: 'S_L16_8', lesson: 16, fr: "Je suis pour le télétravail parce que c'est pratique.", zh: '我贊成遠端工作，因為很方便。', note: 'être pour + parce que' },
  { id: 'S_L16_9', lesson: 16, fr: 'Je travaille beaucoup en ce moment.', zh: '我最近工作很多。', note: 'beaucoup + 動詞' },
  { id: 'S_L16_10', lesson: 16, fr: 'Je suis trop fatigué.', zh: '我太累了。', note: 'trop 帶負面意味' },

  // Extra Français E1（2026-07-17 影集精讀 pipeline 首批：真實口語、全部在已學文法內）
  { id: 'S_EX1_1', lesson: 0, src: 'Extra E1', fr: "Quoi de neuf ?", zh: '有什麼新鮮事？（見面寒暄）', note: '口語超高頻開場' },
  { id: 'S_EX1_2', lesson: 0, src: 'Extra E1', fr: 'Tu veux boire quelque chose ?', zh: '你想喝點什麼嗎？（招待客人）', note: 'vouloir + 原形' },
  { id: 'S_EX1_3', lesson: 0, src: 'Extra E1', fr: "C'est clair ?", zh: '聽清楚了嗎？／明白嗎？（強勢確認）', note: '劇中機翻誤譯成「天氣晴朗」的高頻口語' },
  { id: 'S_EX1_4', lesson: 0, src: 'Extra E1', fr: 'Tu te souviens de moi ?', zh: '你還記得我嗎？', note: 'se souvenir de（反身動詞）' },
  { id: 'S_EX1_5', lesson: 0, src: 'Extra E1', fr: "Je n'en peux plus !", zh: '我再也受不了了！', note: '整塊背，不拆解 en' },
  { id: 'S_EX1_6', lesson: 0, src: 'Extra E1', fr: "Ça m'est égal.", zh: '我無所謂。／隨便。', note: '整塊背' },
  { id: 'S_EX1_7', lesson: 0, src: 'Extra E1', fr: 'Je peux te parler un instant ?', zh: '我可以跟你說句話嗎？', note: 'pouvoir + COD代名詞 te' },
  { id: 'S_EX1_8', lesson: 0, src: 'Extra E1', fr: 'Il faut faire la fête !', zh: '該慶祝一下！', note: 'il faut + 原形' },

  // ── 第17課（A2・passé composé）──
  { id: 'S_L17_1', lesson: 17, fr: "J'ai reçu un message.", zh: '我收到一則訊息。', note: 'recevoir → reçu' },
  { id: 'S_L17_2', lesson: 17, fr: "J'ai obtenu mon diplôme l'année dernière.", zh: '我去年拿到文憑。', note: 'obtenir → obtenu' },
  { id: 'S_L17_3', lesson: 17, fr: 'Ils se sont mariés il y a deux ans.', zh: '他們兩年前結婚了。', note: '反身動詞配 être，分詞+s' },
  { id: 'S_L17_4', lesson: 17, fr: 'Ma fille est née il y a un an.', zh: '我女兒一年前出生。', note: 'naître 配 être+配合；il y a=距今…前' },
  { id: 'S_L17_5', lesson: 17, fr: "Tu as lu le roman ? — Non, je ne l'ai pas lu.", zh: '你讀了那本小說嗎？——沒有，我沒讀。', note: 'COD 代名詞夾在 ne 和 ai 中間' },
  { id: 'S_L17_6', lesson: 17, fr: "J'ai ouvert mon magasin il y a deux ans.", zh: '我兩年前開了我的店。', note: 'ouvrir → ouvert' },
  { id: 'S_L17_7', lesson: 17, fr: 'Je vis à Taïwan depuis cinq ans.', zh: '我住在台灣五年了（還住著）。', note: 'depuis + 現在式' },
  { id: 'S_L17_8', lesson: 17, fr: "J'ai vécu à Taïwan pendant cinq ans.", zh: '我在台灣住過五年（已結束）。', note: 'pendant + passé composé' },
  { id: 'S_L17_9', lesson: 17, fr: 'Je suis mort de rire.', zh: '我笑死了。（MDR）', note: '口語；女生說 morte' },
  { id: 'S_L17_10', lesson: 17, fr: 'Je me lève à six heures.', zh: '我六點起床。（DELF口說高頻）', note: '現在式 je me lève，不是 je me lever' },
  { id: 'S_L18_1', lesson: 18, fr: "J'ai eu un coup de foudre pour elle.", zh: '我對她一見鍾情。', note: 'coup de foudre＝瞬間的一見鍾情' },
  { id: 'S_L18_2', lesson: 18, fr: 'Nous avons fait connaissance en 2018.', zh: '我們2018年認識彼此。', note: 'faire connaissance，不是connaître' },
  { id: 'S_L18_3', lesson: 18, fr: 'Ils se sont mariés il y a trois ans.', zh: '他們三年前結婚了。', note: '反身動詞配être，分詞+s跟主詞配合' },
  { id: 'S_L18_4', lesson: 18, fr: "Elle s'est installée à Lyon l'année dernière.", zh: '她去年在里昂定居下來。', note: "s'installer的passé composé" },
  { id: 'S_L18_5', lesson: 18, fr: 'Je cherche du travail depuis deux mois.', zh: '我找工作已經兩個月了。', note: 'chercher＝找（還沒找到）' },
  { id: 'S_L18_6', lesson: 18, fr: "J'ai obtenu mon diplôme l'année dernière.", zh: '我去年拿到文憑。', note: 'tenir→obtenir同字根' },
  { id: 'S_L18_7', lesson: 18, fr: "Ce n'est pas du tout mon truc.", zh: '這完全不是我的菜。', note: 'mon truc是mon chose的口語替代字' },
  { id: 'S_L18_8', lesson: 18, fr: 'Ma passion, c\'est la cuisine.', zh: '我的熱情所在是烹飪。', note: '強調真心熱愛的固定句型' },
  { id: 'S_L18_9', lesson: 18, fr: 'Je ne connais personne dans cette ville.', zh: '我在這座城市誰都不認識。', note: 'personne當COD放動詞後' },
  { id: 'S_L18_10', lesson: 18, fr: 'Il ne fait plus de sport depuis son accident.', zh: '他自從那次意外後就不再運動了。', note: 'ne...plus＝狀態改變、習慣的終結' },
  { id: 'S_L19_1', lesson: 19, fr: 'Ça te dit ? Tu es libre ce soir ?', zh: '你有興趣嗎？你今晚有空嗎？', note: '邀約常用句組合' },
  { id: 'S_L19_2', lesson: 19, fr: 'On se retrouve chez moi à 19h ?', zh: '我們19點在我家碰面好嗎？', note: 'se retrouver＝碰面、會合' },
  { id: 'S_L19_3', lesson: 19, fr: 'Je m\'excuse, mais je ne peux pas, j\'ai un rendez-vous de travail.', zh: '抱歉，但我不行，我有一個工作會議。', note: '婉拒邀約的完整句' },
  { id: 'S_L19_4', lesson: 19, fr: 'D\'accord, ça marche. À ce soir !', zh: '好，那就這樣說定了。晚點見！', note: 'ça marche＝成交、說定了' },
  { id: 'S_L19_5', lesson: 19, fr: 'Je suis amateur de football, je regarde tous les matchs.', zh: '我對足球很有研究，每場比賽都看。', note: 'être amateur de + 名詞＝真心熱衷' },
  { id: 'S_L19_6', lesson: 19, fr: 'J\'ai fait ma première compétition il y a onze ans.', zh: '我十一年前參加了第一場比賽。', note: 'il y a + 時長＝過去…前' },
  { id: 'S_L19_7', lesson: 19, fr: 'Les places sont en vente depuis hier.', zh: '票昨天開始賣了（現在還在賣）。', note: 'depuis＝持續到現在' },
  { id: 'S_L19_8', lesson: 19, fr: 'J\'ai décidé de participer pour faire de nouvelles expériences.', zh: '我決定參加是為了累積新的經驗。', note: '形容詞放名詞前，des要縮成de' },
  { id: 'S_L19_9', lesson: 19, fr: 'Nous venons de pays différents, mais nous parlons la même langue.', zh: '我們來自不同的國家，但我們說同一種語言。', note: 'la même langue＝相同的語言' },
  { id: 'S_L19_10', lesson: 19, fr: 'J\'ai fait une randonnée à vélo de trois heures.', zh: '我騎了一趟三小時的腳踏車行程。', note: '跟faire du vélo（泛指）對比，une randonnée讓它可數' },
  { id: 'S_L20_1', lesson: 20, fr: 'Je me souviens des confitures que faisait ma grand-mère.', zh: '我記得奶奶做的果醬。', note: 'se souvenir DE＋que關係代名詞＋imparfait，一句吃三個文法點' },
  { id: 'S_L20_2', lesson: 20, fr: 'Quand j\'étais petit, je partais en vacances avec mes parents.', zh: '我小時候會跟父母去度假。', note: 'quand j\'étais petit＝口說寫作萬用開場' },
  { id: 'S_L20_3', lesson: 20, fr: 'À cette époque, j\'habitais à Strasbourg.', zh: '那時候我住在史特拉斯堡。', note: 'à cette époque＝那段時期，配imparfait' },
  { id: 'S_L20_4', lesson: 20, fr: 'Chaque semaine, nous étudiions ensemble.', zh: '我們每週一起讀書。', note: '⚠️雙i：字根étudi-＋字尾-ions' },
  { id: 'S_L20_5', lesson: 20, fr: 'Le soir, on regardait les étoiles.', zh: '晚上我們會看星星。', note: '典型的背景描述→imparfait' },
  { id: 'S_L20_6', lesson: 20, fr: 'Je mangeais beaucoup, mais j\'ai grossi.', zh: '我以前吃很多，但我變胖了。', note: '習慣用imparfait＋單次改變用passé composé，兩時態同句' },
  { id: 'S_L20_7', lesson: 20, fr: 'Ces mots sont gravés dans ma mémoire.', zh: '這些話刻在我的記憶裡。', note: 'gravé dans ma mémoire＝永遠忘不了' },
  { id: 'S_L20_8', lesson: 20, fr: 'Je suis très attaché à cet endroit.', zh: '我很依戀這個地方。', note: 'être attaché à＋地方或人' },
  { id: 'S_L20_9', lesson: 20, fr: 'De temps en temps, on allait voir un spectacle.', zh: '我們偶爾會去看表演。', note: 'de temps en temps＝偶爾，配imparfait講習慣' },
  { id: 'S_L20_10', lesson: 20, fr: 'Ça me replonge dans mon enfance.', zh: '這讓我一下子回到童年。', note: '看到懷舊事物的固定反應句' },
  { id: 'S_L21_1', lesson: 21, fr: 'J\'y vais souvent.', zh: '我常去那裡。', note: 'y＝去/在那裡，夾在主詞和動詞之間' },
  { id: 'S_L21_2', lesson: 21, fr: 'Oui, j\'en reviens à l\'instant.', zh: '對，我剛從那裡回來。', note: 'en＝從那裡（原句是 de la plage）；à l\'instant＝剛剛' },
  { id: 'S_L21_3', lesson: 21, fr: 'Il en est parti à six heures.', zh: '他六點從那裡離開。', note: '⚠️ passé composé 裡 en 放助動詞前面，不是分詞前面' },
  { id: 'S_L21_4', lesson: 21, fr: 'Non, on n\'y a pas dormi.', zh: '不，我們沒有在那裡睡。', note: '否定＋PC 的順序：n\' + y + 助動詞 + pas + 分詞' },
  { id: 'S_L21_5', lesson: 21, fr: 'Je m\'y promène très souvent.', zh: '我很常在那裡散步。', note: '反身動詞＋y：me → m\'，再接 y' },
  { id: 'S_L21_6', lesson: 21, fr: 'Je reviens de Taïwan.', zh: '我剛從台灣回來。', note: '⚠️ revenir de＝去了一趟回來；venir de＝出身自那裡（兩者意思差很多）' },
  { id: 'S_L21_7', lesson: 21, fr: 'J\'ai vu des oiseaux et j\'ai regardé un film.', zh: '我看到一些鳥，而且我看了一部電影。', note: 'voir＝眼睛接收到；regarder＝刻意專注看（電影一定用 regarder）' },
  { id: 'S_L21_8', lesson: 21, fr: 'C\'est un souvenir d\'enfance inoubliable.', zh: '這是一段難忘的童年回憶。', note: 'souvenir de＋種類；inoubliable 好壞皆可用' },
  { id: 'S_L21_9', lesson: 21, fr: 'Ce paysage m\'a marqué à jamais.', zh: '這片風景讓我一輩子難忘。', note: 'marquer qqn＝在心裡刻下印記（不是「標記」）；à jamais＝永遠' },
  { id: 'S_L21_10', lesson: 21, fr: 'Que demander de plus ?', zh: '夫復何求？', note: '已經很完美時的固定說法，口說很加分' },
  { id: 'S_L22_1', lesson: 22, fr: 'Quel temps fait-il aujourd\'hui ?', zh: '今天天氣怎麼樣？', note: '問天氣的標準句；回答用 Il fait…' },
  { id: 'S_L22_2', lesson: 22, fr: 'Il fait très chaud, c\'est la canicule.', zh: '天氣非常熱，是熱浪。', note: 'canicule＝太熱＋持續太久，不是單純的 chaleur' },
  { id: 'S_L22_3', lesson: 22, fr: 'La météo annonce des orages ce week-end.', zh: '氣象預報說這個週末有雷雨。', note: 'annoncer＝預報；orage＝整場雷雨（不是雷聲 tonnerre）' },
  { id: 'S_L22_4', lesson: 22, fr: 'On a parlé de la pluie et du beau temps.', zh: '我們就隨便閒聊。', note: '慣用語，不是真的在講天氣——跟中文「聊天氣」同樣的社交功能' },
  { id: 'S_L22_5', lesson: 22, fr: 'Nous avons mangé dans un bon restaurant français.', zh: '我們在一家好的法式餐廳吃飯。', note: '⭐ 短形容詞在前、國籍在後，名詞夾中間' },
  { id: 'S_L22_6', lesson: 22, fr: 'J\'ai acheté de jolies espadrilles.', zh: '我買了一些漂亮的草編鞋。', note: '⭐ 形容詞放複數名詞前 → des 縮成 de' },
  { id: 'S_L22_7', lesson: 22, fr: 'Nous avons vu de gros bateaux blancs.', zh: '我們看到一些白色大船。', note: '⭐ gros 在前（des→de）、blancs（顏色）在後配陽性複數' },
  { id: 'S_L22_8', lesson: 22, fr: 'J\'utilise mon propre mug.', zh: '我用我自己的杯子。', note: '⚠️ propre 在名詞前＝自己的；放後面 un mug propre＝乾淨的' },
  { id: 'S_L22_9', lesson: 22, fr: 'L\'été, je cherche la fraîcheur.', zh: '夏天我找的是涼爽。', note: 'fraîcheur＝舒服的涼（18-20度），不是 froid（冷）' },
  { id: 'S_L22_10', lesson: 22, fr: 'J\'ai dix jours de congé par an.', zh: '我一年有十天假。', note: 'les congés＝有薪假；prendre des congés＝請假' },
  { id: 'S_L23_1', lesson: 23, fr: 'Je loue un studio qui est dans une ferme.', zh: '我租一間在農場裡的套房。', note: '⭐ 後面直接是動詞 est → qui（子句缺主詞）' },
  { id: 'S_L23_2', lesson: 23, fr: 'Le salon est la pièce que je préfère.', zh: '客廳是我最喜歡的房間。', note: '⚠️ 陷阱：先行詞是地方也用 que——英文是 which I prefer 不是 where' },
  { id: 'S_L23_3', lesson: 23, fr: 'Voici la chambre où je dors.', zh: '這就是我睡的房間。', note: '⭐ 拆回兩句：Je dors dans la chambre → 介詞＋地點 → où' },
  { id: 'S_L23_4', lesson: 23, fr: 'Il vit dans un foyer qu\'il aime beaucoup.', zh: '他住在一間他很喜歡的青年公寓。', note: '⭐ que + il → qu\'il；qui 永遠不縮寫' },
  { id: 'S_L23_5', lesson: 23, fr: 'Ma sœur vit dans un studio que mes parents ont acheté l\'année dernière.', zh: '我姊住在一間我爸媽去年買的套房。', note: '⚠️ 買的是那間房（受詞）→ que，不是 où' },
  { id: 'S_L23_6', lesson: 23, fr: 'Les colocataires sont des personnes qui partagent un appartement.', zh: '室友是分租同一間公寓的人。', note: '⭐ 後面是動詞 partagent → qui' },
  { id: 'S_L23_7', lesson: 23, fr: 'C\'est un appartement de 85 mètres carrés que je partage avec deux colocataires.', zh: '那是一間 85 平方公尺、我跟兩個室友分租的公寓。', note: '⭐ que 後面先出現主詞 je；mètre carré＝平方公尺' },
  { id: 'S_L23_8', lesson: 23, fr: 'Le loyer n\'est pas cher : 400 euros par personne et par mois, charges comprises.', zh: '房租不貴：每人每月 400 歐，含雜費。', note: 'charges comprises＝含水電網，租屋廣告必看的一句' },
  { id: 'S_L23_9', lesson: 23, fr: 'Est-ce que tu trouves que ta maison est confortable ?', zh: '你覺得你家舒適嗎？', note: '🎙trouver que＝覺得（比 penser que 更口語）' },
  { id: 'S_L23_10', lesson: 23, fr: 'Ça, c\'est l\'endroit où j\'habite.', zh: '這就是我住的地方。', note: '🎙endroit＝地方（跟 lieu 同義，更口語）' },
];
