// 時態鏡頭題庫 — tense_lens.html 專用
// ─────────────────────────────────────────────────────────────
// 這不是「時態測驗」，是 codex 5-9-1「選時態的四個開關」的反覆喚醒工具。
// 依據：BLOCKS.md「感知塊靠反覆喚醒，不靠提速」／FRENCH_OS.md。
//
// ⚠️ 素材來源鐵律：所有法文句子 100% 取自 codex.js 既有例句（第5章時態、第6章語氣），
//    Claude 沒有自創任何一句。每題的 cx 欄就是它在 codex 的原始座標，可回查。
//
// 每題只做一件事：把句子裡的**一個動詞**挑出來，跑一次四個開關。
// 兩個動詞的句子會拆成兩題（同一句、不同 target）——那是最有價值的對照體驗。
//
// 格式：{ id, fr, zh, target, cell, cx, lvl, why }
//   target = 要跑開關的那個動詞（原字串，用來在句子裡標黃）
//   cell   = 答案格，四個開關的答案由 CELLS 表推出，不逐題重複寫
//   why    = 揭曉後的解說，只講「為什麼是這格」，不重講規則

// ── 四個開關的答案表（Owen 2026-08-08 定版的排序）──────────────
// ① INTENT  reel=報告現實 / dist=保留距離 / stance=表達立場
// ② WHEN    passe / present / futur / na=由主句決定
// ③ CAMERA  event=完整事件 / scene=展開中的畫面 / na=不適用
// ④ RELATION direct=直接看 / done=到參考點已完成
const CELLS = {
  present   : { s1:'reel',  s2:'present', s3:'na',    s4:'direct', label:'présent',              cx:'5-1-1', lvl:'A1' },
  pc        : { s1:'reel',  s2:'passe',   s3:'event', s4:'direct', label:'passé composé',        cx:'5-2-1', lvl:'A2' },
  imp       : { s1:'reel',  s2:'passe',   s3:'scene', s4:'direct', label:'imparfait',            cx:'5-3-1', lvl:'A2' },
  pqp       : { s1:'reel',  s2:'passe',   s3:'na',    s4:'done',   label:'plus-que-parfait',     cx:'5-4-1', lvl:'B1' },
  fproche   : { s1:'reel',  s2:'futur',   s3:'na',    s4:'direct', label:'futur proche',         cx:'5-5-1', lvl:'A2' },
  fsimple   : { s1:'reel',  s2:'futur',   s3:'na',    s4:'direct', label:'futur simple',         cx:'5-5-2', lvl:'B1' },
  precent   : { s1:'reel',  s2:'passe',   s3:'na',    s4:'direct', label:'passé récent',         cx:'5-6-1', lvl:'A2' },
  psimple   : { s1:'reel',  s2:'passe',   s3:'event', s4:'direct', label:'passé simple',         cx:'5-7-1', lvl:'B2' },
  condpoli  : { s1:'dist',  s2:'present', s3:'na',    s4:'direct', label:'conditionnel présent（禮貌）', cx:'6-2-1', lvl:'A2' },
  condhypo  : { s1:'dist',  s2:'futur',   s3:'na',    s4:'direct', label:'conditionnel présent（假設結果）', cx:'6-2-2', lvl:'B1' },
  condpasse : { s1:'dist',  s2:'passe',   s3:'na',    s4:'done',   label:'conditionnel passé',   cx:'6-2-3', lvl:'B2' },
  subj      : { s1:'stance',s2:'na',      s3:'na',    s4:'direct', label:'subjonctif présent',   cx:'6-3-1', lvl:'B1' },
  siimp     : { s1:'dist',  s2:'futur',   s3:'na',    s4:'direct', label:'si + imparfait（假設條件）', cx:'6-6-1', lvl:'B1' },
  sipqp     : { s1:'dist',  s2:'passe',   s3:'na',    s4:'done',   label:'si + plus-que-parfait（反事實）', cx:'6-6-1', lvl:'B2' },
  sipres    : { s1:'reel',  s2:'present', s3:'na',    s4:'direct', label:'si + présent（真實條件）', cx:'6-6-1', lvl:'A2' },
};

const LENS = [

// ═══ présent ══════════════════════════════════════════════════
{ id:'TL_pres_1', fr:'Je travaille depuis 8h.', zh:'我從八點工作到現在。', target:'travaille', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'中文說「工作到現在」會讓人想選過去式——法文不是。動作還在進行，說話者站在現在看它，所以是présent。depuis 不會把時態拉去過去。' },
{ id:'TL_pres_2', fr:'Elle mange en ce moment.', zh:'她正在吃。', target:'mange', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'法文沒有獨立的進行式，présent 直接兼進行。不需要（也沒有）être en train 之外的特殊形式。' },
{ id:'TL_pres_3', fr:'Je ne fume pas.', zh:'我不抽菸。', target:'fume', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'講的是常態習慣，不是此刻正在發生的事——présent 的第三種工作。' },
{ id:'TL_pres_4', fr:'Elle se lève à 7h tous les jours.', zh:'她每天七點起床。', target:'se lève', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'tous les jours 標示重複習慣。習慣是「現在為真的事實」，不是過去的畫面，所以不是 imparfait。' },
{ id:'TL_pres_5', fr:"J'habite ici depuis cinq ans.", zh:'我住這裡五年了（到現在還住）。', target:'habite', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'⚠️ 這題最容易錯。中文「五年了」聽起來像完成，但重點是「還住著」——狀態延續到說話當下，法文一律用présent。' },
{ id:'TL_pres_6', fr:'Nous apprenons le français depuis six mois.', zh:'我們學法文六個月了（還在學）。', target:'apprenons', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'同上：depuis + 還在持續 = présent。如果學完不學了，才會換成 passé composé。' },
{ id:'TL_pres_7', fr:'Il pleut en ce moment.', zh:'現在正在下雨。', target:'pleut', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'跟 Il pleuvait 只差一個開關：②時間點。站在現在看是 pleut，站在過去看才是 pleuvait。' },
{ id:'TL_pres_8', fr:'Tu comprends ce que je dis ?', zh:'你懂我在說什麼嗎？', target:'comprends', cell:'present', cx:'5-1-1', lvl:'A1',
  why:'此刻的狀態，直接看。comprendre 講的是當下懂不懂，不是一個會結束的事件。' },

// ═══ passé composé ════════════════════════════════════════════
{ id:'TL_pc_1', fr:"Hier, j'ai visité le musée.", zh:'昨天我參觀了博物館。', target:'ai visité', cell:'pc', cx:'5-2-1', lvl:'A2',
  why:'hier 把你放到過去（②），而這件事被包成一個有頭有尾的完整事件（③event）——去了、參觀了、結束了。' },
{ id:'TL_pc_2', fr:"J'ai regardé ce film hier soir.", zh:'我昨晚看了這部電影。', target:'ai regardé', cell:'pc', cx:'5-2-1', lvl:'A2',
  why:'一次完整的觀影，有起訖。若說 je regardais ce film，變成「當時正在看」的背景畫面，通常後面要接發生了什麼。' },
{ id:'TL_pc_3', fr:'Nous avons fini le projet.', zh:'我們完成了這個計畫。', target:'avons fini', cell:'pc', cx:'5-2-1', lvl:'A2',
  why:'完成類動詞天生就是完整事件，幾乎不會出現在 imparfait。' },
{ id:'TL_pc_4', fr:"Elle n'a pas compris la question.", zh:'她沒聽懂這個問題。', target:"n'a pas compris", cell:'pc', cx:'5-2-1', lvl:'A2',
  why:'否定不改變鏡頭——ne…pas 把整個 avoir + 過去分詞包住，格子還是 passé composé。' },
{ id:'TL_pc_5', fr:'Elle est arrivée hier.', zh:'她昨天到了。', target:'est arrivée', cell:'pc', cx:'5-2-2', lvl:'A2',
  why:'être 家族不改變格子——助動詞用 être 是形式問題（形式塊），四個開關的答案跟 avoir 那組完全一樣。' },
{ id:'TL_pc_6', fr:'Elle est sortie hier soir.', zh:'她昨晚出門了。', target:'est sortie', cell:'pc', cx:'5-2-2', lvl:'A2',
  why:'一個完整的外出事件。跟 elle sortait souvent（她那時常出門）差在③鏡頭。' },
{ id:'TL_pc_7', fr:'Il est resté chez lui tout le week-end.', zh:'他整個週末都待在家。', target:'est resté', cell:'pc', cx:'5-2-2', lvl:'A2',
  why:'⚠️ 整個週末很長，但依然是 passé composé——因為說話者把這段時間包成一個有邊界的整塊。長短不決定鏡頭。' },
{ id:'TL_pc_8', fr:'Ils sont nés en France.', zh:'他們在法國出生。', target:'sont nés', cell:'pc', cx:'5-2-2', lvl:'A2',
  why:'出生是瞬間的、不可能展開的事件。' },
{ id:'TL_pc_9', fr:'Ils se sont couchés tard.', zh:'他們很晚睡。', target:'se sont couchés', cell:'pc', cx:'5-2-3', lvl:'B1',
  why:'反身動詞的 PC 一律用 être——一樣是形式層的事，格子沒變。' },
{ id:'TL_pc_10', fr:'Nous nous sommes bien amusés.', zh:'我們玩得很開心。', target:'nous sommes bien amusés', cell:'pc', cx:'5-2-3', lvl:'B1',
  why:'一次完整的、結束了的經驗。' },
{ id:'TL_pc_11', fr:"Elle s'est cassé le bras.", zh:'她摔斷了手臂。', target:"s'est cassé", cell:'pc', cx:'5-2-3', lvl:'B1',
  why:'瞬間事件。（配合與否是形式塊的另一題：le bras 是真受詞且在後面，所以不配合。）' },
{ id:'TL_pc_12', fr:"J'ai pris le métro.", zh:'我搭了地鐵。', target:'ai pris', cell:'pc', cx:'5-2-4', lvl:'A2',
  why:'一趟完整的搭乘。過去分詞不規則（prendre→pris）是形式層，不影響開關。' },
{ id:'TL_pc_13', fr:'Ils ont vu ce film trois fois.', zh:'他們看過這部電影三次。', target:'ont vu', cell:'pc', cx:'5-2-4', lvl:'A2',
  why:'⚠️ 重複三次還是 passé composé。「重複」不等於 imparfait——trois fois 標明了次數，就是三個有邊界的事件，不是模糊的習慣。' },
{ id:'TL_pc_14', fr:'Nous avons eu de la chance.', zh:'我們很幸運。', target:'avons eu', cell:'pc', cx:'5-2-4', lvl:'A2',
  why:'指某次特定的走運，是事件。若說 nous avions de la chance，變成「那陣子我們運氣一直很好」的背景。' },
{ id:'TL_pc_15', fr:'Ces photos ? Je les ai prises hier.', zh:'這些照片？我昨天拍的。', target:'les ai prises', cell:'pc', cx:'5-2-5', lvl:'B2',
  why:'COD 前置只改變過去分詞要不要配合（形式塊），格子仍是 passé composé。' },
{ id:'TL_pc_16', fr:'Où sont mes clés ? Je ne les ai pas vues.', zh:'我的鑰匙在哪？我沒看到它們。', target:"ne les ai pas vues", cell:'pc', cx:'5-2-5', lvl:'B2',
  why:'否定 + COD 前置疊在一起，格子還是沒動。' },

// ═══ imparfait ════════════════════════════════════════════════
{ id:'TL_imp_1', fr:"Quand j'étais enfant, je vivais à la campagne.", zh:'我小時候住在鄉下。', target:'vivais', cell:'imp', cx:'5-3-1', lvl:'A2',
  why:'不交代什麼時候開始搬去、什麼時候搬走——鏡頭進到那段時間裡面，拍的是持續的狀態。' },
{ id:'TL_imp_2', fr:'Elle avait les cheveux longs.', zh:'她那時頭髮很長。', target:'avait', cell:'imp', cx:'5-3-1', lvl:'A2',
  why:'描述外觀/狀態，沒有起訖。狀態類的句子在過去幾乎都落在 imparfait。' },
{ id:'TL_imp_3', fr:'Il ne savait pas quoi dire.', zh:'他當時不知道該說什麼。', target:'ne savait pas', cell:'imp', cx:'5-3-1', lvl:'A2',
  why:'心理狀態＝展開中的畫面。savoir / penser / croire / vouloir 這類動詞在過去多半是 imparfait。' },
{ id:'TL_imp_4', fr:'Le ciel était gris ce jour-là.', zh:'那天天空是灰色的。', target:'était', cell:'imp', cx:'5-3-1', lvl:'A2',
  why:'典型的佈景。故事的舞台用 imparfait 搭，事件才用 passé composé 演。' },
{ id:'TL_imp_5', fr:"J'habitais à Lyon avant.", zh:'我以前住里昂。', target:'habitais', cell:'imp', cx:'5-3-1', lvl:'A2',
  why:'⚠️ 跟 J\'habite ici depuis cinq ans 對照著看：那句還住著（présent），這句已經不住了、而且不交代住多久（imparfait）。' },
{ id:'TL_imp_6', fr:'Nous mangions ensemble tous les soirs.', zh:'我們那時每晚都一起吃飯。', target:'mangions', cell:'imp', cx:'5-3-1', lvl:'A2',
  why:'tous les soirs 是模糊的重複習慣，沒有邊界。對照 TL_pc_13 的 trois fois——那個有次數所以是事件。' },
{ id:'TL_imp_7', fr:'Tu buvais du café tous les matins.', zh:'你以前每天早上都喝咖啡。', target:'buvais', cell:'imp', cx:'5-3-2', lvl:'A2',
  why:'過去的習慣，鏡頭不切邊界。' },
{ id:'TL_imp_8', fr:'Il y avait beaucoup de monde à la fête.', zh:'派對上有很多人。', target:'y avait', cell:'imp', cx:'5-3-1', lvl:'A2',
  why:'il y a 在過去講場面幾乎一律 il y avait——那是背景不是事件。' },
{ id:'TL_imp_9', fr:'Nous étions fatigués.', zh:'我們那時很累。', target:'étions', cell:'imp', cx:'5-3-2', lvl:'A2',
  why:'狀態。若說 nous avons été fatigués，會變成很奇怪的「我們累了一陣然後結束」。' },
{ id:'TL_imp_10', fr:'Vous habitiez où avant ?', zh:'你們以前住哪裡？', target:'habitiez', cell:'imp', cx:'5-3-2', lvl:'A2',
  why:'問的是過去的居住狀態，不是某次搬家事件。' },

// ═══ PC vs imparfait：同一句兩個鏡頭（最高價值的對照）═══════════
{ id:'TL_mix_1a', fr:'Il pleuvait quand je suis sorti.', zh:'我出門時正在下雨。', target:'pleuvait', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'下雨是佈景——鏡頭進到雨裡面，不交代幾點開始下、幾點停。' },
{ id:'TL_mix_1b', fr:'Il pleuvait quand je suis sorti.', zh:'我出門時正在下雨。', target:'suis sorti', cell:'pc', cx:'5-3-3', lvl:'A2',
  why:'出門是打斷背景的那一下——有明確的一個瞬間，所以是完整事件。同一句話裡兩個動詞、兩個鏡頭，這就是③開關在做的事。' },
{ id:'TL_mix_2a', fr:'Je dormais quand tu as téléphoné.', zh:'你來電時我正在睡。', target:'dormais', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'睡覺是那個當下正在展開的狀態。' },
{ id:'TL_mix_2b', fr:'Je dormais quand tu as téléphoné.', zh:'你來電時我正在睡。', target:'as téléphoné', cell:'pc', cx:'5-3-3', lvl:'A2',
  why:'來電是插進來的單一事件。固定句型：imparfait 舖底 + quand + passé composé 打斷。' },
{ id:'TL_mix_3a', fr:'Il faisait ses devoirs quand le téléphone a sonné.', zh:'他在寫作業時電話響了。', target:'faisait', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'進行中的活動＝背景。faire ses devoirs 本身可長可短，這裡不交代寫多久，只當舞台。' },
{ id:'TL_mix_3b', fr:'Il faisait ses devoirs quand le téléphone a sonné.', zh:'他在寫作業時電話響了。', target:'a sonné', cell:'pc', cx:'5-3-3', lvl:'A2',
  why:'鈴響是瞬間事件，切進背景。téléphone a sonné 幾乎不可能是 imparfait，除非要講「那陣子電話老是在響」。' },
{ id:'TL_mix_4a', fr:'Nous dînions tranquillement quand quelqu’un a frappé à la porte.', zh:'我們正安靜地吃晚餐時有人敲門。', target:'dînions', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'進行中的場面，tranquillement 更強化了「正在持續」的畫面感。' },
{ id:'TL_mix_4b', fr:'Nous dînions tranquillement quand quelqu’un a frappé à la porte.', zh:'我們正安靜地吃晚餐時有人敲門。', target:'a frappé', cell:'pc', cx:'5-3-3', lvl:'A2',
  why:'敲門是打斷背景的單一動作。quelqu\'un 這種突然出現的主詞常伴隨 passé composé。' },
{ id:'TL_mix_5a', fr:'Il faisait beau, alors nous sommes sortis.', zh:'天氣很好，所以我們出門了。', target:'faisait', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'天氣是條件/背景。faire beau 講天氣狀態，在過去幾乎固定 imparfait。' },
{ id:'TL_mix_5b', fr:'Il faisait beau, alors nous sommes sortis.', zh:'天氣很好，所以我們出門了。', target:'sommes sortis', cell:'pc', cx:'5-3-3', lvl:'A2',
  why:'因為背景而發生的那個決定與行動＝事件。這裡沒有 quand，靠 alors 串——句型會換，鏡頭邏輯不變。' },
{ id:'TL_mix_6a', fr:'Elle lisait un livre. Soudain, elle a entendu un bruit.', zh:'她在讀書。突然，她聽到一個聲音。', target:'lisait', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'跨兩句也一樣：第一句舖底。' },
{ id:'TL_mix_6b', fr:'Elle lisait un livre. Soudain, elle a entendu un bruit.', zh:'她在讀書。突然，她聽到一個聲音。', target:'a entendu', cell:'pc', cx:'5-3-3', lvl:'A2',
  why:'soudain 幾乎是 passé composé 的信號燈。' },
{ id:'TL_mix_7a', fr:"Quand j'étais jeune, j'ai vécu deux ans à Paris.", zh:'我年輕時在巴黎住過兩年。', target:'étais', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'「年輕時」是一整片模糊的時期＝背景。' },
{ id:'TL_mix_7b', fr:"Quand j'étais jeune, j'ai vécu deux ans à Paris.", zh:'我年輕時在巴黎住過兩年。', target:'ai vécu', cell:'pc', cx:'5-3-3', lvl:'A2',
  why:'⚠️ 這題是整套系統的試金石。住兩年比「年輕時」短，卻用 passé composé——因為 deux ans 給了它明確的邊界，說話者把它包成一塊。再說一次：長短不決定鏡頭，你怎麼拍才決定。' },
{ id:'TL_mix_8a', fr:'Elle souriait toujours quand elle parlait de son enfance.', zh:'她講起童年時總是面帶微笑。', target:'souriait', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'⚠️ 這句沒有 passé composé。兩個動詞都是 imparfait，因為兩件事都是反覆的習慣，沒有任何一個是單一事件——不要看到 quand 就反射找事件。' },
{ id:'TL_mix_8b', fr:'Elle souriait toujours quand elle parlait de son enfance.', zh:'她講起童年時總是面帶微笑。', target:'parlait', cell:'imp', cx:'5-3-3', lvl:'A2',
  why:'同上，習慣性的重複。quand 在這裡是「每當」不是「就在那時」——這個字本身不決定時態。' },

// ═══ plus-que-parfait ═════════════════════════════════════════
{ id:'TL_pqp_1a', fr:'Quand je suis arrivé, ils avaient déjà mangé.', zh:'我到的時候，他們已經吃過了。', target:'suis arrivé', cell:'pc', cx:'5-4-1', lvl:'B1',
  why:'我抵達＝參考點，本身是完整事件。' },
{ id:'TL_pqp_1b', fr:'Quand je suis arrivé, ils avaient déjà mangé.', zh:'我到的時候，他們已經吃過了。', target:'avaient déjà mangé', cell:'pqp', cx:'5-4-1', lvl:'B1',
  why:'④開關開了：不是直接看「他們吃飯」，是看它「在我抵達那個點之前就完成了」。這是 PQP 唯一的工作。' },
{ id:'TL_pqp_2', fr:'Elle était déjà partie.', zh:'她（那時）已經走了。', target:'était déjà partie', cell:'pqp', cx:'5-4-1', lvl:'B1',
  why:'déjà 是 PQP 的常見伴侶。參考點沒明說，但語境裡有一個「那時」。' },
{ id:'TL_pqp_3', fr:'Nous avions déjà réservé la table.', zh:'我們早就訂好位子了。', target:'avions déjà réservé', cell:'pqp', cx:'5-4-1', lvl:'B1',
  why:'相對於過去某個時點已完成。' },
{ id:'TL_pqp_4', fr:'Il était parti avant mon arrivée.', zh:'我到之前他就走了。', target:'était parti', cell:'pqp', cx:'5-4-1', lvl:'B1',
  why:'avant 明講了參考點，④開關直接被觸發。' },
{ id:'TL_pqp_5', fr:'Il avait déjà vu ce film avant d’aller au cinéma avec nous.', zh:'他在跟我們去電影院之前就已經看過這部電影了。', target:'avait déjà vu', cell:'pqp', cx:'5-4-1', lvl:'B1',
  why:'兩層過去疊起來，先發生的那層退到 PQP。' },
{ id:'TL_pqp_6a', fr:'Elle a dit qu’elle avait fini.', zh:'她說她已經做完了。', target:'a dit', cell:'pc', cx:'5-4-1', lvl:'B1',
  why:'「說」這個動作本身是事件。' },
{ id:'TL_pqp_6b', fr:'Elle a dit qu’elle avait fini.', zh:'她說她已經做完了。', target:'avait fini', cell:'pqp', cx:'5-4-1', lvl:'B1',
  why:'她說話那刻是參考點，做完發生在更早——④完成。這同時也是時態呼應（5-8-1）：原話的 j\'ai fini 退位成 PQP。' },
{ id:'TL_pqp_7', fr:'Je ne savais pas qu’ils s’étaient rencontrés avant.', zh:'我不知道他們之前見過面。', target:"s'étaient rencontrés", cell:'pqp', cx:'5-4-1', lvl:'B1',
  why:'反身動詞的 PQP 用 être，形式改了、格子沒改。' },

// ═══ futur proche / futur simple ══════════════════════════════
{ id:'TL_fp_1', fr:'On va être en retard !', zh:'我們要遲到了！', target:'va être', cell:'fproche', cx:'5-5-1', lvl:'A2',
  why:'眼前就要發生、跟現在有連結——futur proche 的主場。用 fera / serons 會顯得太正式太遠。' },
{ id:'TL_fp_2', fr:'Je vais appeler le médecin.', zh:'我要打電話給醫生。', target:'vais appeler', cell:'fproche', cx:'5-5-1', lvl:'A2',
  why:'當下的決定與打算，話一出口就準備去做。這是 futur proche 最典型的用法。' },
{ id:'TL_fp_3', fr:'Ils vont déménager le mois prochain.', zh:'他們下個月要搬家。', target:'vont déménager', cell:'fproche', cx:'5-5-1', lvl:'A2',
  why:'⚠️ 下個月不算「馬上」，但已經確定、已經在計畫中——futur proche 管的是「跟現在的連結」，不只是時間近。' },
{ id:'TL_fp_4', fr:'Nous n’allons pas rester longtemps.', zh:'我們不會待很久。', target:"n'allons pas rester", cell:'fproche', cx:'5-5-1', lvl:'A2',
  why:'否定包住 aller，原形留在後面。' },
{ id:'TL_fp_5', fr:'On va manger dans dix minutes.', zh:'我們十分鐘後要吃飯。', target:'va manger', cell:'fproche', cx:'5-5-1', lvl:'A2',
  why:'十分鐘後，緊接著現在。dans + 短時間幾乎都會配 futur proche。' },
{ id:'TL_fs_1', fr:'Demain, il fera beau.', zh:'明天天氣會好。（氣象預報體）', target:'fera', cell:'fsimple', cx:'5-5-2', lvl:'B1',
  why:'②時間點是未來，跟 futur proche 同一格——差別在語域：預報、公告、承諾用 futur simple，比較正式、比較「事情就是會這樣」。' },
{ id:'TL_fs_2', fr:'Vous recevrez la réponse par email.', zh:'您會收到電子郵件回覆。', target:'recevrez', cell:'fsimple', cx:'5-5-2', lvl:'B1',
  why:'公務/正式通知的典型語域。' },
{ id:'TL_fs_3', fr:'Je te téléphonerai ce soir.', zh:'我今晚會打電話給你。', target:'téléphonerai', cell:'fsimple', cx:'5-5-2', lvl:'B1',
  why:'帶承諾意味。口語裡也常說 je vais te téléphoner，兩個都通，差在正式程度。' },
{ id:'TL_fs_4a', fr:'Dès qu’il arrivera, on partira.', zh:'他一到我們就出發。', target:'arrivera', cell:'fsimple', cx:'5-5-2', lvl:'B1',
  why:'⚠️ 中文說「他一到」像現在式，法文的 dès que / quand 後面講未來的事必須用 futur——不能寫 dès qu\'il arrive。這是中文母語者的固定陷阱。' },
{ id:'TL_fs_4b', fr:'Dès qu’il arrivera, on partira.', zh:'他一到我們就出發。', target:'partira', cell:'fsimple', cx:'5-5-2', lvl:'B1',
  why:'主句也是未來。兩邊都 futur，跟英文不一樣。' },
{ id:'TL_fs_5', fr:'Quand j’aurai le temps, je viendrai.', zh:'我有空的時候會來。', target:'aurai', cell:'fsimple', cx:'5-5-2', lvl:'B1',
  why:'同上，quand + 未來 → futur simple。' },
{ id:'TL_fs_6', fr:'Il y aura des averses cet après-midi.', zh:'今天下午會有陣雨。', target:'y aura', cell:'fsimple', cx:'5-5-2', lvl:'B1',
  why:'預報體。il y a 的未來形。' },

// ═══ passé récent ═════════════════════════════════════════════
{ id:'TL_pr_1', fr:'Il vient de partir.', zh:'他剛走。', target:'vient de partir', cell:'precent', cx:'5-6-1', lvl:'A2',
  why:'②是過去（事情已經發生），但強調的是「剛剛、跟現在還連著」。venir 本身是現在式，別被騙了——看的是整組 venir de + 原形。' },
{ id:'TL_pr_2', fr:'Elle vient de m’appeler.', zh:'她剛打給我。', target:"vient de m'appeler", cell:'precent', cx:'5-6-1', lvl:'A2',
  why:'格子是 passé récent；代名詞 m\' 插在原形前面而不是 venir 前面，這是形式層的事，不影響開關。' },
{ id:'TL_pr_3', fr:'Nous venons de recevoir votre message.', zh:'我們剛收到您的訊息。', target:'venons de recevoir', cell:'precent', cx:'5-6-1', lvl:'A2',
  why:'剛完成、餘溫還在。商務信件常用這句開頭，等於中文「我們剛收到您的來信」。' },
{ id:'TL_pr_4a', fr:'Je suis fatigué, je viens de courir.', zh:'我很累，我剛跑完步。', target:'suis', cell:'present', cx:'5-6-1', lvl:'A2',
  why:'現在的狀態，直接看。être fatigué 是狀態不是事件，所以不會是 passé composé。' },
{ id:'TL_pr_4b', fr:'Je suis fatigué, je viens de courir.', zh:'我很累，我剛跑完步。', target:'viens de courir', cell:'precent', cx:'5-6-1', lvl:'A2',
  why:'剛結束的動作，用來解釋現在的狀態——這正是 passé récent 存在的理由：把過去接到現在。' },
{ id:'TL_pr_5a', fr:'Je viens de manger, je n’ai pas faim.', zh:'我剛吃過，不餓。', target:'viens de manger', cell:'precent', cx:'5-6-1', lvl:'A2',
  why:'剛剛完成。若用 j\'ai mangé，只是陳述吃過，少了「所以現在不餓」的即時因果。' },
{ id:'TL_pr_5b', fr:'Je viens de manger, je n’ai pas faim.', zh:'我剛吃過，不餓。', target:"n'ai pas faim", cell:'present', cx:'5-6-1', lvl:'A2',
  why:'現在的狀態。avoir faim 是狀態不是事件。' },

// ═══ passé simple（只認不產）══════════════════════════════════
{ id:'TL_ps_1', fr:'Il ouvrit la porte et sortit.', zh:'他開門出去了。（小說體）', target:'ouvrit', cell:'psimple', cx:'5-7-1', lvl:'B2',
  why:'跟 passé composé 同一格——完整事件、直接看。差別純粹是語域：passé simple 只出現在書面文學/歷史敘事，口語永遠不用。認得出來就夠了。' },
{ id:'TL_ps_2', fr:'Elle regarda par la fenêtre.', zh:'她望向窗外。（小說體）', target:'regarda', cell:'psimple', cx:'5-7-1', lvl:'B2',
  why:'-a 結尾的 -er 動詞 passé simple。口語會說 elle a regardé。' },
{ id:'TL_ps_3', fr:'Ils partirent sans un mot.', zh:'他們一言不發地離開了。', target:'partirent', cell:'psimple', cx:'5-7-1', lvl:'B2',
  why:'-irent 是第三人稱複數的招牌長相。' },
{ id:'TL_ps_4', fr:'Napoléon naquit en Corse.', zh:'拿破崙生於科西嘉。（＝Napoléon est né en Corse）', target:'naquit', cell:'psimple', cx:'5-7-1', lvl:'B2',
  why:'歷史敘述的預設時態。同一件事口語就是 est né，格子完全相同。' },
{ id:'TL_ps_5', fr:'Le roi mourut sans héritier.', zh:'國王死時沒有繼承人。', target:'mourut', cell:'psimple', cx:'5-7-1', lvl:'B2',
  why:'-ut 結尾。讀到這種形就知道自己在讀書面敘事。' },

// ═══ 時態呼應（間接引語）══════════════════════════════════════
{ id:'TL_conc_1a', fr:'Il a dit qu’il était fatigué.', zh:'他說他很累。', target:'a dit', cell:'pc', cx:'5-8-1', lvl:'B2',
  why:'說話這個動作有頭有尾，是完整事件。主句先定錨在過去，從句才會被拖著退位。' },
{ id:'TL_conc_1b', fr:'Il a dit qu’il était fatigué.', zh:'他說他很累。', target:'était', cell:'imp', cx:'5-8-1', lvl:'B2',
  why:'⚠️ 這裡的 imparfait 不是③鏡頭選出來的，是被主句拖下去的——原話是 je suis fatigué（présent），主句一變過去，從句就退位成 imparfait。看到 dit que / pensait que 要先想到呼應。' },
{ id:'TL_conc_2a', fr:'Elle pensait que tu viendrais.', zh:'她以為你會來。', target:'pensait', cell:'imp', cx:'5-8-1', lvl:'B2',
  why:'心理狀態＝背景畫面。penser / croire 在過去幾乎都是 imparfait，也正好是觸發時態呼應的那批動詞。' },
{ id:'TL_conc_2b', fr:'Elle pensait que tu viendrais.', zh:'她以為你會來。', target:'viendrais', cell:'condhypo', cx:'5-8-1', lvl:'B2',
  why:'⚠️ 長得像條件式，功能卻是「過去裡的未來」——原話是 tu viendras（futur），退位後變 conditionnel。形式相同、來路不同，這是 B2 最容易誤判的一格。' },
{ id:'TL_conc_3', fr:'Je croyais qu’il habitait à Paris.', zh:'我以為他住在巴黎。', target:'habitait', cell:'imp', cx:'5-8-1', lvl:'B2',
  why:'原話 il habite → 退位成 imparfait。' },
{ id:'TL_conc_4', fr:'Nous pensions qu’ils avaient déjà réservé.', zh:'我們以為他們已經訂好了。', target:'avaient déjà réservé', cell:'pqp', cx:'5-8-1', lvl:'B2',
  why:'原話 ils ont déjà réservé（PC）→ 退位成 PQP。' },
{ id:'TL_conc_5', fr:'Elle m’a expliqué qu’elle serait en retard.', zh:'她跟我解釋她會遲到。', target:'serait', cell:'condhypo', cx:'5-8-1', lvl:'B2',
  why:'原話 je serai en retard（futur）→ 退位成 conditionnel。' },

// ═══ conditionnel：禮貌 ═══════════════════════════════════════
{ id:'TL_cp_1', fr:'Je voudrais un café, s’il vous plaît.', zh:'我想要一杯咖啡，謝謝。', target:'voudrais', cell:'condpoli', cx:'6-2-1', lvl:'A2',
  why:'①開關轉到「保留距離」：je veux 太直接像命令，往後退一步就變得有禮貌。跟未來、跟假設都無關。' },
{ id:'TL_cp_2', fr:'Pourriez-vous m’aider, s’il vous plaît ?', zh:'您能幫我一下嗎，麻煩了？', target:'Pourriez', cell:'condpoli', cx:'6-2-1', lvl:'A2',
  why:'pouvez → pourriez，距離感讓請求變軟。' },
{ id:'TL_cp_3', fr:'J’aimerais poser une question.', zh:'我想問一個問題。', target:'aimerais', cell:'condpoli', cx:'6-2-1', lvl:'A2',
  why:'跟 je voudrais 同一組客套語。' },
{ id:'TL_cp_4', fr:'Tu pourrais fermer la fenêtre ?', zh:'你可以關窗嗎？', target:'pourrais', cell:'condpoli', cx:'6-2-1', lvl:'A2',
  why:'即使對 tu 也可以用，柔化語氣。' },
{ id:'TL_cp_5', fr:'On devrait partir maintenant.', zh:'我們應該現在出發了。', target:'devrait', cell:'condpoli', cx:'6-2-1', lvl:'A2',
  why:'doit（必須）→ devrait（應該）。條件式把義務降級成建議。' },
{ id:'TL_cp_6', fr:'J’aimerais réserver une table.', zh:'我想訂一張桌子。', target:'aimerais', cell:'condpoli', cx:'6-2-1', lvl:'A2',
  why:'訂位、點餐的標準開場。整組 j\'aimerais + 原形值得當一塊記起來，不要每次重新組裝。' },

// ═══ conditionnel：假設結果 ═══════════════════════════════════
{ id:'TL_ch_1a', fr:'Si j’étais riche, j’achèterais une maison.', zh:'如果我有錢就買房。', target:'étais', cell:'siimp', cx:'6-6-1', lvl:'B1',
  why:'⚠️ 最重要的一題。這個 imparfait 跟過去完全無關，③鏡頭沒有出力——是①開關轉到「保留距離」：我現在沒錢，這是假的。si 後面的 imparfait 標記的是「不真實」，不是「以前」。' },
{ id:'TL_ch_1b', fr:'Si j’étais riche, j’achèterais une maison.', zh:'如果我有錢就買房。', target:'achèterais', cell:'condhypo', cx:'6-6-1', lvl:'B1',
  why:'假設成立的話會發生的結果——距離＋朝未來看。si 子句 imparfait、主句 conditionnel，這組是綁在一起的。' },
{ id:'TL_ch_2a', fr:'Si je gagnais au loto, je voyagerais.', zh:'如果我中樂透，我會去旅行。', target:'gagnais', cell:'siimp', cx:'6-6-1', lvl:'B1',
  why:'不真實的假設，不是過去的習慣。' },
{ id:'TL_ch_2b', fr:'Si je gagnais au loto, je voyagerais.', zh:'如果我中樂透，我會去旅行。', target:'voyagerais', cell:'condhypo', cx:'6-6-1', lvl:'B1',
  why:'假設成立會發生的結果。si + imparfait 配 conditionnel，這兩塊是綁在一起出現的。' },
{ id:'TL_ch_3', fr:'Que ferais-tu à ma place ?', zh:'如果是你，你會怎麼做？', target:'ferais', cell:'condhypo', cx:'6-2-2', lvl:'B1',
  why:'沒有 si，但 à ma place 就是假設條件。' },
{ id:'TL_ch_4', fr:'Il vaudrait mieux partir tôt.', zh:'早點出發會比較好。', target:'vaudrait', cell:'condhypo', cx:'6-2-2', lvl:'B1',
  why:'委婉建議，隱含「如果要我說的話」。vaut mieux 太直接，vaudrait mieux 留了餘地。' },
{ id:'TL_ch_5', fr:'Ce serait une bonne idée.', zh:'這會是個好主意。（委婉表達）', target:'serait', cell:'condhypo', cx:'6-2-2', lvl:'B1',
  why:'c\'est 太斷定，ce serait 留了餘地。' },
{ id:'TL_ch_6', fr:'Elle serait plus heureuse à la campagne.', zh:'她在鄉下會更快樂。', target:'serait', cell:'condhypo', cx:'6-2-2', lvl:'B1',
  why:'隱含的假設：如果她住鄉下的話。' },

// ═══ si 三式：真實條件 ════════════════════════════════════════
{ id:'TL_si_1a', fr:'S’il pleut demain, je resterai chez moi.', zh:'明天下雨我就待在家。', target:'pleut', cell:'sipres', cx:'6-6-1', lvl:'A2',
  why:'⚠️ 這是真的有可能發生的條件，所以①還在「報告現實」。si 後面用 présent——不能用 futur，即使講的是明天。' },
{ id:'TL_si_1b', fr:'S’il pleut demain, je resterai chez moi.', zh:'明天下雨我就待在家。', target:'resterai', cell:'fsimple', cx:'6-6-1', lvl:'A2',
  why:'主句才放 futur。si 子句 présent + 主句 futur，這是三式裡的第一式。' },
{ id:'TL_si_2a', fr:'Si j’ai le temps, je viendrai.', zh:'如果我有空，我會來。', target:'ai', cell:'sipres', cx:'6-6-1', lvl:'A2',
  why:'真實可能的條件 → présent。' },
{ id:'TL_si_2b', fr:'Si j’ai le temps, je viendrai.', zh:'如果我有空，我會來。', target:'viendrai', cell:'fsimple', cx:'6-6-1', lvl:'A2',
  why:'結果放 futur simple。' },
{ id:'TL_si_3', fr:'Si tu ne pars pas maintenant, tu vas rater le train.', zh:'如果你現在不走，你會錯過火車。', target:'vas rater', cell:'fproche', cx:'6-6-1', lvl:'A2',
  why:'第一式的口語版：主句用 futur proche 也完全可以，因為事情迫在眉睫。' },

// ═══ si 三式：反事實（過去）═══════════════════════════════════
{ id:'TL_sp_1a', fr:'Si j’avais su, je ne serais pas venu.', zh:'早知道我就不會來了。', target:'avais su', cell:'sipqp', cx:'6-2-3', lvl:'B2',
  why:'⚠️ PQP 的形，但④完成之外還疊了①距離——事實是「我不知道」。這是第三式：對已經發生的事做反事實假設。' },
{ id:'TL_sp_1b', fr:'Si j’avais su, je ne serais pas venu.', zh:'早知道我就不會來了。', target:'ne serais pas venu', cell:'condpasse', cx:'6-2-3', lvl:'B2',
  why:'事實是我來了。條件式過去＝「本來會/本來不會，但沒有」。悔恨的標準句型。' },
{ id:'TL_sp_2a', fr:'Si j’avais étudié plus, j’aurais réussi.', zh:'如果我當初多讀點書，我就會成功了。', target:'avais étudié', cell:'sipqp', cx:'6-6-1', lvl:'B2',
  why:'反事實：事實是當初沒多讀。si + PQP 是第三式的固定入口，處理已成定局的事。' },
{ id:'TL_sp_2b', fr:'Si j’avais étudié plus, j’aurais réussi.', zh:'如果我當初多讀點書，我就會成功了。', target:'aurais réussi', cell:'condpasse', cx:'6-6-1', lvl:'B2',
  why:'事實是沒成功。conditionnel passé 講的永遠是「本來會，但沒發生」。' },
{ id:'TL_sp_3', fr:'Si elle avait su, elle ne serait pas partie.', zh:'如果她那時知道，她就不會走了。', target:'avait su', cell:'sipqp', cx:'6-6-1', lvl:'B2',
  why:'第三式，跟第二式（si + imparfait）差在時間點：這件事已成定局。' },
{ id:'TL_cpa_1', fr:'Tu aurais pu me dire !', zh:'你大可以跟我說啊！', target:'aurais pu', cell:'condpasse', cx:'6-2-3', lvl:'B2',
  why:'沒有 si，但責備語氣裡藏著「本來可以，卻沒有」。' },
{ id:'TL_cpa_2', fr:'J’aurais dû partir plus tôt.', zh:'我早該早點走。', target:'aurais dû', cell:'condpasse', cx:'6-2-3', lvl:'B2',
  why:'後悔的固定說法。devoir 的條件式過去＝「早該」。' },
{ id:'TL_cpa_3', fr:'Nous aurions aimé rester plus longtemps.', zh:'我們原本想待久一點。', target:'aurions aimé', cell:'condpasse', cx:'6-2-3', lvl:'B2',
  why:'「原本想」——想了但沒做成。' },
{ id:'TL_cpa_4', fr:'Elle n’aurait jamais dit ça.', zh:'她絕對不會說那種話的。', target:"n'aurait jamais dit", cell:'condpasse', cx:'6-2-3', lvl:'B2',
  why:'對過去的推測性否定——說話者在替她辯護：以她的個性不可能說那種話。' },

// ═══ subjonctif ═══════════════════════════════════════════════
{ id:'TL_sub_1', fr:'Il faut que tu viennes.', zh:'你必須來。', target:'viennes', cell:'subj', cx:'6-3-1', lvl:'B1',
  why:'①開關轉到「表達立場」：說話者在下判斷/施加意志，不是報導事實。il faut que 是最強的觸發器。②時間點由主句決定，這個動詞自己不帶時間。' },
{ id:'TL_sub_2', fr:'Je suis content que tu sois là.', zh:'我很高興你在這裡。', target:'sois', cell:'subj', cx:'6-3-1', lvl:'B1',
  why:'情緒是立場。「你在這裡」是事實沒錯，但從句掛在我的感受底下，所以進虛擬式。' },
{ id:'TL_sub_3', fr:'Je regrette que tu ne puisses pas venir.', zh:'我很遺憾你不能來。', target:'puisses', cell:'subj', cx:'6-3-1', lvl:'B1',
  why:'遺憾＝情緒＝立場，①開關轉到 stance。regretter que 跟 être content que 同一類觸發器。' },
{ id:'TL_sub_4', fr:'Bien qu’il soit fatigué, il continue.', zh:'雖然他很累，他還是繼續。', target:'soit', cell:'subj', cx:'6-3-1', lvl:'B1',
  why:'bien que 永遠配虛擬式——讓步連接詞把事實框成「姑且承認」。' },
{ id:'TL_sub_5', fr:'Je pars avant qu’il arrive.', zh:'我在他到之前先走。', target:'arrive', cell:'subj', cx:'6-3-1', lvl:'B1',
  why:'avant que 觸發虛擬——他還沒到，事情還沒落定。' },
{ id:'TL_sub_6', fr:'Il faut que nous partions.', zh:'我們必須走了。', target:'partions', cell:'subj', cx:'6-3-2', lvl:'B1',
  why:'nous 的虛擬式跟 imparfait 長得一樣（-ions），靠 il faut que 判斷不是靠字尾。' },
{ id:'TL_sub_7', fr:'Je veux que tu ailles voir un médecin.', zh:'我要你去看醫生。', target:'ailles', cell:'subj', cx:'6-3-2', lvl:'B1',
  why:'意志動詞 vouloir que → 虛擬。aller 的虛擬式不規則（aille）。' },
{ id:'TL_sub_8', fr:'Il faut que tu sois à l’heure.', zh:'你必須準時。', target:'sois', cell:'subj', cx:'6-3-2', lvl:'B1',
  why:'être 的虛擬式，高頻，值得整塊記起來。' },
{ id:'TL_sub_9', fr:'Je ne pense pas qu’il vienne.', zh:'我不認為他會來。', target:'vienne', cell:'subj', cx:'6-3-3', lvl:'B2',
  why:'⚠️ penser 肯定時配直陳（je pense qu\'il vient），否定後進入懷疑＝立場，才翻成虛擬。同一個動詞，①開關被否定詞扳過去。' },
{ id:'TL_sub_10', fr:'Je doute qu’il soit là.', zh:'我懷疑他在不在。', target:'soit', cell:'subj', cx:'6-3-3', lvl:'B2',
  why:'douter 本身就是不確定＝立場。' },
{ id:'TL_sub_11', fr:'Je ne suis pas sûr qu’elle vienne.', zh:'我不確定她會不會來。', target:'vienne', cell:'subj', cx:'6-3-3', lvl:'B2',
  why:'不確定 → 虛擬。對照下一題。' },
{ id:'TL_sub_12', fr:'Je suis sûr qu’elle réussira.', zh:'我確定她會成功。', target:'réussira', cell:'fsimple', cx:'6-3-3', lvl:'B2',
  why:'⚠️ 陷阱題：確定 → ①回到「報告現實」，用直陳式的 futur，不是虛擬。sûr / certain / évident 肯定時都走直陳。' },
{ id:'TL_sub_13', fr:'Il est évident qu’elle a raison.', zh:'她說的很明顯是對的。', target:'a', cell:'present', cx:'6-3-3', lvl:'B2',
  why:'évident＝斷定事實，直陳式。跟 il faut que 那組相反。' },
{ id:'TL_sub_14', fr:'J’espère qu’il viendra.', zh:'我希望他會來。', target:'viendra', cell:'fsimple', cx:'6-3-3', lvl:'B2',
  why:'⚠️ espérer 是最有名的例外——中文/英文直覺都覺得「希望」該配虛擬，法文卻配直陳。跟它意思很近的 souhaiter que 反而配虛擬。這題單純要背。' },
{ id:'TL_sub_15', fr:'Nous espérons que tout ira bien.', zh:'我們希望一切順利。', target:'ira', cell:'fsimple', cx:'6-3-3', lvl:'B2',
  why:'同上，espérer + 直陳 futur。' },

];

if (typeof module !== 'undefined') module.exports = { LENS, CELLS };
