/* 自動產生，勿手改：node tools/gen_topic_labels.js（來源：dashboard.html 的 TOPIC_LABELS） */
var TOPIC_LABELS_FR = {
 "etre-avoir": "Être & Avoir",
 "er-verbs": "Verbes -ER",
 "reflexive-verbs": "Verbes réfléchis",
 "greetings-politeness": "Salutations",
 "negation": "Négation",
 "numbers-basic": "Nombres",
 "articles": "Articles",
 "possessives": "Possessifs",
 "adjective-agreement": "Accord adjectif",
 "family-possessives": "Famille",
 "question-words": "Questions",
 "likes-hobbies-sports": "Loisirs",
 "couleurs": "Couleurs",
 "preposition-country": "Prép. pays",
 "preposition-place-transport": "Prép. lieu",
 "ir-re-verbs": "Verbes -IR/-RE",
 "irregular-verbs-3rd-group": "Verbes irrég.",
 "heure": "Heure",
 "futur-proche": "Futur proche",
 "passe-compose": "Passé composé",
 "vocab-housing": "Logement",
 "pronoms-toniques": "Pronoms toniques",
 "cod-pronouns": "Pronoms COD",
 "prohibition-request": "Interdiction / Requête",
 "body-health": "Corps & Santé",
 "pronom-y": "Pronom y",
 "comparaison": "Comparaison",
 "reservation-hotel": "Réservation hôtel",
 "imparfait": "Imparfait",
 "vocab-souvenirs": "Souvenirs & saveurs",
 "pronoms-y-en": "Pronoms y / en",
 "vocab-sens": "Les cinq sens",
 "paires-confusables": "Paires confusables",
 "vocab-meteo": "La météo",
 "vocab-logement": "Logement & location",
 "strategie-lecture": "Stratégie de lecture",
 "vocab-consignes": "Consignes d'examen",
 "vocab-annonces": "Annonces & documents",
 "condition-si": "La condition (si)",
 "vocab-meubles": "Meubles & équipement",
 "vocab-quartier": "Le quartier",
 "tout-chaque": "Tout / chaque",
 "vocab-apparence": "L'apparence physique",
 "vocab-caractere": "Qualités & défauts",
 "vocab-nature": "Nature",
 "universite-vocab": "Université",
 "duree": "Durée (pendant/toujours)",
 "numbers-dates-heure": "Nombres · dates · heure",
 "qui-que": "Pronoms qui/que/où",
 "intensite": "Intensité (très/beaucoup)",
 "metier-travail-vocab": "Métier & Travail",
 "vocab-parcours-vie": "Parcours de vie",
 "vocab-loisirs": "Loisirs (activités)",
 "adjective-position": "Place de l'adjectif",
 "cest-il-est": "C'est / Il est",
 "character-adjectives": "Traits de caractère",
 "connectors-pour-parceque": "Connecteurs (pour / parce que)",
 "daily-routine-vocab": "Routine quotidienne",
 "demonstrative-adj": "Adjectifs démonstratifs",
 "frequency-adverbs": "Adverbes de fréquence",
 "giving-advice": "Donner un conseil",
 "household-chores": "Tâches ménagères",
 "ilfaut-devoir": "Il faut / devoir",
 "imperative-mood": "Impératif",
 "interdiction-demande": "Interdiction & demande",
 "on-vs-nous": "On vs nous",
 "passe-recent": "Passé récent (venir de)",
 "physical-description": "Description physique",
 "pouvoir-vouloir": "Pouvoir / vouloir",
 "prepositions-lieu2": "Prép. de lieu (2)",
 "social-invitations": "Inviter & répondre",
 "vocab-alimentation": "Alimentation",
 "vocab-clothing-size": "Vêtements & tailles",
 "vocab-places-city": "Lieux de la ville",
 "vocab-shopping": "Faire les courses",
 "vocab-sport-activities": "Activités sportives",
 "vocab-sport-gym": "Salle de sport",
 "vocab-tech-objects": "Objets technologiques",
 "vocab-vacances": "Les vacances",
 "vocab-weather-season": "Météo & saisons",
 "voici-voila": "Voici / voilà",
 "pronoms-possessifs": "Pronoms possessifs",
 "futur-simple": "Futur simple",
 "vocab-innovation": "Sciences & techniques",
 "vocab-reseaux": "Réseaux sociaux",
 "vocab-technologies": "Technologies de la communication",
 "vocab-aliments": "Les aliments & la cuisine",
 "restriction-ne-que": "La restriction (ne...que)",
 "vocab-restauration": "La restauration",
 "pronoms-cod-coi": "Pronoms COD/COI",
 "corps-sante-vocab": "Le corps et la santé",
 "superlatif": "Le superlatif",
 "pronoms-interrogatifs": "Pronoms interrogatifs (lequel)",
 "medecine-urgences-vocab": "La médecine et les urgences",
 "cause-consequence": "Cause et conséquence",
 "medias-vocab": "L'info, la presse, la télé",
 "preference-interet": "Préférence et intérêt",
 "subjonctif-present": "Subjonctif présent",
 "conditionnel-present": "Conditionnel présent",
 "gerondif": "Le gérondif",
 "vocab-consommation": "La consommation",
 "medias-audio-reseaux": "Médias audios et réseaux sociaux",
 "critique-film": "Faire une critique",
 "place-pronoms-cod-coi": "Place des pronoms COD/COI"
};
